// Traductions partagées par le panneau AirParasiteDisplay et la section
// "Bilan air parasite" du rapport global Retro (GlobalRetroReport).
export const airParasiteTranslations = {
  fr: {
    titlePanel: 'Air parasite par ligne',
    titleReport: 'Bilan air parasite par ligne',
    equipment: 'Équipement',
    airNet: 'Air injecté net',
    airParasite: 'Air parasite',
    airIn: 'Air entrant',
    airDecolm: 'Air décolmatage',
    total: 'Total',
    close: 'Fermer',
    noData: "Aucun débit d'air parasite disponible pour cette ligne.",
    line: 'Ligne',
  },
  en: {
    titlePanel: 'Parasitic air by line',
    titleReport: 'Parasitic air balance by line',
    equipment: 'Equipment',
    airNet: 'Net injected air',
    airParasite: 'Parasitic air',
    airIn: 'Incoming air',
    airDecolm: 'Cleaning air',
    total: 'Total',
    close: 'Close',
    noData: 'No parasitic air flow available for this line.',
    line: 'Line',
  },
  es: {
    titlePanel: 'Aire parásito por línea',
    titleReport: 'Balance de aire parásito por línea',
    equipment: 'Equipo',
    airNet: 'Aire inyectado neto',
    airParasite: 'Aire parásito',
    airIn: 'Aire entrante',
    airDecolm: 'Aire de limpieza',
    total: 'Total',
    close: 'Cerrar',
    noData: 'No hay caudal de aire parásito disponible para esta línea.',
    line: 'Línea',
  },
  de: {
    titlePanel: 'Falschluft pro Linie',
    titleReport: 'Falschluftbilanz pro Linie',
    equipment: 'Anlage',
    airNet: 'Netto eingeblasene Luft',
    airParasite: 'Falschluft',
    airIn: 'Eintretende Luft',
    airDecolm: 'Abreinigungsluft',
    total: 'Gesamt',
    close: 'Schließen',
    noData: 'Kein Falschluftstrom für diese Linie verfügbar.',
    line: 'Linie',
  },
  it: {
    titlePanel: 'Aria parassita per linea',
    titleReport: 'Bilancio aria parassita per linea',
    equipment: 'Apparecchiatura',
    airNet: 'Aria iniettata netta',
    airParasite: 'Aria parassita',
    airIn: 'Aria entrante',
    airDecolm: 'Aria di pulizia',
    total: 'Totale',
    close: 'Chiudi',
    noData: "Nessuna portata d'aria parassita disponibile per questa linea.",
    line: 'Linea',
  },
  pt: {
    titlePanel: 'Ar parasita por linha',
    titleReport: 'Balanço de ar parasita por linha',
    equipment: 'Equipamento',
    airNet: 'Ar injetado líquido',
    airParasite: 'Ar parasita',
    airIn: 'Ar de entrada',
    airDecolm: 'Ar de limpeza',
    total: 'Total',
    close: 'Fechar',
    noData: 'Nenhum fluxo de ar parasita disponível para esta linha.',
    line: 'Linha',
  },
  ru: {
    titlePanel: 'Паразитный воздух по линиям',
    titleReport: 'Баланс паразитного воздуха по линиям',
    equipment: 'Оборудование',
    airNet: 'Чистый впрыскиваемый воздух',
    airParasite: 'Паразитный воздух',
    airIn: 'Входящий воздух',
    airDecolm: 'Воздух очистки',
    total: 'Итого',
    close: 'Закрыть',
    noData: 'Нет данных о паразитном воздухе для этой линии.',
    line: 'Линия',
  },
  zh: {
    titlePanel: '各线寄生空气',
    titleReport: '各线寄生空气平衡',
    equipment: '设备',
    airNet: '净注入空气',
    airParasite: '寄生空气',
    airIn: '进入空气',
    airDecolm: '清灰空气',
    total: '合计',
    close: '关闭',
    noData: '该线路无可用寄生空气流量。',
    line: '线',
  },
  ja: {
    titlePanel: 'ラインごとの寄生空気',
    titleReport: 'ラインごとの寄生空気収支',
    equipment: '設備',
    airNet: '正味注入空気',
    airParasite: '寄生空気',
    airIn: '流入空気',
    airDecolm: '払い落とし空気',
    total: '合計',
    close: '閉じる',
    noData: 'このラインで利用可能な寄生空気流量はありません。',
    line: 'ライン',
  },
  ar: {
    titlePanel: 'الهواء الطفيلي حسب الخط',
    titleReport: 'موازنة الهواء الطفيلي حسب الخط',
    equipment: 'المعدات',
    airNet: 'الهواء المحقون الصافي',
    airParasite: 'هواء طفيلي',
    airIn: 'الهواء الداخل',
    airDecolm: 'هواء التنظيف',
    total: 'الإجمالي',
    close: 'إغلاق',
    noData: 'لا يوجد تدفق هواء طفيلي متاح لهذا الخط.',
    line: 'خط',
  },
};

export const getAirParasiteT = (languageCode) =>
  airParasiteTranslations[languageCode] || airParasiteTranslations.en;
