export const translations = {
  fr: {
    // UI
    Parametres: "Paramètres",
    calculer_et_envoyer_data: "Calculer et envoyer données",
    ShowResults: "Afficher les résultats",
    Calculate: "Calculer",
    Clear: "Effacer",
    Close: "Fermer",
    InvalidInput: "Valeur d'entrée invalide",
    CalculationError: "Erreur lors du calcul",
    NoResults: "Aucun résultat disponible",
    NoInputData: "Aucune donnée d'entrée disponible",

    // Paramètres d'entrée
    fluide_secondaire: "Fluide secondaire",
    bilan_par: "Bilan par",
    T_fumees_sortie: "T fumées sortie",
    T_fumees_entree: "T fumées entrée",
    T_entree_fluide: "T entrée fluide",
    T_sortie_fluide: "T sortie fluide",
    debit_eau: "Débit eau",
    debit_air: "Débit air",
    rendement_echangeur: "Rendement échangeur",
    encrassement_echangeur: "Encrassement échangeur",
    PDC_echangeur: "PDC échangeur",

    // Résultats dataTUBEANDSHELL
    Q_FG_kWh: "Enthalpie cédée fumées",
    Q_utile_eau_kWh: "Enthalpie transmise au fluide",
    T_fluide_out: "T sortie fluide (calculée)",
    T_moyen_eau: "T moyenne fluide",
    m_eau_kg_h: "Débit fluide",
    D_TLM: "ΔT log. moyen",
    Fact_UA: "Facteur UA",
    Fact_U_list: "Coefficient U",
    Surface_m2: "Surface d'échange",

    // dataFlow — fumées
    T_FG: "T fumées propagée",
    P_mmCE: "Pression fumées",
    Qv_wet_Nm3_h: "Débit humide",
    Qv_sec_Nm3_h: "Débit sec",
    Qm_tot_kg_h: "Débit massique total",
    Qm_CO2_kg_h: "Débit CO₂",
    Qm_H2O_kg_h: "Débit H₂O",
    Qm_O2_kg_h: "Débit O₂",
    Qm_N2_kg_h: "Débit N₂",
    O2_dry_pourcent: "O₂ sec",
    O2_humide_pourcent: "O₂ humide",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ humide",
    CO2_dry_pourcent: "CO₂ sec",
    CO2_humide_pourcent: "CO₂ humide",
    H_CO2_kj: "Enthalpie CO₂",
    H_H2O_kj: "Enthalpie H₂O",
    H_O2_kj: "Enthalpie O₂",
    H_N2_kj: "Enthalpie N₂",
    H_tot_kj: "Enthalpie totale",
    H_tot_kW: "Puissance enthalpique",

    // Unités
    celsius: "°C",
    kWh: "kWh",
    kW: "kW",
    kWK: "kW/K",
    kWm2K: "kW/(m²·K)",
    m2: "m²",
    kg_h: "kg/h",
    Nm3_h: "Nm³/h",
    mmCE: "mmCE",
    pourcent: "%",
    kJ_h: "kJ/h",
  },

  en: {
    Parametres: "Parameters",
    calculer_et_envoyer_data: "Calculate and Send Data",
    ShowResults: "Show Results",
    Calculate: "Calculate",
    Clear: "Clear",
    Close: "Close",
    InvalidInput: "Invalid input value",
    CalculationError: "Calculation error",
    NoResults: "No results available",
    NoInputData: "No input data available",

    fluide_secondaire: "Secondary fluid",
    bilan_par: "Balance by",
    T_fumees_sortie: "Flue gas outlet temp.",
    T_fumees_entree: "Flue gas inlet temp.",
    T_entree_fluide: "Fluid inlet temp.",
    T_sortie_fluide: "Fluid outlet temp.",
    debit_eau: "Water flow rate",
    debit_air: "Air flow rate",
    rendement_echangeur: "Heat exchanger efficiency",
    encrassement_echangeur: "Fouling factor",
    PDC_echangeur: "HX pressure drop",

    Q_FG_kWh: "Flue gas heat given",
    Q_utile_eau_kWh: "Heat transferred to fluid",
    T_fluide_out: "Fluid outlet temp. (calc.)",
    T_moyen_eau: "Mean fluid temperature",
    m_eau_kg_h: "Fluid flow rate",
    D_TLM: "Log mean ΔT",
    Fact_UA: "UA factor",
    Fact_U_list: "U coefficient",
    Surface_m2: "Heat exchange area",

    T_FG: "Propagated flue gas temp.",
    P_mmCE: "Flue gas pressure",
    Qv_wet_Nm3_h: "Wet flow rate",
    Qv_sec_Nm3_h: "Dry flow rate",
    Qm_tot_kg_h: "Total mass flow",
    Qm_CO2_kg_h: "CO₂ flow",
    Qm_H2O_kg_h: "H₂O flow",
    Qm_O2_kg_h: "O₂ flow",
    Qm_N2_kg_h: "N₂ flow",
    O2_dry_pourcent: "O₂ dry",
    O2_humide_pourcent: "O₂ wet",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ wet",
    CO2_dry_pourcent: "CO₂ dry",
    CO2_humide_pourcent: "CO₂ wet",
    H_CO2_kj: "CO₂ enthalpy",
    H_H2O_kj: "H₂O enthalpy",
    H_O2_kj: "O₂ enthalpy",
    H_N2_kj: "N₂ enthalpy",
    H_tot_kj: "Total enthalpy",
    H_tot_kW: "Enthalpy power",

    celsius: "°C",
    kWh: "kWh",
    kW: "kW",
    kWK: "kW/K",
    kWm2K: "kW/(m²·K)",
    m2: "m²",
    kg_h: "kg/h",
    Nm3_h: "Nm³/h",
    mmCE: "mmWC",
    pourcent: "%",
    kJ_h: "kJ/h",
  },

  es: {
    Parametres: "Parámetros",
    calculer_et_envoyer_data: "Calcular y Enviar Datos",
    ShowResults: "Mostrar Resultados",
    Calculate: "Calcular",
    Clear: "Limpiar",
    Close: "Cerrar",
    InvalidInput: "Valor de entrada inválido",
    CalculationError: "Error de cálculo",
    NoResults: "No hay resultados disponibles",
    NoInputData: "No hay datos de entrada disponibles",

    fluide_secondaire: "Fluido secundario",
    bilan_par: "Balance por",
    T_fumees_sortie: "T gases salida",
    T_fumees_entree: "T gases entrada",
    T_entree_fluide: "T entrada fluido",
    T_sortie_fluide: "T salida fluido",
    debit_eau: "Caudal de agua",
    debit_air: "Caudal de aire",
    rendement_echangeur: "Rendimiento intercambiador",
    encrassement_echangeur: "Factor de ensuciamiento",
    PDC_echangeur: "Caída de presión IC",

    Q_FG_kWh: "Calor cedido gases",
    Q_utile_eau_kWh: "Calor transferido al fluido",
    T_fluide_out: "T salida fluido (calc.)",
    T_moyen_eau: "T media fluido",
    m_eau_kg_h: "Caudal fluido",
    D_TLM: "ΔT medio logarítmico",
    Fact_UA: "Factor UA",
    Fact_U_list: "Coef. U",
    Surface_m2: "Superficie de intercambio",

    T_FG: "T gases propagada",
    P_mmCE: "Presión gases",
    Qv_wet_Nm3_h: "Caudal húmedo",
    Qv_sec_Nm3_h: "Caudal seco",
    Qm_tot_kg_h: "Flujo másico total",
    Qm_CO2_kg_h: "Flujo CO₂",
    Qm_H2O_kg_h: "Flujo H₂O",
    Qm_O2_kg_h: "Flujo O₂",
    Qm_N2_kg_h: "Flujo N₂",
    O2_dry_pourcent: "O₂ seco",
    O2_humide_pourcent: "O₂ húmedo",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ húmedo",
    CO2_dry_pourcent: "CO₂ seco",
    CO2_humide_pourcent: "CO₂ húmedo",
    H_CO2_kj: "Entalpía CO₂",
    H_H2O_kj: "Entalpía H₂O",
    H_O2_kj: "Entalpía O₂",
    H_N2_kj: "Entalpía N₂",
    H_tot_kj: "Entalpía total",
    H_tot_kW: "Potencia entálpica",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmCA", pourcent: "%", kJ_h: "kJ/h",
  },

  de: {
    Parametres: "Parameter",
    calculer_et_envoyer_data: "Berechnen und Daten Senden",
    ShowResults: "Ergebnisse Anzeigen",
    Calculate: "Berechnen",
    Clear: "Löschen",
    Close: "Schließen",
    InvalidInput: "Ungültiger Eingabewert",
    CalculationError: "Berechnungsfehler",
    NoResults: "Keine Ergebnisse verfügbar",
    NoInputData: "Keine Eingabedaten verfügbar",

    fluide_secondaire: "Sekundärfluid",
    bilan_par: "Bilanz nach",
    T_fumees_sortie: "Rauchgastemperatur Ausgang",
    T_fumees_entree: "Rauchgastemperatur Eingang",
    T_entree_fluide: "Fluid-Eintrittstemperatur",
    T_sortie_fluide: "Fluid-Austrittstemperatur",
    debit_eau: "Wasserdurchfluss",
    debit_air: "Luftdurchfluss",
    rendement_echangeur: "Wärmetauscher-Wirkungsgrad",
    encrassement_echangeur: "Verschmutzungsfaktor",
    PDC_echangeur: "Druckverlust WT",

    Q_FG_kWh: "Abgegebene Wärme Rauchgas",
    Q_utile_eau_kWh: "Übertragene Wärme",
    T_fluide_out: "Fluid-Austrittstemperatur (ber.)",
    T_moyen_eau: "Mittlere Fluidtemperatur",
    m_eau_kg_h: "Fluiddurchfluss",
    D_TLM: "Mittlere log. Temperaturdifferenz",
    Fact_UA: "UA-Faktor",
    Fact_U_list: "U-Koeffizient",
    Surface_m2: "Wärmeübertragungsfläche",

    T_FG: "Propagierte Rauchgastemperatur",
    P_mmCE: "Rauchgasdruck",
    Qv_wet_Nm3_h: "Feuchter Volumenstrom",
    Qv_sec_Nm3_h: "Trockener Volumenstrom",
    Qm_tot_kg_h: "Gesamtmassenstrom",
    Qm_CO2_kg_h: "CO₂-Strom",
    Qm_H2O_kg_h: "H₂O-Strom",
    Qm_O2_kg_h: "O₂-Strom",
    Qm_N2_kg_h: "N₂-Strom",
    O2_dry_pourcent: "O₂ trocken",
    O2_humide_pourcent: "O₂ feucht",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ feucht",
    CO2_dry_pourcent: "CO₂ trocken",
    CO2_humide_pourcent: "CO₂ feucht",
    H_CO2_kj: "Enthalpie CO₂",
    H_H2O_kj: "Enthalpie H₂O",
    H_O2_kj: "Enthalpie O₂",
    H_N2_kj: "Enthalpie N₂",
    H_tot_kj: "Gesamtenthalpie",
    H_tot_kW: "Enthalpie-Leistung",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmWS", pourcent: "%", kJ_h: "kJ/h",
  },

  it: {
    Parametres: "Parametri",
    calculer_et_envoyer_data: "Calcola e Invia Dati",
    ShowResults: "Mostra Risultati",
    Calculate: "Calcola",
    Clear: "Cancella",
    Close: "Chiudi",
    InvalidInput: "Valore di input non valido",
    CalculationError: "Errore di calcolo",
    NoResults: "Nessun risultato disponibile",
    NoInputData: "Nessun dato di input disponibile",

    fluide_secondaire: "Fluido secondario",
    bilan_par: "Bilancio per",
    T_fumees_sortie: "T gas uscita",
    T_fumees_entree: "T gas entrata",
    T_entree_fluide: "T ingresso fluido",
    T_sortie_fluide: "T uscita fluido",
    debit_eau: "Portata acqua",
    debit_air: "Portata aria",
    rendement_echangeur: "Rendimento scambiatore",
    encrassement_echangeur: "Fattore di sporcamento",
    PDC_echangeur: "Perdita di carico SC",

    Q_FG_kWh: "Calore ceduto gas",
    Q_utile_eau_kWh: "Calore trasferito al fluido",
    T_fluide_out: "T uscita fluido (calc.)",
    T_moyen_eau: "T media fluido",
    m_eau_kg_h: "Portata fluido",
    D_TLM: "ΔT medio logaritmico",
    Fact_UA: "Fattore UA",
    Fact_U_list: "Coeff. U",
    Surface_m2: "Superficie di scambio",

    T_FG: "T gas propagata",
    P_mmCE: "Pressione gas",
    Qv_wet_Nm3_h: "Portata umida",
    Qv_sec_Nm3_h: "Portata secca",
    Qm_tot_kg_h: "Portata massica totale",
    Qm_CO2_kg_h: "Portata CO₂",
    Qm_H2O_kg_h: "Portata H₂O",
    Qm_O2_kg_h: "Portata O₂",
    Qm_N2_kg_h: "Portata N₂",
    O2_dry_pourcent: "O₂ secco",
    O2_humide_pourcent: "O₂ umido",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ umido",
    CO2_dry_pourcent: "CO₂ secco",
    CO2_humide_pourcent: "CO₂ umido",
    H_CO2_kj: "Entalpia CO₂",
    H_H2O_kj: "Entalpia H₂O",
    H_O2_kj: "Entalpia O₂",
    H_N2_kj: "Entalpia N₂",
    H_tot_kj: "Entalpia totale",
    H_tot_kW: "Potenza entalpica",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmCA", pourcent: "%", kJ_h: "kJ/h",
  },

  pt: {
    Parametres: "Parâmetros",
    calculer_et_envoyer_data: "Calcular e Enviar Dados",
    ShowResults: "Mostrar Resultados",
    Calculate: "Calcular",
    Clear: "Limpar",
    Close: "Fechar",
    InvalidInput: "Valor de entrada inválido",
    CalculationError: "Erro de cálculo",
    NoResults: "Nenhum resultado disponível",
    NoInputData: "Nenhum dado de entrada disponível",

    fluide_secondaire: "Fluido secundário",
    bilan_par: "Balanço por",
    T_fumees_sortie: "T gases saída",
    T_fumees_entree: "T gases entrada",
    T_entree_fluide: "T entrada fluido",
    T_sortie_fluide: "T saída fluido",
    debit_eau: "Vazão de água",
    debit_air: "Vazão de ar",
    rendement_echangeur: "Rendimento trocador",
    encrassement_echangeur: "Fator de incrustação",
    PDC_echangeur: "Queda de pressão TC",

    Q_FG_kWh: "Calor cedido gases",
    Q_utile_eau_kWh: "Calor transferido ao fluido",
    T_fluide_out: "T saída fluido (calc.)",
    T_moyen_eau: "T média fluido",
    m_eau_kg_h: "Vazão fluido",
    D_TLM: "ΔT médio logarítmico",
    Fact_UA: "Fator UA",
    Fact_U_list: "Coef. U",
    Surface_m2: "Área de troca",

    T_FG: "T gases propagada",
    P_mmCE: "Pressão gases",
    Qv_wet_Nm3_h: "Vazão úmida",
    Qv_sec_Nm3_h: "Vazão seca",
    Qm_tot_kg_h: "Fluxo mássico total",
    Qm_CO2_kg_h: "Fluxo CO₂",
    Qm_H2O_kg_h: "Fluxo H₂O",
    Qm_O2_kg_h: "Fluxo O₂",
    Qm_N2_kg_h: "Fluxo N₂",
    O2_dry_pourcent: "O₂ seco",
    O2_humide_pourcent: "O₂ úmido",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ úmido",
    CO2_dry_pourcent: "CO₂ seco",
    CO2_humide_pourcent: "CO₂ úmido",
    H_CO2_kj: "Entalpia CO₂",
    H_H2O_kj: "Entalpia H₂O",
    H_O2_kj: "Entalpia O₂",
    H_N2_kj: "Entalpia N₂",
    H_tot_kj: "Entalpia total",
    H_tot_kW: "Potência entálpica",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmCA", pourcent: "%", kJ_h: "kJ/h",
  },

  zh: {
    Parametres: "参数",
    calculer_et_envoyer_data: "计算并发送数据",
    ShowResults: "显示结果",
    Calculate: "计算",
    Clear: "清除",
    Close: "关闭",
    InvalidInput: "输入值无效",
    CalculationError: "计算错误",
    NoResults: "没有可用结果",
    NoInputData: "没有可用的输入数据",

    fluide_secondaire: "二次流体",
    bilan_par: "按以下平衡",
    T_fumees_sortie: "烟气出口温度",
    T_fumees_entree: "烟气入口温度",
    T_entree_fluide: "流体入口温度",
    T_sortie_fluide: "流体出口温度",
    debit_eau: "水流量",
    debit_air: "空气流量",
    rendement_echangeur: "换热器效率",
    encrassement_echangeur: "污垢系数",
    PDC_echangeur: "换热器压降",

    Q_FG_kWh: "烟气放热量",
    Q_utile_eau_kWh: "流体吸热量",
    T_fluide_out: "流体出口温度（计算）",
    T_moyen_eau: "流体平均温度",
    m_eau_kg_h: "流体流量",
    D_TLM: "对数平均温差",
    Fact_UA: "UA系数",
    Fact_U_list: "传热系数U",
    Surface_m2: "换热面积",

    T_FG: "传播烟气温度",
    P_mmCE: "烟气压力",
    Qv_wet_Nm3_h: "湿烟气流量",
    Qv_sec_Nm3_h: "干烟气流量",
    Qm_tot_kg_h: "总质量流量",
    Qm_CO2_kg_h: "CO₂流量",
    Qm_H2O_kg_h: "H₂O流量",
    Qm_O2_kg_h: "O₂流量",
    Qm_N2_kg_h: "N₂流量",
    O2_dry_pourcent: "干O₂",
    O2_humide_pourcent: "湿O₂",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "湿N₂",
    CO2_dry_pourcent: "干CO₂",
    CO2_humide_pourcent: "湿CO₂",
    H_CO2_kj: "CO₂焓",
    H_H2O_kj: "H₂O焓",
    H_O2_kj: "O₂焓",
    H_N2_kj: "N₂焓",
    H_tot_kj: "总焓",
    H_tot_kW: "焓功率",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmWC", pourcent: "%", kJ_h: "kJ/h",
  },

  ja: {
    Parametres: "パラメータ",
    calculer_et_envoyer_data: "計算してデータ送信",
    ShowResults: "結果を表示",
    Calculate: "計算",
    Clear: "クリア",
    Close: "閉じる",
    InvalidInput: "無効な入力値",
    CalculationError: "計算エラー",
    NoResults: "利用可能な結果がありません",
    NoInputData: "利用可能な入力データがありません",

    fluide_secondaire: "二次流体",
    bilan_par: "バランス基準",
    T_fumees_sortie: "排ガス出口温度",
    T_fumees_entree: "排ガス入口温度",
    T_entree_fluide: "流体入口温度",
    T_sortie_fluide: "流体出口温度",
    debit_eau: "水流量",
    debit_air: "空気流量",
    rendement_echangeur: "熱交換器効率",
    encrassement_echangeur: "汚れ係数",
    PDC_echangeur: "熱交換器圧力損失",

    Q_FG_kWh: "排ガス放熱量",
    Q_utile_eau_kWh: "流体への伝熱量",
    T_fluide_out: "流体出口温度（計算）",
    T_moyen_eau: "流体平均温度",
    m_eau_kg_h: "流体流量",
    D_TLM: "対数平均温度差",
    Fact_UA: "UA係数",
    Fact_U_list: "熱通過率U",
    Surface_m2: "伝熱面積",

    T_FG: "伝播排ガス温度",
    P_mmCE: "排ガス圧力",
    Qv_wet_Nm3_h: "湿り排ガス流量",
    Qv_sec_Nm3_h: "乾燥排ガス流量",
    Qm_tot_kg_h: "総質量流量",
    Qm_CO2_kg_h: "CO₂流量",
    Qm_H2O_kg_h: "H₂O流量",
    Qm_O2_kg_h: "O₂流量",
    Qm_N2_kg_h: "N₂流量",
    O2_dry_pourcent: "乾燥O₂",
    O2_humide_pourcent: "湿潤O₂",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "湿潤N₂",
    CO2_dry_pourcent: "乾燥CO₂",
    CO2_humide_pourcent: "湿潤CO₂",
    H_CO2_kj: "CO₂エンタルピー",
    H_H2O_kj: "H₂Oエンタルピー",
    H_O2_kj: "O₂エンタルピー",
    H_N2_kj: "N₂エンタルピー",
    H_tot_kj: "全エンタルピー",
    H_tot_kW: "エンタルピー出力",

    celsius: "°C", kWh: "kWh", kW: "kW", kWK: "kW/K", kWm2K: "kW/(m²·K)",
    m2: "m²", kg_h: "kg/h", Nm3_h: "Nm³/h", mmCE: "mmWC", pourcent: "%", kJ_h: "kJ/h",
  },

  ru: {
    Parametres: "Параметры",
    calculer_et_envoyer_data: "Вычислить и отправить данные",
    ShowResults: "Показать результаты",
    Calculate: "Вычислить",
    Clear: "Очистить",
    Close: "Закрыть",
    InvalidInput: "Недопустимое входное значение",
    CalculationError: "Ошибка вычисления",
    NoResults: "Нет доступных результатов",
    NoInputData: "Нет доступных входных данных",

    fluide_secondaire: "Вторичная среда",
    bilan_par: "Баланс по",
    T_fumees_sortie: "Т дымовых газов на выходе",
    T_fumees_entree: "Т дымовых газов на входе",
    T_entree_fluide: "Т входа теплоносителя",
    T_sortie_fluide: "Т выхода теплоносителя",
    debit_eau: "Расход воды",
    debit_air: "Расход воздуха",
    rendement_echangeur: "КПД теплообменника",
    encrassement_echangeur: "Коэффициент загрязнения",
    PDC_echangeur: "Потери давления ТО",

    Q_FG_kWh: "Теплоотдача дымовых газов",
    Q_utile_eau_kWh: "Теплопередача теплоносителю",
    T_fluide_out: "Т выхода (расч.)",
    T_moyen_eau: "Средняя Т теплоносителя",
    m_eau_kg_h: "Расход теплоносителя",
    D_TLM: "Среднелогарифмическая ΔТ",
    Fact_UA: "Коэффициент UA",
    Fact_U_list: "Коэффициент теплопередачи U",
    Surface_m2: "Поверхность теплообмена",

    T_FG: "Распространяемая Т газов",
    P_mmCE: "Давление газов",
    Qv_wet_Nm3_h: "Влажный объёмный расход",
    Qv_sec_Nm3_h: "Сухой объёмный расход",
    Qm_tot_kg_h: "Суммарный массовый расход",
    Qm_CO2_kg_h: "Расход CO₂",
    Qm_H2O_kg_h: "Расход H₂O",
    Qm_O2_kg_h: "Расход O₂",
    Qm_N2_kg_h: "Расход N₂",
    O2_dry_pourcent: "O₂ сухой",
    O2_humide_pourcent: "O₂ влажный",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ влажный",
    CO2_dry_pourcent: "CO₂ сухой",
    CO2_humide_pourcent: "CO₂ влажный",
    H_CO2_kj: "Энтальпия CO₂",
    H_H2O_kj: "Энтальпия H₂O",
    H_O2_kj: "Энтальпия O₂",
    H_N2_kj: "Энтальпия N₂",
    H_tot_kj: "Полная энтальпия",
    H_tot_kW: "Энтальпийная мощность",

    celsius: "°C", kWh: "кВт·ч", kW: "кВт", kWK: "кВт/К", kWm2K: "кВт/(м²·К)",
    m2: "м²", kg_h: "кг/ч", Nm3_h: "нм³/ч", mmCE: "мм вод.ст.", pourcent: "%", kJ_h: "кДж/ч",
  },

  ar: {
    Parametres: "المعاملات",
    calculer_et_envoyer_data: "احسب وأرسل البيانات",
    ShowResults: "إظهار النتائج",
    Calculate: "احسب",
    Clear: "مسح",
    Close: "إغلاق",
    InvalidInput: "قيمة إدخال غير صالحة",
    CalculationError: "خطأ في الحساب",
    NoResults: "لا توجد نتائج متاحة",
    NoInputData: "لا توجد بيانات إدخال متاحة",

    fluide_secondaire: "السائل الثانوي",
    bilan_par: "الميزان حسب",
    T_fumees_sortie: "درجة حرارة الغازات عند الخروج",
    T_fumees_entree: "درجة حرارة الغازات عند الدخول",
    T_entree_fluide: "درجة حرارة دخول السائل",
    T_sortie_fluide: "درجة حرارة خروج السائل",
    debit_eau: "تدفق الماء",
    debit_air: "تدفق الهواء",
    rendement_echangeur: "مردود المبادل الحراري",
    encrassement_echangeur: "معامل التلوث",
    PDC_echangeur: "فقدان الضغط في المبادل",

    Q_FG_kWh: "الحرارة المنبعثة من الغازات",
    Q_utile_eau_kWh: "الحرارة المنقولة للسائل",
    T_fluide_out: "درجة حرارة خروج السائل (محسوبة)",
    T_moyen_eau: "متوسط درجة حرارة السائل",
    m_eau_kg_h: "تدفق السائل",
    D_TLM: "فرق الحرارة اللوغاريتمي",
    Fact_UA: "معامل UA",
    Fact_U_list: "معامل الانتقال الحراري U",
    Surface_m2: "سطح التبادل الحراري",

    T_FG: "درجة حرارة الغازات المنتشرة",
    P_mmCE: "ضغط الغازات",
    Qv_wet_Nm3_h: "التدفق الرطب",
    Qv_sec_Nm3_h: "التدفق الجاف",
    Qm_tot_kg_h: "التدفق الكتلي الإجمالي",
    Qm_CO2_kg_h: "تدفق CO₂",
    Qm_H2O_kg_h: "تدفق H₂O",
    Qm_O2_kg_h: "تدفق O₂",
    Qm_N2_kg_h: "تدفق N₂",
    O2_dry_pourcent: "O₂ جاف",
    O2_humide_pourcent: "O₂ رطب",
    H2O_pourcent: "H₂O",
    N2_humide_pourcent: "N₂ رطب",
    CO2_dry_pourcent: "CO₂ جاف",
    CO2_humide_pourcent: "CO₂ رطب",
    H_CO2_kj: "إنثالبي CO₂",
    H_H2O_kj: "إنثالبي H₂O",
    H_O2_kj: "إنثالبي O₂",
    H_N2_kj: "إنثالبي N₂",
    H_tot_kj: "الإنثالبي الكلي",
    H_tot_kW: "قدرة الإنثالبي",

    celsius: "°م", kWh: "كيلوواط·ساعة", kW: "كيلوواط", kWK: "كيلوواط/كلفن",
    kWm2K: "كيلوواط/(م²·كلفن)", m2: "م²", kg_h: "كغ/س", Nm3_h: "نم³/س",
    mmCE: "ملم عمود ماء", pourcent: "%", kJ_h: "كيلوجول/س",
  },
};
