export const translations = {
  // ========================================
  // FRANÇAIS
  // ========================================
  fr: {
    // === Common / Commun ===
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Clear memory': 'Effacer la mémoire',
    'Flue gas composition': 'Composition des fumées',
    'Input flue gas': 'Fumées en entrée',
    'Output flue gas': 'Fumées en sortie',
    'Residues calculated': 'Résidus calculés',

    // === Equipment Configuration / Configuration des équipements ===
    'Equipment Configuration': 'Configuration des équipements',
    'Fan Type': 'Type de ventilateur',
    'Motor Type': 'Type de moteur',
    'Transmission Type': 'Type de transmission',

    // === Fan Types / Types de ventilateurs ===
    'Optimized centrifugal fan': 'Ventilateur centrifuge optimisé',
    'Standard centrifugal fan': 'Ventilateur centrifuge standard',
    'Optimized axial fan': 'Ventilateur axial optimisé',
    'Standard axial fan': 'Ventilateur axial standard',

    // === Motor Types / Types de moteurs ===
    'High efficiency motor (IE3/IE4)': 'Moteur haute efficacité (IE3/IE4)',
    'Standard motor (IE2)': 'Moteur standard (IE2)',

    // === Transmission Types / Types de transmission ===
    'Direct transmission': 'Transmission directe',
    'Belt transmission': 'Transmission par courroies',
    'Gear reducer': 'Réducteur à engrenages',

    // === Input Parameters / Paramètres d'entrée ===
    'Electrical yield [%]': 'Rendement électrique [%]',
    'Radiative losses [%]': 'Pertes radiatives [%]',
    'Outlet pressure [mmCE]': 'Pression de sortie [mmCE]',
    'Ambient air temperature [°C]': 'Température de l\'air ambiant [°C]',
    'Safety factor [-]': 'Facteur de sécurité [-]',
    'Fly ashes content outlet [g/Nm3]': 'Teneur en cendres volantes sortie [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité des mâchefers [%]',
    'O2 ref [%]': 'O2 référence [%]',

    // === Calculated Values / Valeurs calculées ===
    'Flow rate [m³/h at conditions]': 'Débit volumique [m³/h aux conditions]',
    'Total pressure drop [mmCE]': 'Perte de charge totale [mmCE]',
    'Aeraulic power [kW]': 'Puissance aéraulique [kW]',
    'Mechanical power [kW]': 'Puissance mécanique [kW]',
    'Electrical power (before safety) [kWe]': 'Puissance électrique (avant sécurité) [kWe]',
    'Electrical power (with safety) [kWe]': 'Puissance électrique (avec sécurité) [kWe]',
    'Fan efficiency [%]': 'Rendement ventilateur [%]',
    'Motor efficiency [%]': 'Rendement moteur [%]',
    'Transmission efficiency [%]': 'Rendement transmission [%]',
    'Global efficiency [%]': 'Rendement global [%]',
    'Temperature inlet IDFAN [°C]': 'Température entrée IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Température sortie IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Élévation de température (calculée) [°C]',
    'Power transmitted to flue gas [kW]': 'Puissance transmise aux fumées [kW]',
    'Power lost to ambient [kW]': 'Puissance perdue vers l\'ambiance [kW]',
    'Pressure inlet [mmCE]': 'Pression entrée [mmCE]',
    'Waste Flow [kg/h]': 'Débit de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Débit de fumées humides [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Débit de fumées sèches [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'Fly ash inlet [kg/h]': 'Cendres volantes entrée [kg/h]',
    'Fly ash outlet [kg/h]': 'Cendres volantes sortie [kg/h]',
    'IDFAN ash collected [kg/h]': 'Cendres collectées IDFAN [kg/h]',
    'Flue gas inlet at inlet temperature': 'Fumées en entrée à la température d\'entrée',
    'Flue gas outlet at outlet temperature': 'Fumées en sortie à la température de sortie',

    // === Help Page / Page d'aide ===
    'ID FAN (Induced Draft Fan)': 'ID FAN (Ventilateur de Tirage Induit)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'Pour un ID FAN (ventilateur de tirage induit), le rendement global typique se situe entre 60% et 75%, selon la configuration et la qualité des équipements.',
    'Detail by component:': 'Détail par composant :',
    'Centrifugal fan': 'Ventilateur centrifuge',
    'Efficiency: 70-80% (optimized)': 'Rendement : 70-80% (optimisé)',
    'Efficiency: 60-75% (standard)': 'Rendement : 60-75% (standard)',
    'Electric motor': 'Moteur électrique',
    'Efficiency: 90-95% (high efficiency motor)': 'Rendement : 90-95% (moteur haute efficacité)',
    'Efficiency: 85-92% (standard motor)': 'Rendement : 85-92% (moteur standard)',
    'Transmission': 'Transmission',
    'Direct: 98-99%': 'Directe : 98-99%',
    'Belts: 94-96%': 'Courroies : 94-96%',
    'Gear reducer: 95-98%': 'Réducteur : 95-98%',
    'Overall efficiency calculation:': 'Calcul du rendement global :',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_ventilateur × η_moteur × η_transmission',
    'Optimal configuration:': 'Configuration optimale :',
    'Fan: 75%': 'Ventilateur : 75%',
    'Motor: 93%': 'Moteur : 93%',
    'Direct transmission: 98%': 'Transmission directe : 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Rendement global = 0,75 × 0,93 × 0,98 = 68%',
    'Standard configuration:': 'Configuration standard :',
    'Fan: 65%': 'Ventilateur : 65%',
    'Motor: 90%': 'Moteur : 90%',
    'Belt transmission: 95%': 'Transmission par courroies : 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Rendement global = 0,65 × 0,90 × 0,95 = 56%',
    'Recommendations for your code:': 'Recommandations pour votre code :',
    'For typical industrial applications, I recommend these default values:': 'Pour des applications industrielles typiques, je recommande ces valeurs par défaut :',
    'Realistic for a good fan': 'Réaliste pour un bon ventilateur',
    'Standard IE3 motor': 'Moteur IE3 standard',
    'Quality belt transmission': 'Transmission par courroies de qualité',
    'Standard safety factor': 'Facteur de sécurité standard',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Rendement global résultant : 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Facteurs d\'influence :',
    'Size: Large fans have better efficiencies': 'Taille : Les gros ventilateurs ont de meilleurs rendements',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Point de fonctionnement : Optimal près du BEP (Best Efficiency Point)',
    'Wear: Efficiency decreases with fouling': 'Usure : Le rendement diminue avec l\'encrassement',
    'Variable speed: Improves efficiency at partial load': 'Vitesse variable : Améliore l\'efficacité à charge partielle',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'Un rendement global de 65% est une bonne valeur de référence pour un ID FAN bien dimensionné.',
  },

  // ========================================
  // ENGLISH
  // ========================================
  en: {
    // === Common ===
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Clear memory': 'Clear memory',
    'Flue gas composition': 'Flue gas composition',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',
    'Residues calculated': 'Residues calculated',

    // === Equipment Configuration ===
    'Equipment Configuration': 'Equipment Configuration',
    'Fan Type': 'Fan Type',
    'Motor Type': 'Motor Type',
    'Transmission Type': 'Transmission Type',

    // === Fan Types ===
    'Optimized centrifugal fan': 'Optimized centrifugal fan',
    'Standard centrifugal fan': 'Standard centrifugal fan',
    'Optimized axial fan': 'Optimized axial fan',
    'Standard axial fan': 'Standard axial fan',

    // === Motor Types ===
    'High efficiency motor (IE3/IE4)': 'High efficiency motor (IE3/IE4)',
    'Standard motor (IE2)': 'Standard motor (IE2)',

    // === Transmission Types ===
    'Direct transmission': 'Direct transmission',
    'Belt transmission': 'Belt transmission',
    'Gear reducer': 'Gear reducer',

    // === Input Parameters ===
    'Electrical yield [%]': 'Electrical yield [%]',
    'Radiative losses [%]': 'Radiative losses [%]',
    'Outlet pressure [mmCE]': 'Outlet pressure [mmWC]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Safety factor [-]': 'Safety factor [-]',
    'Fly ashes content outlet [g/Nm3]': 'Fly ashes content outlet [g/Nm3]',
    'siccity bottom ash [%]': 'Siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',

    // === Calculated Values ===
    'Flow rate [m³/h at conditions]': 'Flow rate [m³/h at conditions]',
    'Total pressure drop [mmCE]': 'Total pressure drop [mmWC]',
    'Aeraulic power [kW]': 'Aeraulic power [kW]',
    'Mechanical power [kW]': 'Mechanical power [kW]',
    'Electrical power (before safety) [kWe]': 'Electrical power (before safety) [kWe]',
    'Electrical power (with safety) [kWe]': 'Electrical power (with safety) [kWe]',
    'Fan efficiency [%]': 'Fan efficiency [%]',
    'Motor efficiency [%]': 'Motor efficiency [%]',
    'Transmission efficiency [%]': 'Transmission efficiency [%]',
    'Global efficiency [%]': 'Global efficiency [%]',
    'Temperature inlet IDFAN [°C]': 'Temperature inlet IDFAN [°C]',
    'Temperature outlet IDFAN [°C]': 'Temperature outlet IDFAN [°C]',
    'Temperature rise (calculated) [°C]': 'Temperature rise (calculated) [°C]',
    'Power transmitted to flue gas [kW]': 'Power transmitted to flue gas [kW]',
    'Power lost to ambient [kW]': 'Power lost to ambient [kW]',
    'Pressure inlet [mmCE]': 'Pressure inlet [mmWC]',
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'Fly ash inlet [kg/h]': 'Fly ash inlet [kg/h]',
    'Fly ash outlet [kg/h]': 'Fly ash outlet [kg/h]',
    'IDFAN ash collected [kg/h]': 'IDFAN ash collected [kg/h]',
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',

    // === Help Page ===
    'ID FAN (Induced Draft Fan)': 'ID FAN (Induced Draft Fan)',
    'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.': 'For an ID FAN (induced draft fan), typical overall efficiency ranges between 60% and 75%, depending on configuration and equipment quality.',
    'Detail by component:': 'Detail by component:',
    'Centrifugal fan': 'Centrifugal fan',
    'Efficiency: 70-80% (optimized)': 'Efficiency: 70-80% (optimized)',
    'Efficiency: 60-75% (standard)': 'Efficiency: 60-75% (standard)',
    'Electric motor': 'Electric motor',
    'Efficiency: 90-95% (high efficiency motor)': 'Efficiency: 90-95% (high efficiency motor)',
    'Efficiency: 85-92% (standard motor)': 'Efficiency: 85-92% (standard motor)',
    'Transmission': 'Transmission',
    'Direct: 98-99%': 'Direct: 98-99%',
    'Belts: 94-96%': 'Belts: 94-96%',
    'Gear reducer: 95-98%': 'Gear reducer: 95-98%',
    'Overall efficiency calculation:': 'Overall efficiency calculation:',
    'η_global = η_fan × η_motor × η_transmission': 'η_global = η_fan × η_motor × η_transmission',
    'Optimal configuration:': 'Optimal configuration:',
    'Fan: 75%': 'Fan: 75%',
    'Motor: 93%': 'Motor: 93%',
    'Direct transmission: 98%': 'Direct transmission: 98%',
    'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%': 'Overall efficiency = 0.75 × 0.93 × 0.98 = 68%',
    'Standard configuration:': 'Standard configuration:',
    'Fan: 65%': 'Fan: 65%',
    'Motor: 90%': 'Motor: 90%',
    'Belt transmission: 95%': 'Belt transmission: 95%',
    'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%': 'Overall efficiency = 0.65 × 0.90 × 0.95 = 56%',
    'Recommendations for your code:': 'Recommendations for your code:',
    'For typical industrial applications, I recommend these default values:': 'For typical industrial applications, I recommend these default values:',
    'Realistic for a good fan': 'Realistic for a good fan',
    'Standard IE3 motor': 'Standard IE3 motor',
    'Quality belt transmission': 'Quality belt transmission',
    'Standard safety factor': 'Standard safety factor',
    'Resulting overall efficiency: 72% × 91% × 97% = 63%': 'Resulting overall efficiency: 72% × 91% × 97% = 63%',
    'Influencing factors:': 'Influencing factors:',
    'Size: Large fans have better efficiencies': 'Size: Large fans have better efficiencies',
    'Operating point: Optimal near BEP (Best Efficiency Point)': 'Operating point: Optimal near BEP (Best Efficiency Point)',
    'Wear: Efficiency decreases with fouling': 'Wear: Efficiency decreases with fouling',
    'Variable speed: Improves efficiency at partial load': 'Variable speed: Improves efficiency at partial load',
    'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.': 'An overall efficiency of 65% is a good reference value for a well-sized ID FAN.',
  },
};