export const translations = {
  fr: {
    // Header & titres
    'GF Configuration': 'Configuration — Four à Grille',
    'Caractéristiques de Fonctionnement': 'Caractéristiques de Fonctionnement',

    // Onglets
    'Gaz de combustion': 'Gaz de combustion',
    'Émissions polluantes': 'Émissions polluantes',
    'OPEX': 'OPEX',
    'Rapport': 'Rapport',

    // Boutons
    'Effacer': 'Effacer',
    'Envoyer données': 'Envoyer données',
    'Retour au flow': 'Retour au flow',
    'Aller à l\'onglet': 'Aller à l\'onglet',

    // Onglet combustion
    'Paramètres de combustion': 'Paramètres de combustion',
    'Bilan énergétique': 'Bilan énergétique',
    'Puissance incinerateur': 'Puissance incinérateur',
    'PCI déchet': 'PCI déchet',
    'Energie recuperee': 'Énergie récupérée (chaudière)',
    'Rendement WHB': 'Rendement WHB',
    'Données air combustion': 'Données air combustion',
    'T air': 'T air',
    'Enthalpie air': 'Enthalpie air',
    'Pertes thermiques': 'Pertes thermiques',
    'Résultats bruts': 'Résultats bruts',

    // Onglet polluants (repris de FB)
    'calculationParameters': 'Paramètres de calcul',
    'calculatedParameters': 'Paramètres calculés',
    'flueGasComposition': 'Composition des fumées',
    'inputFlueGas': 'Fumées d\'entrée',
    'outputFlueGas': 'Fumées de sortie',
    'bottomAshesCalculated': 'Cendres calculées',
    'wasteFlow': 'Débit déchets [kg/h]',
    'flueGasFlowWet': 'Débit fumées humides [Nm³/h]',
    'flueGasFlowDry': 'Débit fumées sèches [Nm³/h]',
    'o2Calculated': 'O₂ calculé [%]',
    'bottomAsh': 'Cendres lourdes sèches [kg/h]',
    'bottomAshWet': 'Cendres lourdes humides [kg/h]',
    'flyAsh': 'Cendres volantes [kg/h]',
    'sncr': 'SNCR',
    'sncrtEnabled': 'Activation SNCR',
    'noxLimit': 'Limite NOx [mg/Nm³]',
    'stoichiometry': 'Stœchiométrie',
    'nh3Consumption': 'Consommation NH₃ [kg/h]',
    'mercuryTreatment': 'Traitement du mercure',
    'hgTreatmentEnabled': 'Traitement Hg activé',
    'brHgRatio': 'Ratio Br/Hg',
    'hgMass': 'Masse Hg [kg/h]',
    'bromideConsumption': 'Consommation bromure [kg/h]',
    'pollutantTreatmentTable': 'Tableau de traitement des polluants',
    'pollutant': 'Polluant',
    'reactif': 'Réactif',
    'massInput': 'Masse entrée [kg/h]',
    'efficiency': 'Efficacité [%]',
    'stoechCoeff': 'Coeff. stoech.',
    'massOutput': 'Masse sortie [kg/h]',
    'massResidue': 'Résidu [kg/h]',
    'massReactif': 'Masse réactif [kg/h]',
    'massReduced': 'Masse réduite [kg/h]',
    'resetDefaultValues': 'Réinitialiser',

    // Rapport
    'GF — Rapport de synthèse': 'GF — Rapport de synthèse',
    '1. Bilan énergétique': '1. Bilan énergétique',
    '2. Gaz de combustion': '2. Gaz de combustion',
    '3. Émissions polluantes': '3. Émissions polluantes',
    '4. OPEX': '4. OPEX',
    'Température de sortie': 'Température de sortie',
    'O₂ mesuré (sec)': 'O₂ mesuré (sec)',
    'Débit humide total [kg/h]': 'Débit humide total [kg/h]',
    'Débit sec [Nm³/h]': 'Débit sec [Nm³/h]',
    'Débit humide [Nm³/h]': 'Débit humide [Nm³/h]',
    'Composition gaz de sortie': 'Composition gaz de sortie',
    'Gaz en entrée [kg/h]': 'Gaz en entrée [kg/h]',
    'Gaz en sortie [kg/h]': 'Gaz en sortie [kg/h]',
    'Résidus calculés': 'Résidus calculés',
    'Cendres lourdes sèches [kg/h]': 'Cendres lourdes sèches [kg/h]',
    'Cendres lourdes humides [kg/h]': 'Cendres lourdes humides [kg/h]',
    'Cendres volantes [kg/h]': 'Cendres volantes [kg/h]',
    'OPEX — Coûts horaires': 'OPEX — Coûts horaires',
    'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.': 'Coûts OPEX non disponibles — ouvrir l\'onglet Opex.',
    'Électricité': 'Électricité',
    'Eau': 'Eau',
    'Réactifs': 'Réactifs',
    'Énergie': 'Énergie',
    'Total coût': 'Total coût',
    'Coût horaire': 'Coût horaire',
    'Coût annuel': 'Coût annuel',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ électricité',
    'CO₂ énergie': 'CO₂ énergie',
    'CO₂ transport': 'CO₂ transport',
    'Total CO₂': 'Total CO₂',
    'Consommateur': 'Consommateur',
    'Total': 'Total',
    'Eau potable [m³/h]': 'Eau potable [m³/h]',
    'Eau de refroidissement [m³/h]': 'Eau de refroidissement [m³/h]',
    'Eau déminéralisée [m³/h]': 'Eau déminéralisée [m³/h]',
    'Consommations électriques': 'Consommations électriques',
    'Consommation d\'eau': 'Consommation d\'eau',
    'Énergie auxiliaire': 'Énergie auxiliaire',
    'Gaz haute valeur [MW]': 'Gaz haute valeur [MW]',
    'Fuel [MW]': 'Fuel [MW]',
    'Rapport généré automatiquement': 'Rapport généré automatiquement',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Données non disponibles (ouvrir l\'onglet Opex)',
  },

  en: {
    'GF Configuration': 'Configuration — Grate Furnace',
    'Caractéristiques de Fonctionnement': 'Operating Characteristics',
    'Gaz de combustion': 'Flue Gas',
    'Émissions polluantes': 'Pollutant Emissions',
    'OPEX': 'OPEX',
    'Rapport': 'Report',
    'Effacer': 'Clear',
    'Envoyer données': 'Send Data',
    'Retour au flow': 'Back to Flow',
    'Aller à l\'onglet': 'Go to tab',
    'Paramètres de combustion': 'Combustion Parameters',
    'Bilan énergétique': 'Energy Balance',
    'Puissance incinerateur': 'Incinerator Power',
    'PCI déchet': 'Waste LCV',
    'Energie recuperee': 'Recovered Energy (boiler)',
    'Rendement WHB': 'WHB Yield',
    'Données air combustion': 'Combustion Air Data',
    'T air': 'Air temperature',
    'Enthalpie air': 'Air enthalpy',
    'Pertes thermiques': 'Thermal losses',
    'Résultats bruts': 'Raw results',
    'calculationParameters': 'Calculation Parameters',
    'calculatedParameters': 'Calculated Parameters',
    'flueGasComposition': 'Flue Gas Composition',
    'inputFlueGas': 'Inlet Flue Gas',
    'outputFlueGas': 'Outlet Flue Gas',
    'bottomAshesCalculated': 'Calculated Ashes',
    'wasteFlow': 'Waste flow [kg/h]',
    'flueGasFlowWet': 'Wet flue gas flow [Nm³/h]',
    'flueGasFlowDry': 'Dry flue gas flow [Nm³/h]',
    'o2Calculated': 'Calculated O₂ [%]',
    'bottomAsh': 'Dry bottom ash [kg/h]',
    'bottomAshWet': 'Wet bottom ash [kg/h]',
    'flyAsh': 'Fly ash [kg/h]',
    'sncr': 'SNCR',
    'sncrtEnabled': 'Enable SNCR',
    'noxLimit': 'NOx limit [mg/Nm³]',
    'stoichiometry': 'Stoichiometry',
    'nh3Consumption': 'NH₃ consumption [kg/h]',
    'mercuryTreatment': 'Mercury treatment',
    'hgTreatmentEnabled': 'Hg treatment enabled',
    'brHgRatio': 'Br/Hg ratio',
    'hgMass': 'Hg mass [kg/h]',
    'bromideConsumption': 'Bromide consumption [kg/h]',
    'pollutantTreatmentTable': 'Pollutant treatment table',
    'pollutant': 'Pollutant',
    'reactif': 'Reagent',
    'massInput': 'Inlet mass [kg/h]',
    'efficiency': 'Efficiency [%]',
    'stoechCoeff': 'Stoech. coeff.',
    'massOutput': 'Outlet mass [kg/h]',
    'massResidue': 'Residue [kg/h]',
    'massReactif': 'Reagent mass [kg/h]',
    'massReduced': 'Reduced mass [kg/h]',
    'resetDefaultValues': 'Reset to defaults',
    'GF — Rapport de synthèse': 'GF — Summary Report',
    '1. Bilan énergétique': '1. Energy Balance',
    '2. Gaz de combustion': '2. Flue Gas',
    '3. Émissions polluantes': '3. Pollutant Emissions',
    '4. OPEX': '4. OPEX',
    'Température de sortie': 'Outlet temperature',
    'O₂ mesuré (sec)': 'Measured O₂ (dry)',
    'Débit humide total [kg/h]': 'Total wet flow [kg/h]',
    'Débit sec [Nm³/h]': 'Dry flow [Nm³/h]',
    'Débit humide [Nm³/h]': 'Wet flow [Nm³/h]',
    'Composition gaz de sortie': 'Outlet gas composition',
    'Gaz en entrée [kg/h]': 'Inlet gas [kg/h]',
    'Gaz en sortie [kg/h]': 'Outlet gas [kg/h]',
    'Résidus calculés': 'Calculated residues',
    'Cendres lourdes sèches [kg/h]': 'Dry bottom ash [kg/h]',
    'Cendres lourdes humides [kg/h]': 'Wet bottom ash [kg/h]',
    'Cendres volantes [kg/h]': 'Fly ash [kg/h]',
    'OPEX — Coûts horaires': 'OPEX — Hourly Costs',
    'Coûts OPEX non disponibles — ouvrir les onglets Design et Opex.': 'OPEX costs not available — open the Opex tab.',
    'Électricité': 'Electricity',
    'Eau': 'Water',
    'Réactifs': 'Reagents',
    'Énergie': 'Energy',
    'Total coût': 'Total cost',
    'Coût horaire': 'Hourly cost',
    'Coût annuel': 'Annual cost',
    'Total CO₂ [kg/h]': 'Total CO₂ [kg/h]',
    'CO₂ électricité': 'CO₂ electricity',
    'CO₂ énergie': 'CO₂ energy',
    'CO₂ transport': 'CO₂ transport',
    'Total CO₂': 'Total CO₂',
    'Consommateur': 'Consumer',
    'Total': 'Total',
    'Eau potable [m³/h]': 'Drinking water [m³/h]',
    'Eau de refroidissement [m³/h]': 'Cooling water [m³/h]',
    'Eau déminéralisée [m³/h]': 'Demineralised water [m³/h]',
    'Consommations électriques': 'Electrical consumptions',
    'Consommation d\'eau': 'Water consumption',
    'Énergie auxiliaire': 'Auxiliary energy',
    'Gaz haute valeur [MW]': 'High-value gas [MW]',
    'Fuel [MW]': 'Fuel [MW]',
    'Rapport généré automatiquement': 'Report automatically generated',
    'Données non disponibles (ouvrir l\'onglet Design)': 'Data not available (open Opex tab)',
  },
};
