export const translations = {
  fr: {
    // ===== FICHIER 1 : HCl Quench System =====
    // Header
    calculator: 'Calculateur Système Quench HCl',
    activeCalculation: 'Calcul automatique actif',
    realtimeUpdate: 'Mise à jour en temps réel',
    convergence: 'Convergence',
    boucle1: 'Boucle 1',
    boucle2: 'Boucle 2',

    // Errors & Warnings
    errorTitle: 'Erreur',
    warningTitle: 'Avertissement',
    successTitle: 'Calcul automatique actif',
    totalMassFlowZero: 'Le débit massique total ne peut pas être zéro',
    invalidTempPressure: 'Température et pression doivent être positives',
    invalidEfficiency: 'L\'efficacité doit être entre 0 et 1',
    calculationError: 'Erreur de calcul',
    speedWarning: 'Vitesse colonne {speed} m/s hors spécifications (10-15 m/s)',
    coneSpeedWarning: 'Vitesse cône {speed} m/s hors spécifications (30-40 m/s)',
    liquidFlowWarning: 'Débit liquide arrosage {flow} kg/h dépasse le maximum {max} kg/h',

    // Input Sections
    fuelInlet: 'Fumées d\'Entrée',
    designParameters: 'Paramètres de Conception',
    hclConcentrations: 'Concentrations HCl',
    resultsTitle: 'Résultats de Calcul',

    // Input Fields - Fuel
    temperature: 'Température (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Pression (mmHg)',
    upstreamPressure: 'Pression amont (mmH2O)',

    // Input Fields - Design
    venturiEfficiency: 'Efficacité venturi',
    waterSupplyTemp: 'Temp. eau appoint (°C)',
    quenchDiameter: 'Diamètre Quench (m)',
    coneDiameter: 'Diamètre cône (mm)',
    maxLiquidFlow: 'Qm Liq Ar Max (kg/h)',

    // Input Fields - Concentrations
    hclRecirculation: 'Conc. HCl recirculation (%)',
    hclSpray: 'Conc. HCl arrosage (%)',

    // Results - Purification Performance
    purificationPerformance: 'Performances Épuratoires',
    exitTemp: 'Temp. sortie fumées',
    saturationTemp: 'Temp. saturation',
    hclEfficiency: 'Efficacité HCl',
    hclExit: 'HCl sortie',
    hclDry: 'HCl sec 11% O₂',
    so2Dry: 'SO₂ sec 11% O₂',

    // Results - Hydraulic Performance
    hydraulicPerformance: 'Performances Hydrauliques',
    columnSpeed: 'Vitesse colonne',
    coneSpeed: 'Vitesse cône',
    saturationHeight: 'Hauteur saturation',
    purifiedDensity: 'Masse vol. épurée',

    // Results - Water Balance & pH
    waterBalance: 'Bilans Eau et pH',
    evaporation: 'Évaporation',
    waterSupply: 'Eau d\'appoint',
    purge: 'Purge',
    sprayLiquid: 'Liquide arrosage',
    sprayPh: 'pH arrosage',
    recircPh: 'pH recirculation',
    hclSprayConc: 'Conc. HCl arrosage',
    hclRecircConc: 'Conc. HCl recirc.',

    // Units
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    // Section headers
    'Données des Fumées': 'Données des Fumées',
    'Solution de Lavage': 'Solution de Lavage',
    'Résultats des Calculs': 'Résultats des Calculs',
    'Bilans Matière': 'Bilans Matière',
    'Dimensionnement Colonne': 'Dimensionnement Colonne',
    'Débits de Solution': 'Débits de Solution',
    'Paramètres de Transfert': 'Paramètres de Transfert',
    'Résultats': 'Résultats',

    // Input labels - Fumées
    'Débit volumique fumées (Nm³/h)': 'Débit volumique fumées (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'Concentration SO2 entrée (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'Concentration SO2 sortie souhaitée (mg/Nm³)',
    'Température fumées (°C)': 'Température fumées (°C)',
    'Teneur O2 fumées (%)': 'Teneur O2 fumées (%)',
    'Pression fumées (mbar)': 'Pression fumées (mbar)',

    // Input labels - Solution de lavage
    'Type de réactif': 'Type de réactif',
    'Concentration solution (% massique)': 'Concentration solution (% massique)',
    'pH solution souhaité': 'pH solution souhaité',
    'Température solution (°C)': 'Température solution (°C)',
    'Rapport L/G (L/m³)': 'Rapport L/G (L/m³)',

    // Input labels - Paramètres de conception
    'Vitesse gaz colonne (m/s)': 'Vitesse gaz colonne (m/s)',
    'Hauteur garnissage (m)': 'Hauteur garnissage (m)',
    'Type de garnissage': 'Type de garnissage',

    // Réactifs
    'NaOH (Soude caustique)': 'NaOH (Soude caustique)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Carbonate de sodium)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Bicarbonate de sodium)',

    // Garnissages
    'Anneaux de Pall': 'Anneaux de Pall',
    'Anneaux de Raschig': 'Anneaux de Raschig',
    'Selles de Berl': 'Selles de Berl',
    'Garnissage structuré': 'Garnissage structuré',

    // Results labels
    'Charge SO2 éliminée': 'Charge SO2 éliminée',
    'Consommation réactif': 'Consommation réactif',
    'avec 20% d\'excès': 'avec 20% d\'excès',
    'Efficacité d\'épuration': 'Efficacité d\'épuration',
    'Diamètre colonne': 'Diamètre colonne',
    'Surface section colonne': 'Surface section colonne',
    'Volume garnissage': 'Volume garnissage',
    'Débit solution lavage': 'Débit solution lavage',
    'Solution': 'Solution',
    'Débit de purge estimé': 'Débit de purge estimé',
    'Coefficient KLa SO2': 'Coefficient KLa SO2',
    'valeur estimée': 'valeur estimée',
    'Nombre d\'unités de transfert': 'Nombre d\'unités de transfert',
    'Surface d\'échange': 'Surface d\'échange',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Fumées d\'Entrée',
    'Concentrations HCl': 'Concentrations HCl',
    'Performances Épuratoires': 'Performances Épuratoires',
    'Performances Hydrauliques': 'Performances Hydrauliques',
    'Bilans Eau et pH': 'Bilans Eau et pH',
    'Résumé des Paramètres': 'Résumé des Paramètres',

    // Input labels from File 3
    'Température (°C)': 'Température (°C)',
    'CO₂ (kg/h)': 'CO₂ (kg/h)',
    'H₂O (kg/h)': 'H₂O (kg/h)',
    'O₂ (kg/h)': 'O₂ (kg/h)',
    'N₂ (kg/h)': 'N₂ (kg/h)',
    'SO₂ (kg/h)': 'SO₂ (kg/h)',
    'HCl (kg/h)': 'HCl (kg/h)',
    'Pression (mmHg)': 'Pression (mmHg)',
    'Pression amont (mmH2O)': 'Pression amont (mmH2O)',
    'Efficacité venturi': 'Efficacité venturi',
    'Temp. eau appoint (°C)': 'Temp. eau appoint (°C)',
    'Diamètre Quench (m)': 'Diamètre Quench (m)',
    'Diamètre cône (mm)': 'Diamètre cône (mm)',
    'Qm Liq Ar Max (kg/h)': 'Qm Liq Ar Max (kg/h)',
    'Conc. HCl recirculation (%)': 'Conc. HCl recirculation (%)',
    'Conc. HCl arrosage (%)': 'Conc. HCl arrosage (%)',

    // Output labels from File 3
    'Temp. sortie fumées': 'Temp. sortie fumées',
    'Temp. saturation': 'Temp. saturation',
    'Efficacité HCl': 'Efficacité HCl',
    'HCl sortie': 'HCl sortie',
    'HCl sec 11% O₂': 'HCl sec 11% O₂',
    'SO₂ sec 11% O₂': 'SO₂ sec 11% O₂',
    'Vitesse colonne': 'Vitesse colonne',
    'Vitesse cône': 'Vitesse cône',
    'Hauteur saturation': 'Hauteur saturation',
    'Masse vol. épurée': 'Masse vol. épurée',
    'Évaporation': 'Évaporation',
    'Eau d\'appoint': 'Eau d\'appoint',
    'Purge': 'Purge',
    'Liquide arrosage': 'Liquide arrosage',
    'pH arrosage': 'pH arrosage',
    'pH recirculation': 'pH recirculation',
    'Conc. HCl arrosage': 'Conc. HCl arrosage',
    'Conc. HCl recirc.': 'Conc. HCl recirc.',
  },

  en: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'HCl Quench System Calculator',
    activeCalculation: 'Automatic calculation active',
    realtimeUpdate: 'Real-time update',
    convergence: 'Convergence',
    boucle1: 'Loop 1',
    boucle2: 'Loop 2',
    errorTitle: 'Error',
    warningTitle: 'Warning',
    successTitle: 'Automatic calculation active',
    totalMassFlowZero: 'Total mass flow cannot be zero',
    invalidTempPressure: 'Temperature and pressure must be positive',
    invalidEfficiency: 'Efficiency must be between 0 and 1',
    calculationError: 'Calculation error',
    speedWarning: 'Column speed {speed} m/s out of specifications (10-15 m/s)',
    coneSpeedWarning: 'Cone speed {speed} m/s out of specifications (30-40 m/s)',
    liquidFlowWarning: 'Spray liquid flow {flow} kg/h exceeds maximum {max} kg/h',
    fuelInlet: 'Inlet Gases',
    designParameters: 'Design Parameters',
    hclConcentrations: 'HCl Concentrations',
    resultsTitle: 'Calculation Results',
    temperature: 'Temperature (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Pressure (mmHg)',
    upstreamPressure: 'Upstream Pressure (mmH2O)',
    venturiEfficiency: 'Venturi efficiency',
    waterSupplyTemp: 'Supply water temp. (°C)',
    quenchDiameter: 'Quench Diameter (m)',
    coneDiameter: 'Cone Diameter (mm)',
    maxLiquidFlow: 'Max Spray Flow (kg/h)',
    hclRecirculation: 'HCl recirculation conc. (%)',
    hclSpray: 'HCl spray conc. (%)',
    purificationPerformance: 'Purification Performance',
    exitTemp: 'Gas exit temperature',
    saturationTemp: 'Saturation temperature',
    hclEfficiency: 'HCl efficiency',
    hclExit: 'HCl exit',
    hclDry: 'HCl dry 11% O₂',
    so2Dry: 'SO₂ dry 11% O₂',
    hydraulicPerformance: 'Hydraulic Performance',
    columnSpeed: 'Column speed',
    coneSpeed: 'Cone speed',
    saturationHeight: 'Saturation height',
    purifiedDensity: 'Purified density',
    waterBalance: 'Water Balance & pH',
    evaporation: 'Evaporation',
    waterSupply: 'Water supply',
    purge: 'Purge',
    sprayLiquid: 'Spray liquid',
    sprayPh: 'Spray pH',
    recircPh: 'Recirculation pH',
    hclSprayConc: 'HCl spray conc.',
    hclRecircConc: 'HCl recirc. conc.',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'Fume Data',
    'Solution de Lavage': 'Washing Solution',
    'Paramètres de Conception': 'Design Parameters',
    'Résultats des Calculs': 'Calculation Results',
    'Bilans Matière': 'Material Balances',
    'Dimensionnement Colonne': 'Column Sizing',
    'Débits de Solution': 'Solution Flow Rates',
    'Paramètres de Transfert': 'Transfer Parameters',
    'Résultats': 'Results',
    'Débit volumique fumées (Nm³/h)': 'Fume volume flow (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'SO2 inlet concentration (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'Desired SO2 outlet (mg/Nm³)',
    'Température fumées (°C)': 'Fume temperature (°C)',
    'Teneur O2 fumées (%)': 'Fume O2 content (%)',
    'Pression fumées (mbar)': 'Fume pressure (mbar)',
    'Type de réactif': 'Reagent type',
    'Concentration solution (% massique)': 'Solution concentration (% w/w)',
    'pH solution souhaité': 'Desired solution pH',
    'Température solution (°C)': 'Solution temperature (°C)',
    'Rapport L/G (L/m³)': 'L/G ratio (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Column gas velocity (m/s)',
    'Hauteur garnissage (m)': 'Packing height (m)',
    'Type de garnissage': 'Packing type',
    'NaOH (Soude caustique)': 'NaOH (Caustic soda)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Sodium carbonate)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Sodium bicarbonate)',
    'Anneaux de Pall': 'Pall rings',
    'Anneaux de Raschig': 'Raschig rings',
    'Selles de Berl': 'Berl saddles',
    'Garnissage structuré': 'Structured packing',
    'Charge SO2 éliminée': 'SO2 load removed',
    'Consommation réactif': 'Reagent consumption',
    'avec 20% d\'excès': 'with 20% excess',
    'Efficacité d\'épuration': 'Purification efficiency',
    'Diamètre colonne': 'Column diameter',
    'Surface section colonne': 'Column cross-section',
    'Volume garnissage': 'Packing volume',
    'Débit solution lavage': 'Washing solution flow',
    'Solution': 'Solution',
    'Débit de purge estimé': 'Estimated purge flow',
    'Coefficient KLa SO2': 'SO2 KLa coefficient',
    'valeur estimée': 'estimated value',
    'Nombre d\'unités de transfert': 'Number of transfer units',
    'Surface d\'échange': 'Exchange surface',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Inlet Fumes',
    'Concentrations HCl': 'HCl Concentrations',
    'Performances Épuratoires': 'Purification Performance',
    'Performances Hydrauliques': 'Hydraulic Performance',
    'Bilans Eau et pH': 'Water Balance and pH',
    'Résumé des Paramètres': 'Parameter Summary',
  },

  de: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'HCl-Quench-Systemrechner',
    activeCalculation: 'Automatische Berechnung aktiv',
    realtimeUpdate: 'Echtzeit-Update',
    convergence: 'Konvergenz',
    boucle1: 'Schleife 1',
    boucle2: 'Schleife 2',
    errorTitle: 'Fehler',
    warningTitle: 'Warnung',
    successTitle: 'Automatische Berechnung aktiv',
    totalMassFlowZero: 'Der Gesamtmassenstrom darf nicht Null sein',
    invalidTempPressure: 'Temperatur und Druck müssen positiv sein',
    invalidEfficiency: 'Effizienz muss zwischen 0 und 1 liegen',
    calculationError: 'Berechnungsfehler',
    speedWarning: 'Säulengeschwindigkeit {speed} m/s außerhalb Spezifikation (10-15 m/s)',
    coneSpeedWarning: 'Kegelgeschwindigkeit {speed} m/s außerhalb Spezifikation (30-40 m/s)',
    liquidFlowWarning: 'Sprühflüssigkeitsstrom {flow} kg/h überschreitet Maximum {max} kg/h',
    fuelInlet: 'Einlassgase',
    designParameters: 'Konstruktionsparameter',
    hclConcentrations: 'HCl-Konzentrationen',
    resultsTitle: 'Berechnungsergebnisse',
    temperature: 'Temperatur (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Druck (mmHg)',
    upstreamPressure: 'Eingangsdruck (mmH2O)',
    venturiEfficiency: 'Venturi-Effizienz',
    waterSupplyTemp: 'Versorgungswassertemp. (°C)',
    quenchDiameter: 'Quench-Durchmesser (m)',
    coneDiameter: 'Kegeldurchmesser (mm)',
    maxLiquidFlow: 'Max. Sprühfluss (kg/h)',
    hclRecirculation: 'HCl-Umwälzkonz. (%)',
    hclSpray: 'HCl-Sprühkonz. (%)',
    purificationPerformance: 'Reinigungsleistung',
    exitTemp: 'Gasaustrittstemperatur',
    saturationTemp: 'Sättigungstemperatur',
    hclEfficiency: 'HCl-Effizienz',
    hclExit: 'HCl-Austritt',
    hclDry: 'HCl trocken 11% O₂',
    so2Dry: 'SO₂ trocken 11% O₂',
    hydraulicPerformance: 'Hydraulische Leistung',
    columnSpeed: 'Säulengeschwindigkeit',
    coneSpeed: 'Kegelgeschwindigkeit',
    saturationHeight: 'Sättigungshöhe',
    purifiedDensity: 'Gereinigte Dichte',
    waterBalance: 'Wasserbilanz und pH',
    evaporation: 'Verdampfung',
    waterSupply: 'Wasserzufuhr',
    purge: 'Spülung',
    sprayLiquid: 'Sprühflüssigkeit',
    sprayPh: 'Sprüh-pH',
    recircPh: 'Umwälz-pH',
    hclSprayConc: 'HCl-Sprühkonz.',
    hclRecircConc: 'HCl-Umwälzkonz.',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'Abgasdaten',
    'Solution de Lavage': 'Waschlösung',
    'Paramètres de Conception': 'Konstruktionsparameter',
    'Résultats des Calculs': 'Berechnungsergebnisse',
    'Bilans Matière': 'Stoffbilanz',
    'Dimensionnement Colonne': 'Kolonnendimensionierung',
    'Débits de Solution': 'Lösungsdurchsätze',
    'Paramètres de Transfert': 'Transferparameter',
    'Résultats': 'Ergebnisse',
    'Débit volumique fumées (Nm³/h)': 'Abgasvolumenstrom (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'SO2-Eingangskonzentration (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'Gewünschter SO2-Ausgang (mg/Nm³)',
    'Température fumées (°C)': 'Abgastemperatur (°C)',
    'Teneur O2 fumées (%)': 'Abgas-O2-Gehalt (%)',
    'Pression fumées (mbar)': 'Abgasdruck (mbar)',
    'Type de réactif': 'Reaktivtyp',
    'Concentration solution (% massique)': 'Lösungskonzentration (% m/m)',
    'pH solution souhaité': 'Gewünschter Lösungs-pH',
    'Température solution (°C)': 'Lösungstemperatur (°C)',
    'Rapport L/G (L/m³)': 'L/G-Verhältnis (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Kolonen-Gasgeschwindigkeit (m/s)',
    'Hauteur garnissage (m)': 'Füllkörperhöhe (m)',
    'Type de garnissage': 'Füllkörpertyp',
    'NaOH (Soude caustique)': 'NaOH (Kaustische Soda)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Natriumcarbonat)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Natriumbicarbonat)',
    'Anneaux de Pall': 'Pall-Ringe',
    'Anneaux de Raschig': 'Raschig-Ringe',
    'Selles de Berl': 'Berl-Sättel',
    'Garnissage structuré': 'Strukturiertes Füllmaterial',
    'Charge SO2 éliminée': 'Entfernte SO2-Last',
    'Consommation réactif': 'Reaktivverbrauch',
    'avec 20% d\'excès': 'mit 20% Überschuss',
    'Efficacité d\'épuration': 'Reinigungseffizienz',
    'Diamètre colonne': 'Kolonnendurchmesser',
    'Surface section colonne': 'Kolonnenquerschnittsfläche',
    'Volume garnissage': 'Füllkörpervolumen',
    'Débit solution lavage': 'Waschlösungsdurchsatz',
    'Solution': 'Lösung',
    'Débit de purge estimé': 'Geschätzter Spüldurchsatz',
    'Coefficient KLa SO2': 'SO2-KLa-Koeffizient',
    'valeur estimée': 'geschätzter Wert',
    'Nombre d\'unités de transfert': 'Anzahl der Transfereinheiten',
    'Surface d\'échange': 'Austauschfläche',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Einlassgase',
    'Concentrations HCl': 'HCl-Konzentrationen',
    'Performances Épuratoires': 'Reinigungsleistung',
    'Performances Hydrauliques': 'Hydraulische Leistung',
    'Bilans Eau et pH': 'Wasserbilanz und pH',
    'Résumé des Paramètres': 'Parameterzusammenfassung',
  },

  es: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'Calculadora del Sistema Quench HCl',
    activeCalculation: 'Cálculo automático activo',
    realtimeUpdate: 'Actualización en tiempo real',
    convergence: 'Convergencia',
    boucle1: 'Bucle 1',
    boucle2: 'Bucle 2',
    errorTitle: 'Error',
    warningTitle: 'Advertencia',
    successTitle: 'Cálculo automático activo',
    totalMassFlowZero: 'El flujo másico total no puede ser cero',
    invalidTempPressure: 'La temperatura y presión deben ser positivas',
    invalidEfficiency: 'La eficiencia debe estar entre 0 y 1',
    calculationError: 'Error de cálculo',
    speedWarning: 'Velocidad de columna {speed} m/s fuera de especificaciones (10-15 m/s)',
    coneSpeedWarning: 'Velocidad de cono {speed} m/s fuera de especificaciones (30-40 m/s)',
    liquidFlowWarning: 'Flujo de líquido de pulverización {flow} kg/h excede el máximo {max} kg/h',
    fuelInlet: 'Gases de Entrada',
    designParameters: 'Parámetros de Diseño',
    hclConcentrations: 'Concentraciones de HCl',
    resultsTitle: 'Resultados del Cálculo',
    temperature: 'Temperatura (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Presión (mmHg)',
    upstreamPressure: 'Presión aguas arriba (mmH2O)',
    venturiEfficiency: 'Eficiencia venturi',
    waterSupplyTemp: 'Temp. agua de aporte (°C)',
    quenchDiameter: 'Diámetro Quench (m)',
    coneDiameter: 'Diámetro cono (mm)',
    maxLiquidFlow: 'Flujo máximo de líquido (kg/h)',
    hclRecirculation: 'Conc. HCl recirculación (%)',
    hclSpray: 'Conc. HCl pulverización (%)',
    purificationPerformance: 'Rendimiento de Purificación',
    exitTemp: 'Temp. salida gases',
    saturationTemp: 'Temp. saturación',
    hclEfficiency: 'Eficiencia HCl',
    hclExit: 'Salida HCl',
    hclDry: 'HCl seco 11% O₂',
    so2Dry: 'SO₂ seco 11% O₂',
    hydraulicPerformance: 'Rendimiento Hidráulico',
    columnSpeed: 'Velocidad de columna',
    coneSpeed: 'Velocidad de cono',
    saturationHeight: 'Altura de saturación',
    purifiedDensity: 'Densidad purificada',
    waterBalance: 'Balance de Agua y pH',
    evaporation: 'Evaporación',
    waterSupply: 'Suministro de agua',
    purge: 'Purga',
    sprayLiquid: 'Líquido de pulverización',
    sprayPh: 'pH de pulverización',
    recircPh: 'pH de recirculación',
    hclSprayConc: 'Conc. HCl pulverización',
    hclRecircConc: 'Conc. HCl recirculación',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'Datos de Humos',
    'Solution de Lavage': 'Solución de Lavado',
    'Paramètres de Conception': 'Parámetros de Diseño',
    'Résultats des Calculs': 'Resultados de Cálculos',
    'Bilans Matière': 'Balance de Materia',
    'Dimensionnement Colonne': 'Dimensionamiento de Columna',
    'Débits de Solution': 'Caudales de Solución',
    'Paramètres de Transfert': 'Parámetros de Transferencia',
    'Résultats': 'Resultados',
    'Débit volumique fumées (Nm³/h)': 'Caudal volumétrico de humos (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'Concentración SO2 entrada (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'SO2 salida deseada (mg/Nm³)',
    'Température fumées (°C)': 'Temperatura de humos (°C)',
    'Teneur O2 fumées (%)': 'Contenido O2 en humos (%)',
    'Pression fumées (mbar)': 'Presión de humos (mbar)',
    'Type de réactif': 'Tipo de reactivo',
    'Concentration solution (% massique)': 'Concentración de solución (% m/m)',
    'pH solution souhaité': 'pH de solución deseado',
    'Température solution (°C)': 'Temperatura de solución (°C)',
    'Rapport L/G (L/m³)': 'Relación L/G (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Velocidad de gas en columna (m/s)',
    'Hauteur garnissage (m)': 'Altura de relleno (m)',
    'Type de garnissage': 'Tipo de relleno',
    'NaOH (Soude caustique)': 'NaOH (Sosa cáustica)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Carbonato de sodio)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Bicarbonato de sodio)',
    'Anneaux de Pall': 'Anillos Pall',
    'Anneaux de Raschig': 'Anillos Raschig',
    'Selles de Berl': 'Sillas Berl',
    'Garnissage structuré': 'Relleno estructurado',
    'Charge SO2 éliminée': 'Carga SO2 eliminada',
    'Consommation réactif': 'Consumo de reactivo',
    'avec 20% d\'excès': 'con 20% de exceso',
    'Efficacité d\'épuration': 'Eficiencia de purificación',
    'Diamètre colonne': 'Diámetro de columna',
    'Surface section colonne': 'Área de sección de columna',
    'Volume garnissage': 'Volumen de relleno',
    'Débit solution lavage': 'Caudal de solución de lavado',
    'Solution': 'Solución',
    'Débit de purge estimé': 'Caudal de purga estimado',
    'Coefficient KLa SO2': 'Coeficiente KLa SO2',
    'valeur estimée': 'valor estimado',
    'Nombre d\'unités de transfert': 'Número de unidades de transferencia',
    'Surface d\'échange': 'Superficie de intercambio',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Humos de Entrada',
    'Concentrations HCl': 'Concentraciones de HCl',
    'Performances Épuratoires': 'Desempeño de Purificación',
    'Performances Hydrauliques': 'Desempeño Hidráulico',
    'Bilans Eau et pH': 'Balance de Agua y pH',
    'Résumé des Paramètres': 'Resumen de Parámetros',
  },

  it: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'Calcolatore Sistema Quench HCl',
    activeCalculation: 'Calcolo automatico attivo',
    realtimeUpdate: 'Aggiornamento in tempo reale',
    convergence: 'Convergenza',
    boucle1: 'Ciclo 1',
    boucle2: 'Ciclo 2',
    errorTitle: 'Errore',
    warningTitle: 'Avvertenza',
    successTitle: 'Calcolo automatico attivo',
    totalMassFlowZero: 'La portata massica totale non può essere zero',
    invalidTempPressure: 'Temperatura e pressione devono essere positive',
    invalidEfficiency: 'L\'efficienza deve essere tra 0 e 1',
    calculationError: 'Errore di calcolo',
    speedWarning: 'Velocità colonna {speed} m/s fuori specifiche (10-15 m/s)',
    coneSpeedWarning: 'Velocità cono {speed} m/s fuori specifiche (30-40 m/s)',
    liquidFlowWarning: 'Portata liquido di spruzzo {flow} kg/h supera il massimo {max} kg/h',
    fuelInlet: 'Gas in Ingresso',
    designParameters: 'Parametri di Progettazione',
    hclConcentrations: 'Concentrazioni HCl',
    resultsTitle: 'Risultati del Calcolo',
    temperature: 'Temperatura (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Pressione (mmHg)',
    upstreamPressure: 'Pressione a monte (mmH2O)',
    venturiEfficiency: 'Efficienza venturi',
    waterSupplyTemp: 'Temp. acqua di apporto (°C)',
    quenchDiameter: 'Diametro Quench (m)',
    coneDiameter: 'Diametro cono (mm)',
    maxLiquidFlow: 'Max portata liquido (kg/h)',
    hclRecirculation: 'Conc. HCl ricircolo (%)',
    hclSpray: 'Conc. HCl spruzzo (%)',
    purificationPerformance: 'Prestazioni di Depurazione',
    exitTemp: 'Temp. uscita gas',
    saturationTemp: 'Temp. saturazione',
    hclEfficiency: 'Efficienza HCl',
    hclExit: 'Uscita HCl',
    hclDry: 'HCl secco 11% O₂',
    so2Dry: 'SO₂ secco 11% O₂',
    hydraulicPerformance: 'Prestazioni Idrauliche',
    columnSpeed: 'Velocità colonna',
    coneSpeed: 'Velocità cono',
    saturationHeight: 'Altezza saturazione',
    purifiedDensity: 'Densità depurata',
    waterBalance: 'Bilancio Acqua e pH',
    evaporation: 'Evaporazione',
    waterSupply: 'Apporto acqua',
    purge: 'Spurgo',
    sprayLiquid: 'Liquido di spruzzo',
    sprayPh: 'pH spruzzo',
    recircPh: 'pH ricircolo',
    hclSprayConc: 'Conc. HCl spruzzo',
    hclRecircConc: 'Conc. HCl ricircolo',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'Dati dei Fumi',
    'Solution de Lavage': 'Soluzione di Lavaggio',
    'Paramètres de Conception': 'Parametri di Progettazione',
    'Résultats des Calculs': 'Risultati dei Calcoli',
    'Bilans Matière': 'Bilanci Materiali',
    'Dimensionnement Colonne': 'Dimensionamento Colonna',
    'Débits de Solution': 'Portate di Soluzione',
    'Paramètres de Transfert': 'Parametri di Trasferimento',
    'Résultats': 'Risultati',
    'Débit volumique fumées (Nm³/h)': 'Portata volumetrica fumi (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'Concentrazione SO2 ingresso (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'SO2 uscita desiderata (mg/Nm³)',
    'Température fumées (°C)': 'Temperatura fumi (°C)',
    'Teneur O2 fumées (%)': 'Contenuto O2 fumi (%)',
    'Pression fumées (mbar)': 'Pressione fumi (mbar)',
    'Type de réactif': 'Tipo di reagente',
    'Concentration solution (% massique)': 'Concentrazione soluzione (% m/m)',
    'pH solution souhaité': 'pH soluzione desiderato',
    'Température solution (°C)': 'Temperatura soluzione (°C)',
    'Rapport L/G (L/m³)': 'Rapporto L/G (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Velocità gas colonna (m/s)',
    'Hauteur garnissage (m)': 'Altezza riempimento (m)',
    'Type de garnissage': 'Tipo di riempimento',
    'NaOH (Soude caustique)': 'NaOH (Soda caustica)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Carbonato di sodio)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Bicarbonato di sodio)',
    'Anneaux de Pall': 'Anelli Pall',
    'Anneaux de Raschig': 'Anelli Raschig',
    'Selles de Berl': 'Selle Berl',
    'Garnissage structuré': 'Riempimento strutturato',
    'Charge SO2 éliminée': 'Carico SO2 rimosso',
    'Consommation réactif': 'Consumo reagente',
    'avec 20% d\'excès': 'con 20% di eccesso',
    'Efficacité d\'épuration': 'Efficienza di depurazione',
    'Diamètre colonne': 'Diametro colonna',
    'Surface section colonne': 'Area sezione colonna',
    'Volume garnissage': 'Volume riempimento',
    'Débit solution lavage': 'Portata soluzione lavaggio',
    'Solution': 'Soluzione',
    'Débit de purge estimé': 'Portata spurgo stimata',
    'Coefficient KLa SO2': 'Coefficiente KLa SO2',
    'valeur estimée': 'valore stimato',
    'Nombre d\'unités de transfert': 'Numero unità di trasferimento',
    'Surface d\'échange': 'Superficie di scambio',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Fumi in Ingresso',
    'Concentrations HCl': 'Concentrazioni di HCl',
    'Performances Épuratoires': 'Prestazioni di Purificazione',
    'Performances Hydrauliques': 'Prestazioni Idrauliche',
    'Bilans Eau et pH': 'Bilancio Acqua e pH',
    'Résumé des Paramètres': 'Riepilogo dei Parametri',
  },

  pt: {
    // ===== FICHIER 1 : HCl Quench System (simplified - using only en translations as pt file had errors) =====
    calculator: 'Calculadora do Sistema Quench HCl',
    activeCalculation: 'Cálculo automático ativo',
    realtimeUpdate: 'Atualização em tempo real',
    convergence: 'Convergência',
    boucle1: 'Loop 1',
    boucle2: 'Loop 2',
    errorTitle: 'Erro',
    warningTitle: 'Aviso',
    successTitle: 'Cálculo automático ativo',
    totalMassFlowZero: 'O fluxo de massa total não pode ser zero',
    invalidTempPressure: 'Temperatura e pressão devem ser positivas',
    invalidEfficiency: 'A eficiência deve estar entre 0 e 1',
    calculationError: 'Erro de cálculo',
    speedWarning: 'Velocidade da coluna {speed} m/s fora das especificações (10-15 m/s)',
    coneSpeedWarning: 'Velocidade do cone {speed} m/s fora das especificações (30-40 m/s)',
    liquidFlowWarning: 'Fluxo de líquido de pulverização {flow} kg/h excede o máximo {max} kg/h',
    fuelInlet: 'Gases de Entrada',
    designParameters: 'Parâmetros de Design',
    hclConcentrations: 'Concentrações de HCl',
    resultsTitle: 'Resultados do Cálculo',
    temperature: 'Temperatura (°C)',
    co2: 'CO₂ (kg/h)',
    h2o: 'H₂O (kg/h)',
    o2: 'O₂ (kg/h)',
    n2: 'N₂ (kg/h)',
    so2: 'SO₂ (kg/h)',
    hcl: 'HCl (kg/h)',
    pressure: 'Pressão (mmHg)',
    upstreamPressure: 'Pressão a montante (mmH2O)',
    venturiEfficiency: 'Eficiência do venturi',
    waterSupplyTemp: 'Temp. água de suprimento (°C)',
    quenchDiameter: 'Diâmetro Quench (m)',
    coneDiameter: 'Diâmetro do cone (mm)',
    maxLiquidFlow: 'Fluxo máximo de líquido (kg/h)',
    hclRecirculation: 'Conc. HCl recirculação (%)',
    hclSpray: 'Conc. HCl pulverização (%)',
    purificationPerformance: 'Desempenho de Purificação',
    exitTemp: 'Temp. saída de gases',
    saturationTemp: 'Temp. saturação',
    hclEfficiency: 'Eficiência HCl',
    hclExit: 'Saída HCl',
    hclDry: 'HCl seco 11% O₂',
    so2Dry: 'SO₂ seco 11% O₂',
    hydraulicPerformance: 'Desempenho Hidráulico',
    columnSpeed: 'Velocidade da coluna',
    coneSpeed: 'Velocidade do cone',
    saturationHeight: 'Altura de saturação',
    purifiedDensity: 'Densidade purificada',
    waterBalance: 'Balanço de Água e pH',
    evaporation: 'Evaporação',
    waterSupply: 'Suprimento de água',
    purge: 'Descarga',
    sprayLiquid: 'Líquido de pulverização',
    sprayPh: 'pH de pulverização',
    recircPh: 'pH de recirculação',
    hclSprayConc: 'Conc. HCl pulverização',
    hclRecircConc: 'Conc. HCl recirculação',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Dados des Fumées': 'Dados dos Fumos',
    'Solution de Lavage': 'Solução de Lavagem',
    'Paramètres de Conception': 'Parâmetros de Design',
    'Résultats des Calculs': 'Resultados de Cálculos',
    'Bilans Matière': 'Balanços de Material',
    'Dimensionnement Colonne': 'Dimensionamento da Coluna',
    'Débits de Solution': 'Vazões de Solução',
    'Paramètres de Transfert': 'Parâmetros de Transferência',
    'Résultats': 'Resultados',
    'Débit volumique fumées (Nm³/h)': 'Vazão volumétrica de fumos (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'Concentração SO2 entrada (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'SO2 saída desejada (mg/Nm³)',
    'Température fumées (°C)': 'Temperatura dos fumos (°C)',
    'Teneur O2 fumées (%)': 'Teor O2 dos fumos (%)',
    'Pression fumées (mbar)': 'Pressão dos fumos (mbar)',
    'Type de réactif': 'Tipo de reagente',
    'Concentration solution (% massique)': 'Concentração de solução (% m/m)',
    'pH solution souhaité': 'pH da solução desejado',
    'Température solution (°C)': 'Temperatura da solução (°C)',
    'Rapport L/G (L/m³)': 'Relação L/G (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Velocidade do gás na coluna (m/s)',
    'Hauteur garnissage (m)': 'Altura do recheio (m)',
    'Type de garnissage': 'Tipo de recheio',
    'NaOH (Soude caustique)': 'NaOH (Soda cáustica)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Carbonato de sódio)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Bicarbonato de sódio)',
    'Anneaux de Pall': 'Anéis Pall',
    'Anneaux de Raschig': 'Anéis Raschig',
    'Selles de Berl': 'Selas Berl',
    'Garnissage structuré': 'Recheio estruturado',
    'Charge SO2 éliminée': 'Carga SO2 removida',
    'Consommation réactif': 'Consumo de reagente',
    'avec 20% d\'excès': 'com 20% de excesso',
    'Efficacité d\'épuration': 'Eficiência de purificação',
    'Diamètre colonne': 'Diâmetro da coluna',
    'Surface section colonne': 'Área da seção da coluna',
    'Volume garnissage': 'Volume do recheio',
    'Débit solution lavage': 'Vazão de solução de lavagem',
    'Solution': 'Solução',
    'Débit de purge estimé': 'Vazão de purga estimada',
    'Coefficient KLa SO2': 'Coeficiente KLa SO2',
    'valeur estimée': 'valor estimado',
    'Nombre d\'unités de transfert': 'Número de unidades de transferência',
    'Surface d\'échange': 'Superfície de troca',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Fumaça de Entrada',
    'Concentrations HCl': 'Concentrações de HCl',
    'Performances Épuratoires': 'Desempenho de Purificação',
    'Performances Hydrauliques': 'Desempenho Hidráulico',
    'Bilans Eau et pH': 'Balanço de Água e pH',
    'Résumé des Paramètres': 'Resumo de Parâmetros',
  },

  zh: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'HCl淬火系统计算器',
    activeCalculation: '自动计算活跃',
    realtimeUpdate: '实时更新',
    convergence: '收敛',
    boucle1: '循环1',
    boucle2: '循环2',
    errorTitle: '错误',
    warningTitle: '警告',
    successTitle: '自动计算活跃',
    totalMassFlowZero: '总质量流量不能为零',
    invalidTempPressure: '温度和压力必须为正值',
    invalidEfficiency: '效率必须在0到1之间',
    calculationError: '计算错误',
    speedWarning: '塔速度{speed} m/s超出规范(10-15 m/s)',
    coneSpeedWarning: '锥体速度{speed} m/s超出规范(30-40 m/s)',
    liquidFlowWarning: '喷液流量{flow} kg/h超过最大值{max} kg/h',
    fuelInlet: '进口气体',
    designParameters: '设计参数',
    hclConcentrations: 'HCl浓度',
    resultsTitle: '计算结果',
    temperature: '温度(°C)',
    co2: 'CO₂(kg/h)',
    h2o: 'H₂O(kg/h)',
    o2: 'O₂(kg/h)',
    n2: 'N₂(kg/h)',
    so2: 'SO₂(kg/h)',
    hcl: 'HCl(kg/h)',
    pressure: '压力(mmHg)',
    upstreamPressure: '上游压力(mmH2O)',
    venturiEfficiency: '文丘里效率',
    waterSupplyTemp: '补充水温(°C)',
    quenchDiameter: '淬火直径(m)',
    coneDiameter: '锥体直径(mm)',
    maxLiquidFlow: '最大喷液流(kg/h)',
    hclRecirculation: 'HCl再循环浓度(%)',
    hclSpray: 'HCl喷液浓度(%)',
    purificationPerformance: '净化性能',
    exitTemp: '气体出口温度',
    saturationTemp: '饱和温度',
    hclEfficiency: 'HCl效率',
    hclExit: 'HCl出口',
    hclDry: 'HCl干燥11% O₂',
    so2Dry: 'SO₂干燥11% O₂',
    hydraulicPerformance: '水力性能',
    columnSpeed: '塔速度',
    coneSpeed: '锥体速度',
    saturationHeight: '饱和高度',
    purifiedDensity: '净化密度',
    waterBalance: '水平衡和pH',
    evaporation: '蒸发',
    waterSupply: '供水',
    purge: '排泥',
    sprayLiquid: '喷液',
    sprayPh: '喷液pH',
    recircPh: '再循环pH',
    hclSprayConc: 'HCl喷液浓度',
    hclRecircConc: 'HCl再循环浓度',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': '烟气数据',
    'Solution de Lavage': '洗涤溶液',
    'Paramètres de Conception': '设计参数',
    'Résultats des Calculs': '计算结果',
    'Bilans Matière': '物料平衡',
    'Dimensionnement Colonne': '塔柱尺寸',
    'Débits de Solution': '溶液流量',
    'Paramètres de Transfert': '传质参数',
    'Résultats': '结果',
    'Débit volumique fumées (Nm³/h)': '烟气体积流量 (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'SO2入口浓度 (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': '所需SO2出口 (mg/Nm³)',
    'Température fumées (°C)': '烟气温度 (°C)',
    'Teneur O2 fumées (%)': '烟气O2含量 (%)',
    'Pression fumées (mbar)': '烟气压力 (mbar)',
    'Type de réactif': '反应物类型',
    'Concentration solution (% massique)': '溶液浓度 (% w/w)',
    'pH solution souhaité': '所需溶液pH',
    'Température solution (°C)': '溶液温度 (°C)',
    'Rapport L/G (L/m³)': 'L/G比率 (L/m³)',
    'Vitesse gaz colonne (m/s)': '塔气体速度 (m/s)',
    'Hauteur garnissage (m)': '填料高度 (m)',
    'Type de garnissage': '填料类型',
    'NaOH (Soude caustique)': 'NaOH (苛性钠)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (碳酸钠)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (碳酸氢钠)',
    'Anneaux de Pall': 'Pall环',
    'Anneaux de Raschig': 'Raschig环',
    'Selles de Berl': 'Berl鞍',
    'Garnissage structuré': '结构填料',
    'Charge SO2 éliminée': '去除SO2负荷',
    'Consommation réactif': '反应物消耗',
    'avec 20% d\'excès': '含20%过量',
    'Efficacité d\'épuration': '净化效率',
    'Diamètre colonne': '塔直径',
    'Surface section colonne': '塔截面积',
    'Volume garnissage': '填料体积',
    'Débit solution lavage': '洗涤溶液流量',
    'Solution': '溶液',
    'Débit de purge estimé': '估计的排污流量',
    'Coefficient KLa SO2': 'SO2 KLa系数',
    'valeur estimée': '估计值',
    'Nombre d\'unités de transfert': '传质单元数',
    'Surface d\'échange': '交换面积',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': '进气',
    'Concentrations HCl': 'HCl浓度',
    'Performances Épuratoires': '净化性能',
    'Performances Hydrauliques': '液压性能',
    'Bilans Eau et pH': '水平衡和pH',
    'Résumé des Paramètres': '参数摘要',
  },

  ja: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'HCl淬火システム計算機',
    activeCalculation: '自動計算アクティブ',
    realtimeUpdate: 'リアルタイム更新',
    convergence: '収束',
    boucle1: 'ループ1',
    boucle2: 'ループ2',
    errorTitle: 'エラー',
    warningTitle: '警告',
    successTitle: '自動計算アクティブ',
    totalMassFlowZero: '総質量流量がゼロにはなりません',
    invalidTempPressure: '温度と圧力は正である必要があります',
    invalidEfficiency: '効率は0から1の間である必要があります',
    calculationError: '計算エラー',
    speedWarning: 'カラム速度{speed} m/s仕様外(10-15 m/s)',
    coneSpeedWarning: 'コーン速度{speed} m/s仕様外(30-40 m/s)',
    liquidFlowWarning: 'スプレー液体流量{flow} kg/h最大値{max} kg/hを超えます',
    fuelInlet: '吸入ガス',
    designParameters: '設計パラメータ',
    hclConcentrations: 'HCl濃度',
    resultsTitle: '計算結果',
    temperature: '温度(°C)',
    co2: 'CO₂(kg/h)',
    h2o: 'H₂O(kg/h)',
    o2: 'O₂(kg/h)',
    n2: 'N₂(kg/h)',
    so2: 'SO₂(kg/h)',
    hcl: 'HCl(kg/h)',
    pressure: '圧力(mmHg)',
    upstreamPressure: '上流圧力(mmH2O)',
    venturiEfficiency: 'ベンチュリ効率',
    waterSupplyTemp: '給水温度(°C)',
    quenchDiameter: '淬火直径(m)',
    coneDiameter: 'コーン直径(mm)',
    maxLiquidFlow: '最大スプレー流量(kg/h)',
    hclRecirculation: 'HCl再循環濃度(%)',
    hclSpray: 'HClスプレー濃度(%)',
    purificationPerformance: '浄化性能',
    exitTemp: 'ガス出口温度',
    saturationTemp: '飽和温度',
    hclEfficiency: 'HCl効率',
    hclExit: 'HCl出口',
    hclDry: 'HCl乾燥11% O₂',
    so2Dry: 'SO₂乾燥11% O₂',
    hydraulicPerformance: '油圧性能',
    columnSpeed: 'カラム速度',
    coneSpeed: 'コーン速度',
    saturationHeight: '飽和高さ',
    purifiedDensity: '浄化密度',
    waterBalance: '水収支とpH',
    evaporation: '蒸発',
    waterSupply: '給水',
    purge: 'パージ',
    sprayLiquid: 'スプレー液',
    sprayPh: 'スプレーpH',
    recircPh: '再循環pH',
    hclSprayConc: 'HClスプレー濃度',
    hclRecircConc: 'HCl再循環濃度',
    celsius: '°C',
    kgPerHour: 'kg/h',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'mg/Nm³',
    kgPerM3: 'kg/m³',
    percent: '%',
    seconds: 's',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': '排ガスデータ',
    'Solution de Lavage': '洗浄溶液',
    'Paramètres de Conception': '設計パラメータ',
    'Résultats des Calculs': '計算結果',
    'Bilans Matière': '物質収支',
    'Dimensionnement Colonne': '塔のサイジング',
    'Débits de Solution': '溶液流量',
    'Paramètres de Transfert': '移動パラメータ',
    'Résultats': '結果',
    'Débit volumique fumées (Nm³/h)': '排ガス体積流量 (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'SO2入口濃度 (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': '希望SO2出口 (mg/Nm³)',
    'Température fumées (°C)': '排ガス温度 (°C)',
    'Teneur O2 fumées (%)': '排ガスO2含有量 (%)',
    'Pression fumées (mbar)': '排ガス圧力 (mbar)',
    'Type de réactif': '試薬タイプ',
    'Concentration solution (% massique)': '溶液濃度 (% w/w)',
    'pH solution souhaité': '希望溶液pH',
    'Température solution (°C)': '溶液温度 (°C)',
    'Rapport L/G (L/m³)': 'L/G比 (L/m³)',
    'Vitesse gaz colonne (m/s)': '塔ガス速度 (m/s)',
    'Hauteur garnissage (m)': '充填物の高さ (m)',
    'Type de garnissage': '充填物タイプ',
    'NaOH (Soude caustique)': 'NaOH (苛性ソーダ)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (炭酸ナトリウム)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (重炭酸ナトリウム)',
    'Anneaux de Pall': 'Pall環',
    'Anneaux de Raschig': 'Raschig環',
    'Selles de Berl': 'Berl鞍',
    'Garnissage structuré': '構造化充填物',
    'Charge SO2 éliminée': '除去されたSO2負荷',
    'Consommation réactif': '試薬消費',
    'avec 20% d\'excès': '20%過剰',
    'Efficacité d\'épuration': '浄化効率',
    'Diamètre colonne': '塔直径',
    'Surface section colonne': '塔断面積',
    'Volume garnissage': '充填物体積',
    'Débit solution lavage': '洗浄溶液流量',
    'Solution': '溶液',
    'Débit de purge estimé': '推定パージ流量',
    'Coefficient KLa SO2': 'SO2 KLa係数',
    'valeur estimée': '推定値',
    'Nombre d\'unités de transfert': '移動ユニット数',
    'Surface d\'échange': '交換面積',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': '排ガス入口',
    'Concentrations HCl': 'HCl濃度',
    'Performances Épuratoires': '浄化性能',
    'Performances Hydrauliques': '油圧性能',
    'Bilans Eau et pH': '水バランスとpH',
    'Résumé des Paramètres': 'パラメータサマリー',
  },

  ru: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'Калькулятор системы закаливания HCl',
    activeCalculation: 'Автоматический расчет активен',
    realtimeUpdate: 'Обновление в реальном времени',
    convergence: 'Сходимость',
    boucle1: 'Цикл 1',
    boucle2: 'Цикл 2',
    errorTitle: 'Ошибка',
    warningTitle: 'Предупреждение',
    successTitle: 'Автоматический расчет активен',
    totalMassFlowZero: 'Полный массовый расход не может быть нулевым',
    invalidTempPressure: 'Температура и давление должны быть положительными',
    invalidEfficiency: 'Эффективность должна быть между 0 и 1',
    calculationError: 'Ошибка расчета',
    speedWarning: 'Скорость колонны {speed} м/s вне спецификации (10-15 м/s)',
    coneSpeedWarning: 'Скорость конуса {speed} м/s вне спецификации (30-40 м/s)',
    liquidFlowWarning: 'Расход распыляемой жидкости {flow} кг/ч превышает максимум {max} кг/ч',
    fuelInlet: 'Поступающие газы',
    designParameters: 'Параметры конструкции',
    hclConcentrations: 'Концентрации HCl',
    resultsTitle: 'Результаты расчета',
    temperature: 'Температура (°C)',
    co2: 'CO₂ (кг/ч)',
    h2o: 'H₂O (кг/ч)',
    o2: 'O₂ (кг/ч)',
    n2: 'N₂ (кг/ч)',
    so2: 'SO₂ (кг/ч)',
    hcl: 'HCl (кг/ч)',
    pressure: 'Давление (mmHg)',
    upstreamPressure: 'Давление по потоку (mmH2O)',
    venturiEfficiency: 'Эффективность Вентури',
    waterSupplyTemp: 'Температура подачи воды (°C)',
    quenchDiameter: 'Диаметр закалки (м)',
    coneDiameter: 'Диаметр конуса (мм)',
    maxLiquidFlow: 'Макс. расход жидкости (кг/ч)',
    hclRecirculation: 'Конц. HCl рециркуляция (%)',
    hclSpray: 'Конц. HCl распыл (%)',
    purificationPerformance: 'Производительность очистки',
    exitTemp: 'Температура на выходе газа',
    saturationTemp: 'Температура насыщения',
    hclEfficiency: 'Эффективность HCl',
    hclExit: 'Выход HCl',
    hclDry: 'HCl сухой 11% O₂',
    so2Dry: 'SO₂ сухой 11% O₂',
    hydraulicPerformance: 'Гидравлическая производительность',
    columnSpeed: 'Скорость колонны',
    coneSpeed: 'Скорость конуса',
    saturationHeight: 'Высота насыщения',
    purifiedDensity: 'Очищенная плотность',
    waterBalance: 'Водный баланс и pH',
    evaporation: 'Испарение',
    waterSupply: 'Подача воды',
    purge: 'Продувка',
    sprayLiquid: 'Распыляемая жидкость',
    sprayPh: 'pH распыла',
    recircPh: 'pH рециркуляции',
    hclSprayConc: 'Конц. HCl распыл',
    hclRecircConc: 'Конц. HCl рециркуляция',
    celsius: '°C',
    kgPerHour: 'кг/ч',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'м/s',
    meter: 'м',
    mgPerNm3: 'мг/Nm³',
    kgPerM3: 'кг/м³',
    percent: '%',
    seconds: 'с',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'Данные газов',
    'Solution de Lavage': 'Промывная жидкость',
    'Paramètres de Conception': 'Параметры конструкции',
    'Résultats des Calculs': 'Результаты расчетов',
    'Bilans Matière': 'Материальные балансы',
    'Dimensionnement Colonne': 'Размеры колонны',
    'Débits de Solution': 'Расходы жидкости',
    'Paramètres de Transfert': 'Параметры передачи',
    'Résultats': 'Результаты',
    'Débit volumique fumées (Nm³/h)': 'Объемный расход газа (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'Концентрация SO2 на входе (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'Требуемый SO2 на выходе (mg/Nm³)',
    'Température fumées (°C)': 'Температура газа (°C)',
    'Teneur O2 fumées (%)': 'Содержание O2 в газе (%)',
    'Pression fumées (mbar)': 'Давление газа (mbar)',
    'Type de réactif': 'Тип реагента',
    'Concentration solution (% massique)': 'Концентрация раствора (% м/м)',
    'pH solution souhaité': 'Требуемый pH раствора',
    'Température solution (°C)': 'Температура раствора (°C)',
    'Rapport L/G (L/m³)': 'Отношение L/G (L/m³)',
    'Vitesse gaz colonne (m/s)': 'Скорость газа в колонне (m/s)',
    'Hauteur garnissage (m)': 'Высота насадки (m)',
    'Type de garnissage': 'Тип насадки',
    'NaOH (Soude caustique)': 'NaOH (Каустическая сода)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (Карбонат натрия)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (Бикарбонат натрия)',
    'Anneaux de Pall': 'Кольца Палла',
    'Anneaux de Raschig': 'Кольца Рашига',
    'Selles de Berl': 'Сёдла Берла',
    'Garnissage structuré': 'Структурированная насадка',
    'Charge SO2 éliminée': 'Удаленная нагрузка SO2',
    'Consommation réactif': 'Расход реагента',
    'avec 20% d\'excès': 'с 20% избытком',
    'Efficacité d\'épuration': 'Эффективность очистки',
    'Diamètre colonne': 'Диаметр колонны',
    'Surface section colonne': 'Площадь поперечного сечения колонны',
    'Volume garnissage': 'Объем насадки',
    'Débit solution lavage': 'Расход промывной жидкости',
    'Solution': 'Раствор',
    'Débit de purge estimé': 'Расчетный расход продувки',
    'Coefficient KLa SO2': 'Коэффициент KLa SO2',
    'valeur estimée': 'расчетное значение',
    'Nombre d\'unités de transfert': 'Количество ступеней переноса',
    'Surface d\'échange': 'Поверхность теплообмена',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'Входящие газы',
    'Concentrations HCl': 'Концентрации HCl',
    'Performances Épuratoires': 'Производительность очистки',
    'Performances Hydrauliques': 'Гидравлическая производительность',
    'Bilans Eau et pH': 'Баланс воды и pH',
    'Résumé des Paramètres': 'Краткое резюме параметров',
  },

  ar: {
    // ===== FICHIER 1 : HCl Quench System =====
    calculator: 'حاسبة نظام إطفاء HCl',
    activeCalculation: 'الحساب التلقائي نشط',
    realtimeUpdate: 'التحديث في الوقت الفعلي',
    convergence: 'التقارب',
    boucle1: 'الحلقة 1',
    boucle2: 'الحلقة 2',
    errorTitle: 'خطأ',
    warningTitle: 'تحذير',
    successTitle: 'الحساب التلقائي نشط',
    totalMassFlowZero: 'لا يمكن أن يكون إجمالي تدفق الكتلة صفراً',
    invalidTempPressure: 'يجب أن تكون درجة الحرارة والضغط موجبة',
    invalidEfficiency: 'يجب أن تكون الكفاءة بين 0 و 1',
    calculationError: 'خطأ في الحساب',
    speedWarning: 'سرعة العمود {speed} m/s خارج المواصفات (10-15 m/s)',
    coneSpeedWarning: 'سرعة المخروط {speed} m/s خارج المواصفات (30-40 m/s)',
    liquidFlowWarning: 'تدفق السائل الرشاش {flow} كغ/ساعة يتجاوز الحد الأقصى {max} كغ/ساعة',
    fuelInlet: 'الغازات الواردة',
    designParameters: 'معاملات التصميم',
    hclConcentrations: 'تركيزات HCl',
    resultsTitle: 'نتائج الحساب',
    temperature: 'درجة الحرارة (°C)',
    co2: 'CO₂ (كغ/ساعة)',
    h2o: 'H₂O (كغ/ساعة)',
    o2: 'O₂ (كغ/ساعة)',
    n2: 'N₂ (كغ/ساعة)',
    so2: 'SO₂ (كغ/ساعة)',
    hcl: 'HCl (كغ/ساعة)',
    pressure: 'الضغط (mmHg)',
    upstreamPressure: 'الضغط في المنطقة العلوية (mmH2O)',
    venturiEfficiency: 'كفاءة فينتوري',
    waterSupplyTemp: 'درجة حرارة مياه الإمداد (°C)',
    quenchDiameter: 'قطر الإطفاء (m)',
    coneDiameter: 'قطر المخروط (mm)',
    maxLiquidFlow: 'الحد الأقصى لتدفق السائل (كغ/ساعة)',
    hclRecirculation: 'تركيز HCl إعادة الدوران (%)',
    hclSpray: 'تركيز HCl الرشاش (%)',
    purificationPerformance: 'أداء التنقية',
    exitTemp: 'درجة حرارة الغاز عند الخروج',
    saturationTemp: 'درجة حرارة التشبع',
    hclEfficiency: 'كفاءة HCl',
    hclExit: 'مخرج HCl',
    hclDry: 'HCl جاف 11% O₂',
    so2Dry: 'SO₂ جاف 11% O₂',
    hydraulicPerformance: 'الأداء الهيدروليكي',
    columnSpeed: 'سرعة العمود',
    coneSpeed: 'سرعة المخروط',
    saturationHeight: 'ارتفاع التشبع',
    purifiedDensity: 'الكثافة المنقاة',
    waterBalance: 'التوازن المائي والرقم الهيدروجيني',
    evaporation: 'التبخر',
    waterSupply: 'إمداد المياه',
    purge: 'التطهير',
    sprayLiquid: 'السائل الرشاش',
    sprayPh: 'الرقم الهيدروجيني للرشاش',
    recircPh: 'الرقم الهيدروجيني لإعادة الدوران',
    hclSprayConc: 'تركيز HCl الرشاش',
    hclRecircConc: 'تركيز HCl إعادة الدوران',
    celsius: '°C',
    kgPerHour: 'كغ/ساعة',
    mmHg: 'mmHg',
    mmH2O: 'mmH2O',
    meterPerSecond: 'm/s',
    meter: 'm',
    mgPerNm3: 'مغ/Nm³',
    kgPerM3: 'كغ/م³',
    percent: '%',
    seconds: 'ث',

    // ===== FICHIER 2 : Scrubber SO2 =====
    'Données des Fumées': 'بيانات الدخان',
    'Solution de Lavage': 'محلول الغسيل',
    'Paramètres de Conception': 'معاملات التصميم',
    'Résultats des Calculs': 'نتائج الحسابات',
    'Bilans Matière': 'الأرصدة المادية',
    'Dimensionnement Colonne': 'حجم العمود',
    'Débits de Solution': 'تدفقات المحلول',
    'Paramètres de Transfert': 'معاملات النقل',
    'Résultats': 'النتائج',
    'Débit volumique fumées (Nm³/h)': 'تدفق الدخان الحجمي (Nm³/h)',
    'Concentration SO2 entrée (mg/Nm³)': 'تركيز SO2 عند المدخل (mg/Nm³)',
    'Concentration SO2 sortie souhaitée (mg/Nm³)': 'SO2 المخرج المطلوب (mg/Nm³)',
    'Température fumées (°C)': 'درجة حرارة الدخان (°C)',
    'Teneur O2 fumées (%)': 'محتوى O2 في الدخان (%)',
    'Pression fumées (mbar)': 'ضغط الدخان (mbar)',
    'Type de réactif': 'نوع الكاشف',
    'Concentration solution (% massique)': 'تركيز المحلول (% w/w)',
    'pH solution souhaité': 'pH المحلول المطلوب',
    'Température solution (°C)': 'درجة حرارة المحلول (°C)',
    'Rapport L/G (L/m³)': 'نسبة L/G (L/m³)',
    'Vitesse gaz colonne (m/s)': 'سرعة الغاز في العمود (m/s)',
    'Hauteur garnissage (m)': 'ارتفاع الحشوة (m)',
    'Type de garnissage': 'نوع الحشوة',
    'NaOH (Soude caustique)': 'NaOH (الصودا الكاوية)',
    'Na2CO3 (Carbonate de sodium)': 'Na2CO3 (كربونات الصوديوم)',
    'NaHCO3 (Bicarbonate de sodium)': 'NaHCO3 (بيكربونات الصوديوم)',
    'Anneaux de Pall': 'حلقات Pall',
    'Anneaux de Raschig': 'حلقات Raschig',
    'Selles de Berl': 'سروج Berl',
    'Garnissage structuré': 'حشوة منظمة',
    'Charge SO2 éliminée': 'حمولة SO2 المزالة',
    'Consommation réactif': 'استهلاك الكاشف',
    'avec 20% d\'excès': 'مع 20% فائض',
    'Efficacité d\'épuration': 'كفاءة التنقية',
    'Diamètre colonne': 'قطر العمود',
    'Surface section colonne': 'مساحة المقطع العرضي للعمود',
    'Volume garnissage': 'حجم الحشوة',
    'Débit solution lavage': 'تدفق محلول الغسيل',
    'Solution': 'محلول',
    'Débit de purge estimé': 'تدفق التطهير المقدر',
    'Coefficient KLa SO2': 'معامل KLa SO2',
    'valeur estimée': 'قيمة مقدرة',
    'Nombre d\'unités de transfert': 'عدد وحدات النقل',
    'Surface d\'échange': 'سطح التبادل',

    // ===== FICHIER 3 : Additional System =====
    'Fumées d\'Entrée': 'غازات الدخول',
    'Concentrations HCl': 'تركيزات HCl',
    'Performances Épuratoires': 'أداء التنقية',
    'Performances Hydrauliques': 'الأداء الهيدروليكي',
    'Bilans Eau et pH': 'توازن المياه والرقم الهيدروجيني',
    'Résumé des Paramètres': 'ملخص المعاملات',
  },
};