export const translations = {
  fr: {
    // FlueGasParameters (RK)
    calculationParameters: 'Paramètres de calcul',
    resetValues: 'Réinitialiser les valeurs',
    calculatedParameters: 'Paramètres calculés',
    airStoechio: 'Air stoechiométrique [kmol]',
    calculatedTemperature: 'Température calculée [°C]',
    waterContent: 'Teneur en eau [kg/Nm³]',
    hSystem: 'Enthalpie système [kJ/h]',
    airFactorCalculated: 'Facteur air calculé',
    combustionAirComposition: 'Composition de l\'air de combustion',
    atStoichiometry: 'À la stoechiométrie',
    atAdiabaticity: 'À l\'adiabaticité',
    combustionAirTotal: 'Air de combustion total',
    flueGasComposition: 'Composition des gaz de fumée',
    flueGasAtStoichiometry: 'Gaz de fumée à la stoechiométrie',
    outputFlueGasWithoutWater: 'Gaz de fumée en sortie sans eau',
    outputFlueGasWithWater: 'Gaz de fumée en sortie avec eau',
    export: 'Exporter',

    // STACKFlueGasParameters
    flueGasInletAtTemperature: 'Gaz de fumée en entrée à la température',
    clearMemory: 'Effacer la mémoire',

    // STACKFlueGasPollutantEmission
    flueGasCompositionInput: 'Composition des gaz de fumée',
    inputFlueGas: 'Gaz de fumée en entrée',
    O2RefPercent: 'O2 référence [%]',
    flyAshContent: 'Teneur en cendres volantes [g/Nm³]',

    // STACKdesign
    stackTheoreticHeight: 'Hauteur théorique de la cheminée indépendante',
    pollutantType: 'Type de polluant',
    gas: 'Gaz',
    dust: 'Poussière',
    zone: 'Zone',
    zoneDescription1: 'Zone peu polluée',
    zoneDescription2: 'Zone moyennement urbanisée ou industrialisée',
    zoneDescription3: 'Zone très urbanisée ou industrialisée',
    gasType: 'Type de gaz',
    calculatedResults: 'Résultats calculés',
    pollutantConcentration: 'Concentration des polluants [mg/Nm³]',
    minimumStackHeight: 'Hauteur minimale de cheminée [m]',
    multiStackConfiguration: 'Configuration multi-cheminées',
    multiStackCorrection: 'Résultat : correction multi-cheminées',
    correctedStackHeight: 'Hauteur cheminée corrigée [m]',
    heightDifferenceInitial: 'Différence avec hauteur initiale [m]',
    obstacleCalculation: 'Calcul avec obstacles',
    obstacleCorrection: 'Résultat : correction avec obstacles',
    stackHeightWithObstacles: 'Hauteur cheminée avec obstacles [m]',
    heightDifferenceMultiStack: 'Différence avec hauteur multi-stack [m]',
    regulatoryCompliance: 'Conformité réglementaire',
    emissionLimit: 'Valeur limite d\'émission',
    calculatedConcentration: 'Concentration calculée',
    status: 'Statut',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    note: 'Note',
    secondaryStackHeightNote: 'La hauteur minimale de la cheminée secondaire doit être calculée en fonction de la hauteur de la cheminée principale et de la distance entre les deux installations.',
    obstacleNoteText: 'La présence d\'obstacles à proximité de la cheminée peut affecter la dispersion des polluants et nécessiter un ajustement de hauteur.',
    
    // Input field labels
    wetFlueGasFlow: 'Débit des fumées humides [kg/h]',
    pollutantFlow: 'Débit de polluant [kg/h]',
    outletTemperature: 'Température de sortie [°C]',
    temperatureDifference: 'Delta Température sortie-air [°C]',
    distanceBetweenStacks: 'Distance entre cheminées [m]',
    secondaryStackHeight: 'Hauteur cheminée secondaire [m]',
    secondaryStackDiameter: 'Diamètre cheminée secondaire [m]',
    secondaryStackFlow: 'Débit des fumées cheminée secondaire [Nm³/h]',
    secondaryStackTemperature: 'Température cheminée secondaire [°C]',
    obstacleDistance: 'Distance de l\'obstacle [m]',
    obstacleHeight: 'Hauteur de l\'obstacle [m]',
    obstacleWidth: 'Largeur de l\'obstacle [m]',
    obstacleAngle: 'Angle de l\'obstacle [°]',

    // STACKMainPage
    stackConfiguration: 'Configuration de la CHEMINÉE',
    backToFlow: 'Retour au flux',
    flueGases: 'Gaz de fumée',
    pollutantEmissions: 'Émissions de polluants',
    design: 'Design',
    opex: 'Opex',

    // Design - Existing keys
    pressionAeraulique: 'Pression aéraulique [mmCE]',
    pdcMmCE: 'PDC [mmCE]',
    diametreInterne: 'Diamètre interne du four [m]',
    diametreExterne: 'Diamètre externe du four [m]',
    longueur: 'Longueur du four [m]',
    pente: 'Pente du four [°]',
    beta: 'Beta',
    nombreTours: 'Nombre de tours [rpm]',
    hauteurDechets: 'Hauteur des déchets [m]',
    masseVolumiqueDechets: 'Masse volumique des déchets [kg/m3]',
    debitDechetsSolides: 'Débit déchets solides [kg/h]',
    debitDechetsLiquides: 'Débit déchets liquides [kg/h]',
    typeCombustible: 'Type de combustible',
    typeAtomisation: 'Type d\'atomisation',
    typeEau: 'Type d\'eau',
    debitEau: 'Débit eau [m3/h]',
    temperatureEntree: 'Température entrée [°C]',
    temperatureSortie: 'Température sortie [°C]',
    epaisseurRefractaire: 'Épaisseur réfractaire [m]',
    temperaturePeau: 'Température de peau moyenne [°C]',
    dtRefroidissement: 'DT de refroidissement [°C]',
    debitHumideFumees: 'Débit humide des fumées [Nm3/h]',
    temperatureSCC: 'Température SCC [°C]',
    diametreSCC: 'Diamètre interne SCC [m]',
    tempsSejourDesire: 'Temps de séjour désiré [s]',
    typeCombustibleSCC: 'Type de combustible SCC',
    typeAtomisationSCC: 'Type d\'atomisation déchets SCC',
    nbTrappes: 'Actionner les vérins : nb de trappes',
    puissanceUnite: 'Puissance électrique par unité [kW/u]',
    masseImbrulees: 'Masse des imbrûlées [kg/h]',
    typeCamion: 'Type de camion',
    distance: 'Distance [km]',
    debitVentilateur: 'Débit du ventilateur de combustion [Nm3/h]',
    rendementVentilateur: 'Rendement du ventilateur de combustion [%]',
    h2oPourcent: 'H2O [%]',
    co2Pourcent: 'CO2 [%]',
    tfumProvisoire: 'Température fumées provisoire [°C]',
    emissiviteFume: 'Émissivité fumées',
    teauExtracteur: 'Température eau extracteur [°C]',
  },

  de: {
    // Fluent calculations
    calculationParameters: 'Berechnungsparameter',
    resetValues: 'Werte zurücksetzen',
    calculatedParameters: 'Berechnete Parameter',
    airStoechio: 'Stöchiometrische Luft [kmol]',
    calculatedTemperature: 'Berechnete Temperatur [°C]',
    waterContent: 'Wassergehalt [kg/Nm³]',
    hSystem: 'Systementhalpie [kJ/h]',
    airFactorCalculated: 'Berechneter Luftfaktor',
    combustionAirComposition: 'Zusammensetzung der Verbrennungsluft',
    atStoichiometry: 'Bei Stöchiometrie',
    atAdiabaticity: 'Bei Adiabatizität',
    combustionAirTotal: 'Gesamte Verbrennungsluft',
    flueGasComposition: 'Zusammensetzung der Rauchgase',
    flueGasAtStoichiometry: 'Rauchgase bei Stöchiometrie',
    outputFlueGasWithoutWater: 'Ausgangsrauchgas ohne Wasser',
    outputFlueGasWithWater: 'Ausgangsrauchgas mit Wasser',
    export: 'Exportieren',

    flueGasInletAtTemperature: 'Rauchgaseintritt bei Temperatur',
    clearMemory: 'Speicher löschen',

    flueGasCompositionInput: 'Rauchgaszusammensetzung',
    inputFlueGas: 'Eingangsrauchgas',
    O2RefPercent: 'O2 Referenz [%]',
    flyAshContent: 'Flugaschegehalt [g/Nm³]',

    stackTheoreticHeight: 'Theoretische Höhe des unabhängigen Schornsteins',
    pollutantType: 'Schadstofftyp',
    gas: 'Gas',
    dust: 'Staub',
    zone: 'Zone',
    zoneDescription1: 'Gering verschmutzte Zone',
    zoneDescription2: 'Mäßig urbanisiertes oder industrialisiertes Gebiet',
    zoneDescription3: 'Stark urbanisiertes oder industrialisiertes Gebiet',
    gasType: 'Gastyp',
    calculatedResults: 'Berechnete Ergebnisse',
    pollutantConcentration: 'Schadstoffkonzentration [mg/Nm³]',
    minimumStackHeight: 'Mindestschornsteinhöhe [m]',
    multiStackConfiguration: 'Multi-Stack-Konfiguration',
    multiStackCorrection: 'Ergebnis: Multi-Stack-Korrektur',
    correctedStackHeight: 'Korrigierte Schornsteinhohe [m]',
    heightDifferenceInitial: 'Unterschied zur Anfangshöhe [m]',
    obstacleCalculation: 'Berechnung mit Hindernissen',
    obstacleCorrection: 'Ergebnis: Korrektur mit Hindernissen',
    stackHeightWithObstacles: 'Schornsteinhohe mit Hindernissen [m]',
    heightDifferenceMultiStack: 'Unterschied zur Multi-Stack-Höhe [m]',
    regulatoryCompliance: 'Behördliche Einhaltung',
    emissionLimit: 'Emissionsgrenzwert',
    calculatedConcentration: 'Berechnete Konzentration',
    status: 'Status',
    compliant: 'Konform',
    nonCompliant: 'Nicht konform',
    note: 'Hinweis',
    secondaryStackHeightNote: 'Die Mindesthohe des Sekundärschornsteins sollte auf der Grundlage der Hohe des Primärschornsteins und des Abstands zwischen den beiden Anlagen berechnet werden.',
    obstacleNoteText: 'Das Vorhandensein von Hindernissen in der Nähe des Schornsteins kann die Schadstoffausbreitung beeinflussen und eine Höhennanpassung erfordern.',
    
    wetFlueGasFlow: 'Feuchter Rauchgasdurchsatz [kg/h]',
    pollutantFlow: 'Schadstoffdurchsatz [kg/h]',
    outletTemperature: 'Ausgangstemperatur [°C]',
    temperatureDifference: 'Temperaturunterschied Ausgang-Luft [°C]',
    distanceBetweenStacks: 'Abstand zwischen Schornsteinen [m]',
    secondaryStackHeight: 'Höhe des Sekundärschornsteins [m]',
    secondaryStackDiameter: 'Durchmesser des Sekundärschornsteins [m]',
    secondaryStackFlow: 'Rauchgasdurchsatz Sekundärschornstein [Nm³/h]',
    secondaryStackTemperature: 'Temperatur des Sekundärschornsteins [°C]',
    obstacleDistance: 'Hindernisabstand [m]',
    obstacleHeight: 'Hindernishshöhe [m]',
    obstacleWidth: 'Hindernisbreite [m]',
    obstacleAngle: 'Hinderniswinkel [°]',

    stackConfiguration: 'SCHORNSTEIN-Konfiguration',
    backToFlow: 'Zurück zu Fluss',
    flueGases: 'Rauchgase',
    pollutantEmissions: 'Schadstoffemissionen',
    design: 'Design',
    opex: 'Betriebskosten',
  },

  es: {
    calculationParameters: 'Parámetros de cálculo',
    resetValues: 'Restablecer valores',
    calculatedParameters: 'Parámetros calculados',
    airStoechio: 'Aire estequiométrico [kmol]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Contenido de agua [kg/Nm³]',
    hSystem: 'Entalpía del sistema [kJ/h]',
    airFactorCalculated: 'Factor de aire calculado',
    combustionAirComposition: 'Composición del aire de combustión',
    atStoichiometry: 'En estequiometría',
    atAdiabaticity: 'En adiabaticidad',
    combustionAirTotal: 'Aire de combustión total',
    flueGasComposition: 'Composición del gas de escape',
    flueGasAtStoichiometry: 'Gas de escape en estequiometría',
    outputFlueGasWithoutWater: 'Gas de escape sin agua',
    outputFlueGasWithWater: 'Gas de escape con agua',
    export: 'Exportar',

    flueGasInletAtTemperature: 'Entrada de gas de escape a temperatura',
    clearMemory: 'Limpiar memoria',

    flueGasCompositionInput: 'Composición del gas de escape',
    inputFlueGas: 'Gas de escape de entrada',
    O2RefPercent: 'Referencia O2 [%]',
    flyAshContent: 'Contenido de ceniza volante [g/Nm³]',

    stackTheoreticHeight: 'Altura teórica de la chimenea independiente',
    pollutantType: 'Tipo de contaminante',
    gas: 'Gas',
    dust: 'Polvo',
    zone: 'Zona',
    zoneDescription1: 'Zona poco contaminada',
    zoneDescription2: 'Zona moderadamente urbanizada o industrializada',
    zoneDescription3: 'Zona altamente urbanizada o industrializada',
    gasType: 'Tipo de gas',
    calculatedResults: 'Resultados calculados',
    pollutantConcentration: 'Concentración de contaminantes [mg/Nm³]',
    minimumStackHeight: 'Altura mínima de la chimenea [m]',
    multiStackConfiguration: 'Configuración multi-chimenea',
    multiStackCorrection: 'Resultado: corrección multi-chimenea',
    correctedStackHeight: 'Altura de chimenea corregida [m]',
    heightDifferenceInitial: 'Diferencia de altura inicial [m]',
    obstacleCalculation: 'Cálculo con obstáculos',
    obstacleCorrection: 'Resultado: corrección con obstáculos',
    stackHeightWithObstacles: 'Altura de chimenea con obstáculos [m]',
    heightDifferenceMultiStack: 'Diferencia de altura multi-chimenea [m]',
    regulatoryCompliance: 'Cumplimiento regulatorio',
    emissionLimit: 'Límite de emisión',
    calculatedConcentration: 'Concentración calculada',
    status: 'Estado',
    compliant: 'Conforme',
    nonCompliant: 'No conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'La altura mínima de la chimenea secundaria debe calcularse en función de la altura de la chimenea principal y la distancia entre las dos instalaciones.',
    obstacleNoteText: 'La presencia de obstáculos cerca de la chimenea puede afectar la dispersión de contaminantes y requerir un ajuste de altura.',
    
    wetFlueGasFlow: 'Caudal de gas de escape húmedo [kg/h]',
    pollutantFlow: 'Caudal de contaminante [kg/h]',
    outletTemperature: 'Temperatura de salida [°C]',
    temperatureDifference: 'Diferencia de temperatura salida-aire [°C]',
    distanceBetweenStacks: 'Distancia entre chimeneas [m]',
    secondaryStackHeight: 'Altura de chimenea secundaria [m]',
    secondaryStackDiameter: 'Diámetro de chimenea secundaria [m]',
    secondaryStackFlow: 'Caudal de gas chimenea secundaria [Nm³/h]',
    secondaryStackTemperature: 'Temperatura chimenea secundaria [°C]',
    obstacleDistance: 'Distancia del obstáculo [m]',
    obstacleHeight: 'Altura del obstáculo [m]',
    obstacleWidth: 'Ancho del obstáculo [m]',
    obstacleAngle: 'Ángulo del obstáculo [°]',

    stackConfiguration: 'Configuración de CHIMENEA',
    backToFlow: 'Volver al flujo',
    flueGases: 'Gases de escape',
    pollutantEmissions: 'Emisiones de contaminantes',
    design: 'Diseño',
    opex: 'Opex',
  },

  it: {
    calculationParameters: 'Parametri di calcolo',
    resetValues: 'Ripristina valori',
    calculatedParameters: 'Parametri calcolati',
    airStoechio: 'Aria stechiometrica [kmol]',
    calculatedTemperature: 'Temperatura calcolata [°C]',
    waterContent: 'Contenuto di acqua [kg/Nm³]',
    hSystem: 'Entalpia del sistema [kJ/h]',
    airFactorCalculated: 'Fattore aria calcolato',
    combustionAirComposition: 'Composizione dell\'aria di combustione',
    atStoichiometry: 'A stechiometria',
    atAdiabaticity: 'Ad adiabaticità',
    combustionAirTotal: 'Aria di combustione totale',
    flueGasComposition: 'Composizione dei gas di scarico',
    flueGasAtStoichiometry: 'Gas di scarico a stechiometria',
    outputFlueGasWithoutWater: 'Gas di scarico senza acqua',
    outputFlueGasWithWater: 'Gas di scarico con acqua',
    export: 'Esporta',

    flueGasInletAtTemperature: 'Ingresso gas di scarico alla temperatura',
    clearMemory: 'Cancella memoria',

    flueGasCompositionInput: 'Composizione gas di scarico',
    inputFlueGas: 'Gas di scarico in ingresso',
    O2RefPercent: 'Riferimento O2 [%]',
    flyAshContent: 'Contenuto di cenere volante [g/Nm³]',

    stackTheoreticHeight: 'Altezza teorica del camino indipendente',
    pollutantType: 'Tipo di inquinante',
    gas: 'Gas',
    dust: 'Polvere',
    zone: 'Zona',
    zoneDescription1: 'Zona poco inquinata',
    zoneDescription2: 'Area moderatamente urbanizzata o industrializzata',
    zoneDescription3: 'Area altamente urbanizzata o industrializzata',
    gasType: 'Tipo di gas',
    calculatedResults: 'Risultati calcolati',
    pollutantConcentration: 'Concentrazione di inquinanti [mg/Nm³]',
    minimumStackHeight: 'Altezza minima del camino [m]',
    multiStackConfiguration: 'Configurazione multi-camino',
    multiStackCorrection: 'Risultato: correzione multi-camino',
    correctedStackHeight: 'Altezza camino corretta [m]',
    heightDifferenceInitial: 'Differenza dall\'altezza iniziale [m]',
    obstacleCalculation: 'Calcolo con ostacoli',
    obstacleCorrection: 'Risultato: correzione con ostacoli',
    stackHeightWithObstacles: 'Altezza camino con ostacoli [m]',
    heightDifferenceMultiStack: 'Differenza dall\'altezza multi-camino [m]',
    regulatoryCompliance: 'Conformità normativa',
    emissionLimit: 'Limite di emissione',
    calculatedConcentration: 'Concentrazione calcolata',
    status: 'Stato',
    compliant: 'Conforme',
    nonCompliant: 'Non conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'L\'altezza minima del camino secondario deve essere calcolata in base all\'altezza del camino primario e alla distanza tra i due impianti.',
    obstacleNoteText: 'La presenza di ostacoli vicino al camino può influenzare la dispersione degli inquinanti e potrebbe richiedere un adeguamento dell\'altezza.',
    
    wetFlueGasFlow: 'Portata gas di scarico umido [kg/h]',
    pollutantFlow: 'Portata di inquinante [kg/h]',
    outletTemperature: 'Temperatura di uscita [°C]',
    temperatureDifference: 'Differenza di temperatura uscita-aria [°C]',
    distanceBetweenStacks: 'Distanza tra camini [m]',
    secondaryStackHeight: 'Altezza camino secondario [m]',
    secondaryStackDiameter: 'Diametro camino secondario [m]',
    secondaryStackFlow: 'Portata gas camino secondario [Nm³/h]',
    secondaryStackTemperature: 'Temperatura camino secondario [°C]',
    obstacleDistance: 'Distanza ostacolo [m]',
    obstacleHeight: 'Altezza ostacolo [m]',
    obstacleWidth: 'Larghezza ostacolo [m]',
    obstacleAngle: 'Angolo ostacolo [°]',

    stackConfiguration: 'Configurazione CAMINO',
    backToFlow: 'Torna al flusso',
    flueGases: 'Gas di scarico',
    pollutantEmissions: 'Emissioni di inquinanti',
    design: 'Design',
    opex: 'Opex',
  },

  pt: {
    calculationParameters: 'Parâmetros de cálculo',
    resetValues: 'Redefinir valores',
    calculatedParameters: 'Parâmetros calculados',
    airStoechio: 'Ar estequiométrico [kmol]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Conteúdo de água [kg/Nm³]',
    hSystem: 'Entalpia do sistema [kJ/h]',
    airFactorCalculated: 'Fator de ar calculado',
    combustionAirComposition: 'Composição do ar de combustão',
    atStoichiometry: 'Na estequiometria',
    atAdiabaticity: 'Na adiabaticidade',
    combustionAirTotal: 'Ar de combustão total',
    flueGasComposition: 'Composição dos gases de escape',
    flueGasAtStoichiometry: 'Gases de escape na estequiometria',
    outputFlueGasWithoutWater: 'Gases de escape sem água',
    outputFlueGasWithWater: 'Gases de escape com água',
    export: 'Exportar',

    flueGasInletAtTemperature: 'Entrada de gás de escape à temperatura',
    clearMemory: 'Limpar memória',

    flueGasCompositionInput: 'Composição de gases de escape',
    inputFlueGas: 'Gás de escape de entrada',
    O2RefPercent: 'Referência O2 [%]',
    flyAshContent: 'Conteúdo de cinza volante [g/Nm³]',

    stackTheoreticHeight: 'Altura teórica da chaminé independente',
    pollutantType: 'Tipo de poluente',
    gas: 'Gás',
    dust: 'Poeira',
    zone: 'Zona',
    zoneDescription1: 'Zona pouco poluída',
    zoneDescription2: 'Área moderadamente urbanizada ou industrializada',
    zoneDescription3: 'Área altamente urbanizada ou industrializada',
    gasType: 'Tipo de gás',
    calculatedResults: 'Resultados calculados',
    pollutantConcentration: 'Concentração de poluentes [mg/Nm³]',
    minimumStackHeight: 'Altura mínima da chaminé [m]',
    multiStackConfiguration: 'Configuração multi-chaminé',
    multiStackCorrection: 'Resultado: correção multi-chaminé',
    correctedStackHeight: 'Altura de chaminé corrigida [m]',
    heightDifferenceInitial: 'Diferença da altura inicial [m]',
    obstacleCalculation: 'Cálculo com obstáculos',
    obstacleCorrection: 'Resultado: correção com obstáculos',
    stackHeightWithObstacles: 'Altura de chaminé com obstáculos [m]',
    heightDifferenceMultiStack: 'Diferença da altura multi-chaminé [m]',
    regulatoryCompliance: 'Conformidade regulatória',
    emissionLimit: 'Limite de emissão',
    calculatedConcentration: 'Concentração calculada',
    status: 'Status',
    compliant: 'Conforme',
    nonCompliant: 'Não conforme',
    note: 'Nota',
    secondaryStackHeightNote: 'A altura mínima da chaminé secundária deve ser calculada com base na altura da chaminé primária e na distância entre as duas instalações.',
    obstacleNoteText: 'A presença de obstáculos perto da chaminé pode afetar a dispersão de poluentes e pode exigir um ajuste de altura.',
    
    wetFlueGasFlow: 'Vazão de gás de escape úmido [kg/h]',
    pollutantFlow: 'Vazão de poluente [kg/h]',
    outletTemperature: 'Temperatura de saída [°C]',
    temperatureDifference: 'Diferença de temperatura saída-ar [°C]',
    distanceBetweenStacks: 'Distância entre chaminés [m]',
    secondaryStackHeight: 'Altura de chaminé secundária [m]',
    secondaryStackDiameter: 'Diâmetro de chaminé secundária [m]',
    secondaryStackFlow: 'Vazão de gás chaminé secundária [Nm³/h]',
    secondaryStackTemperature: 'Temperatura chaminé secundária [°C]',
    obstacleDistance: 'Distância do obstáculo [m]',
    obstacleHeight: 'Altura do obstáculo [m]',
    obstacleWidth: 'Largura do obstáculo [m]',
    obstacleAngle: 'Ângulo do obstáculo [°]',

    stackConfiguration: 'Configuração de CHAMINÉ',
    backToFlow: 'Voltar ao fluxo',
    flueGases: 'Gases de escape',
    pollutantEmissions: 'Emissões de poluentes',
    design: 'Design',
    opex: 'Opex',
  },

  ru: {
    calculationParameters: 'Параметры расчета',
    resetValues: 'Сбросить значения',
    calculatedParameters: 'Рассчитанные параметры',
    airStoechio: 'Стехиометрический воздух [кмоль]',
    calculatedTemperature: 'Рассчитанная температура [°C]',
    waterContent: 'Содержание воды [кг/Nm³]',
    hSystem: 'Энтальпия системы [кДж/ч]',
    airFactorCalculated: 'Рассчитанный коэффициент воздуха',
    combustionAirComposition: 'Состав воздуха сгорания',
    atStoichiometry: 'При стехиометрии',
    atAdiabaticity: 'При адиабатичности',
    combustionAirTotal: 'Общий воздух сгорания',
    flueGasComposition: 'Состав дымовых газов',
    flueGasAtStoichiometry: 'Дымовые газы при стехиометрии',
    outputFlueGasWithoutWater: 'Выходящие дымовые газы без воды',
    outputFlueGasWithWater: 'Выходящие дымовые газы с водой',
    export: 'Экспорт',

    flueGasInletAtTemperature: 'Вход дымовых газов при температуре',
    clearMemory: 'Очистить память',

    flueGasCompositionInput: 'Состав дымовых газов',
    inputFlueGas: 'Входящие дымовые газы',
    O2RefPercent: 'Эталон O2 [%]',
    flyAshContent: 'Содержание летучей золы [г/Nm³]',

    stackTheoreticHeight: 'Теоретическая высота независимой трубы',
    pollutantType: 'Тип загрязнителя',
    gas: 'Газ',
    dust: 'Пыль',
    zone: 'Зона',
    zoneDescription1: 'Слабо загрязненная зона',
    zoneDescription2: 'Умеренно урбанизированная или промышленная зона',
    zoneDescription3: 'Сильно урбанизированная или промышленная зона',
    gasType: 'Тип газа',
    calculatedResults: 'Рассчитанные результаты',
    pollutantConcentration: 'Концентрация загрязнителей [мг/Nm³]',
    minimumStackHeight: 'Минимальная высота трубы [м]',
    multiStackConfiguration: 'Конфигурация мульти-трубы',
    multiStackCorrection: 'Результат: коррекция мульти-трубы',
    correctedStackHeight: 'Скорректированная высота трубы [м]',
    heightDifferenceInitial: 'Разница с начальной высотой [м]',
    obstacleCalculation: 'Расчет с препятствиями',
    obstacleCorrection: 'Результат: коррекция с препятствиями',
    stackHeightWithObstacles: 'Высота трубы с препятствиями [м]',
    heightDifferenceMultiStack: 'Разница с высотой мульти-трубы [м]',
    regulatoryCompliance: 'Соответствие нормативам',
    emissionLimit: 'Предельное значение выбросов',
    calculatedConcentration: 'Рассчитанная концентрация',
    status: 'Статус',
    compliant: 'Соответствует',
    nonCompliant: 'Не соответствует',
    note: 'Примечание',
    secondaryStackHeightNote: 'Минимальная высота вторичной трубы должна рассчитываться на основе высоты первичной трубы и расстояния между двумя установками.',
    obstacleNoteText: 'Наличие препятствий рядом с трубой может повлиять на рассеивание загрязнителей и потребовать корректировки высоты.',
    
    wetFlueGasFlow: 'Расход влажных дымовых газов [кг/ч]',
    pollutantFlow: 'Расход загрязнителя [кг/ч]',
    outletTemperature: 'Температура на выходе [°C]',
    temperatureDifference: 'Разница температур выход-воздух [°C]',
    distanceBetweenStacks: 'Расстояние между трубами [м]',
    secondaryStackHeight: 'Высота вторичной трубы [м]',
    secondaryStackDiameter: 'Диаметр вторичной трубы [м]',
    secondaryStackFlow: 'Расход дымовых газов вторичной трубы [Nm³/ч]',
    secondaryStackTemperature: 'Температура вторичной трубы [°C]',
    obstacleDistance: 'Расстояние препятствия [м]',
    obstacleHeight: 'Высота препятствия [м]',
    obstacleWidth: 'Ширина препятствия [м]',
    obstacleAngle: 'Угол препятствия [°]',

    stackConfiguration: 'Конфигурация ТРУБЫ',
    backToFlow: 'Вернуться к потоку',
    flueGases: 'Дымовые газы',
    pollutantEmissions: 'Выбросы загрязнителей',
    design: 'Проектирование',
    opex: 'Opex',
  },

  zh: {
    calculationParameters: '计算参数',
    resetValues: '重置值',
    calculatedParameters: '计算的参数',
    airStoechio: '化学计量空气 [kmol]',
    calculatedTemperature: '计算温度 [°C]',
    waterContent: '含水量 [kg/Nm³]',
    hSystem: '系统焓 [kJ/h]',
    airFactorCalculated: '计算的空气因子',
    combustionAirComposition: '燃烧空气成分',
    atStoichiometry: '在化学计量中',
    atAdiabaticity: '在绝热条件下',
    combustionAirTotal: '总燃烧空气',
    flueGasComposition: '烟气成分',
    flueGasAtStoichiometry: '化学计量烟气',
    outputFlueGasWithoutWater: '无水输出烟气',
    outputFlueGasWithWater: '含水输出烟气',
    export: '导出',

    flueGasInletAtTemperature: '烟气进口温度',
    clearMemory: '清除内存',

    flueGasCompositionInput: '烟气成分',
    inputFlueGas: '输入烟气',
    O2RefPercent: '氧气参考值 [%]',
    flyAshContent: '飞灰含量 [g/Nm³]',

    stackTheoreticHeight: '独立烟囱的理论高度',
    pollutantType: '污染物类型',
    gas: '气体',
    dust: '尘埃',
    zone: '区域',
    zoneDescription1: '污染较少的区域',
    zoneDescription2: '中等城市化或工业化地区',
    zoneDescription3: '高度城市化或工业化地区',
    gasType: '气体类型',
    calculatedResults: '计算结果',
    pollutantConcentration: '污染物浓度 [mg/Nm³]',
    minimumStackHeight: '最小烟囱高度 [m]',
    multiStackConfiguration: '多烟囱配置',
    multiStackCorrection: '结果：多烟囱修正',
    correctedStackHeight: '修正烟囱高度 [m]',
    heightDifferenceInitial: '与初始高度的差值 [m]',
    obstacleCalculation: '有障碍物的计算',
    obstacleCorrection: '结果：有障碍物的修正',
    stackHeightWithObstacles: '有障碍物的烟囱高度 [m]',
    heightDifferenceMultiStack: '与多烟囱高度的差值 [m]',
    regulatoryCompliance: '法规符合性',
    emissionLimit: '排放限制值',
    calculatedConcentration: '计算浓度',
    status: '状态',
    compliant: '符合',
    nonCompliant: '不符合',
    note: '注意',
    secondaryStackHeightNote: '应根据主烟囱的高度和两个装置之间的距离来计算二级烟囱的最小高度。',
    obstacleNoteText: '烟囱附近的障碍物可能影响污染物的散布，可能需要调整高度。',
    
    wetFlueGasFlow: '湿烟气流量 [kg/h]',
    pollutantFlow: '污染物流量 [kg/h]',
    outletTemperature: '出口温度 [°C]',
    temperatureDifference: '出口-空气温度差 [°C]',
    distanceBetweenStacks: '烟囱之间的距离 [m]',
    secondaryStackHeight: '次级烟囱高度 [m]',
    secondaryStackDiameter: '次级烟囱直径 [m]',
    secondaryStackFlow: '次级烟囱烟气流量 [Nm³/h]',
    secondaryStackTemperature: '次级烟囱温度 [°C]',
    obstacleDistance: '障碍物距离 [m]',
    obstacleHeight: '障碍物高度 [m]',
    obstacleWidth: '障碍物宽度 [m]',
    obstacleAngle: '障碍物角度 [°]',

    stackConfiguration: '烟囱配置',
    backToFlow: '返回流程',
    flueGases: '烟气',
    pollutantEmissions: '污染物排放',
    design: '设计',
    opex: '运营成本',
  },

  ja: {
    calculationParameters: '計算パラメータ',
    resetValues: '値をリセット',
    calculatedParameters: '計算されたパラメータ',
    airStoechio: '化学量論空気 [kmol]',
    calculatedTemperature: '計算温度 [°C]',
    waterContent: '含水量 [kg/Nm³]',
    hSystem: 'システムエンタルピー [kJ/h]',
    airFactorCalculated: '計算された空気係数',
    combustionAirComposition: '燃焼空気の組成',
    atStoichiometry: '化学量論で',
    atAdiabaticity: '断熱条件で',
    combustionAirTotal: '総燃焼空気',
    flueGasComposition: '排気ガスの組成',
    flueGasAtStoichiometry: '化学量論排気ガス',
    outputFlueGasWithoutWater: '無水排気ガス',
    outputFlueGasWithWater: '含水排気ガス',
    export: 'エクスポート',

    flueGasInletAtTemperature: '排気ガス入口温度',
    clearMemory: 'メモリをクリア',

    flueGasCompositionInput: '排気ガス組成',
    inputFlueGas: '入力排気ガス',
    O2RefPercent: '酸素参照値 [%]',
    flyAshContent: 'フライアッシュ含有量 [g/Nm³]',

    stackTheoreticHeight: '独立煙突の理論的高さ',
    pollutantType: '汚染物質の種類',
    gas: 'ガス',
    dust: 'ダスト',
    zone: 'ゾーン',
    zoneDescription1: '汚染の少ないゾーン',
    zoneDescription2: '中程度の都市化または産業化地域',
    zoneDescription3: '高度に都市化または産業化した地域',
    gasType: 'ガスの種類',
    calculatedResults: '計算結果',
    pollutantConcentration: '汚染物質濃度 [mg/Nm³]',
    minimumStackHeight: '最小煙突高さ [m]',
    multiStackConfiguration: 'マルチスタック構成',
    multiStackCorrection: '結果：マルチスタック補正',
    correctedStackHeight: '補正された煙突の高さ [m]',
    heightDifferenceInitial: '初期高さからの差 [m]',
    obstacleCalculation: '障害物のある計算',
    obstacleCorrection: '結果：障害物のある補正',
    stackHeightWithObstacles: '障害物のある煙突の高さ [m]',
    heightDifferenceMultiStack: 'マルチスタック高さからの差 [m]',
    regulatoryCompliance: '規制適合性',
    emissionLimit: '排出限界値',
    calculatedConcentration: '計算濃度',
    status: 'ステータス',
    compliant: '適合',
    nonCompliant: '不適合',
    note: '注意',
    secondaryStackHeightNote: 'セカンダリ煙突の最小高さは、プライマリ煙突の高さと2つの設備間の距離に基づいて計算する必要があります。',
    obstacleNoteText: '煙突の近くの障害物は汚染物質の拡散に影響を与え、高さの調整が必要な場合があります。',
    
    wetFlueGasFlow: '湿排気ガス流量 [kg/h]',
    pollutantFlow: '汚染物質流量 [kg/h]',
    outletTemperature: '出口温度 [°C]',
    temperatureDifference: '出口-空気温度差 [°C]',
    distanceBetweenStacks: '煙突間距離 [m]',
    secondaryStackHeight: 'セカンダリ煙突高さ [m]',
    secondaryStackDiameter: 'セカンダリ煙突直径 [m]',
    secondaryStackFlow: 'セカンダリ煙突排気ガス流量 [Nm³/h]',
    secondaryStackTemperature: 'セカンダリ煙突温度 [°C]',
    obstacleDistance: '障害物距離 [m]',
    obstacleHeight: '障害物の高さ [m]',
    obstacleWidth: '障害物幅 [m]',
    obstacleAngle: '障害物角度 [°]',

    stackConfiguration: '煙突構成',
    backToFlow: 'フローに戻る',
    flueGases: '排気ガス',
    pollutantEmissions: '汚染物質排出',
    design: 'デザイン',
    opex: 'Opex',
  },

  ar: {
    calculationParameters: 'معاملات الحساب',
    resetValues: 'إعادة تعيين القيم',
    calculatedParameters: 'المعاملات المحسوبة',
    airStoechio: 'الهواء المتكافئ [kmol]',
    calculatedTemperature: 'درجة الحرارة المحسوبة [°C]',
    waterContent: 'محتوى الماء [kg/Nm³]',
    hSystem: 'إنتالبيا النظام [kJ/h]',
    airFactorCalculated: 'معامل الهواء المحسوب',
    combustionAirComposition: 'تركيب الهواء الاحتراق',
    atStoichiometry: 'في التكافؤ',
    atAdiabaticity: 'في الحالة الثابتة حرارياً',
    combustionAirTotal: 'إجمالي الهواء الاحتراق',
    flueGasComposition: 'تركيب غاز العادم',
    flueGasAtStoichiometry: 'غاز العادم في التكافؤ',
    outputFlueGasWithoutWater: 'غاز العادم بدون ماء',
    outputFlueGasWithWater: 'غاز العادم مع الماء',
    export: 'تصدير',

    flueGasInletAtTemperature: 'مدخل غاز العادم عند درجة الحرارة',
    clearMemory: 'مسح الذاكرة',

    flueGasCompositionInput: 'تركيب غاز العادم',
    inputFlueGas: 'غاز العادم المدخل',
    O2RefPercent: 'مرجع الأكسجين [%]',
    flyAshContent: 'محتوى الرماد المتطاير [g/Nm³]',

    stackTheoreticHeight: 'الارتفاع النظري للمداخن المستقلة',
    pollutantType: 'نوع الملوث',
    gas: 'غاز',
    dust: 'غبار',
    zone: 'منطقة',
    zoneDescription1: 'منطقة ملوثة قليلاً',
    zoneDescription2: 'منطقة حضرية أو صناعية معتدلة',
    zoneDescription3: 'منطقة حضرية أو صناعية عالية',
    gasType: 'نوع الغاز',
    calculatedResults: 'النتائج المحسوبة',
    pollutantConcentration: 'تركيز الملوثات [mg/Nm³]',
    minimumStackHeight: 'الحد الأدنى لارتفاع المدخن [m]',
    multiStackConfiguration: 'تكوين المداخن المتعددة',
    multiStackCorrection: 'النتيجة: تصحيح المداخن المتعددة',
    correctedStackHeight: 'ارتفاع المدخن المصحح [m]',
    heightDifferenceInitial: 'الفرق عن الارتفاع الأولي [m]',
    obstacleCalculation: 'حساب مع العقبات',
    obstacleCorrection: 'النتيجة: تصحيح مع العقبات',
    stackHeightWithObstacles: 'ارتفاع المدخن مع العقبات [m]',
    heightDifferenceMultiStack: 'الفرق عن ارتفاع المداخن المتعددة [m]',
    regulatoryCompliance: 'الامتثال التنظيمي',
    emissionLimit: 'حد الانبعاثات',
    calculatedConcentration: 'التركيز المحسوب',
    status: 'الحالة',
    compliant: 'متوافق',
    nonCompliant: 'غير متوافق',
    note: 'ملاحظة',
    secondaryStackHeightNote: 'يجب حساب الحد الأدنى لارتفاع المدخن الثانوي على أساس ارتفاع المدخن الأساسي والمسافة بين المنشأتين.',
    obstacleNoteText: 'قد تؤثر العقبات القريبة من المدخن على تشتت الملوثات وقد تتطلب تعديلاً في الارتفاع.',
    
    wetFlueGasFlow: 'معدل تدفق غاز العادم الرطب [kg/h]',
    pollutantFlow: 'معدل تدفق الملوث [kg/h]',
    outletTemperature: 'درجة حرارة المخرج [°C]',
    temperatureDifference: 'فرق درجة الحرارة مخرج-الهواء [°C]',
    distanceBetweenStacks: 'المسافة بين المداخن [m]',
    secondaryStackHeight: 'ارتفاع المدخن الثانوي [m]',
    secondaryStackDiameter: 'قطر المدخن الثانوي [m]',
    secondaryStackFlow: 'معدل تدفق غاز العادم للمدخن الثانوي [Nm³/h]',
    secondaryStackTemperature: 'درجة حرارة المدخن الثانوي [°C]',
    obstacleDistance: 'مسافة العقبة [m]',
    obstacleHeight: 'ارتفاع العقبة [m]',
    obstacleWidth: 'عرض العقبة [m]',
    obstacleAngle: 'زاوية العقبة [°]',

    stackConfiguration: 'تكوين المدخن',
    backToFlow: 'العودة إلى التدفق',
    flueGases: 'غاز العادم',
    pollutantEmissions: 'انبعاثات الملوثات',
    design: 'التصميم',
    opex: 'Opex',
  },

  en: {
    calculationParameters: 'Calculation parameters',
    resetValues: 'Reset values',
    calculatedParameters: 'Calculated parameters',
    airStoechio: 'Stoichiometric air [kmol]',
    calculatedTemperature: 'Calculated temperature [°C]',
    waterContent: 'Water content [kg/Nm³]',
    hSystem: 'System enthalpy [kJ/h]',
    airFactorCalculated: 'Calculated air factor',
    combustionAirComposition: 'Combustion air composition',
    atStoichiometry: 'At stoichiometry',
    atAdiabaticity: 'At adiabaticity',
    combustionAirTotal: 'Total combustion air',
    flueGasComposition: 'Flue gas composition',
    flueGasAtStoichiometry: 'Flue gas at stoichiometry',
    outputFlueGasWithoutWater: 'Output flue gas without water',
    outputFlueGasWithWater: 'Output flue gas with water',
    export: 'Export',

    flueGasInletAtTemperature: 'Flue gas inlet at temperature',
    clearMemory: 'Clear memory',

    flueGasCompositionInput: 'Flue gas composition',
    inputFlueGas: 'Input flue gas',
    O2RefPercent: 'O2 reference [%]',
    flyAshContent: 'Fly ash content [g/Nm³]',

    stackTheoreticHeight: 'Theoretical height of independent stack',
    pollutantType: 'Pollutant type',
    gas: 'Gas',
    dust: 'Dust',
    zone: 'Zone',
    zoneDescription1: 'Low pollution zone',
    zoneDescription2: 'Moderately urbanized or industrialized area',
    zoneDescription3: 'Highly urbanized or industrialized area',
    gasType: 'Gas type',
    calculatedResults: 'Calculated results',
    pollutantConcentration: 'Pollutant concentration [mg/Nm³]',
    minimumStackHeight: 'Minimum stack height [m]',
    multiStackConfiguration: 'Multi-stack configuration',
    multiStackCorrection: 'Result: multi-stack correction',
    correctedStackHeight: 'Corrected stack height [m]',
    heightDifferenceInitial: 'Difference from initial height [m]',
    obstacleCalculation: 'Calculation with obstacles',
    obstacleCorrection: 'Result: correction with obstacles',
    stackHeightWithObstacles: 'Stack height with obstacles [m]',
    heightDifferenceMultiStack: 'Difference from multi-stack height [m]',
    regulatoryCompliance: 'Regulatory compliance',
    emissionLimit: 'Emission limit value',
    calculatedConcentration: 'Calculated concentration',
    status: 'Status',
    compliant: 'Compliant',
    nonCompliant: 'Non-compliant',
    note: 'Note',
    secondaryStackHeightNote: 'The minimum height of the secondary stack should be calculated based on the height of the primary stack and the distance between the two installations.',
    obstacleNoteText: 'The presence of obstacles near the stack can affect pollutant dispersion and may require height adjustment.',
    
    wetFlueGasFlow: 'Wet flue gas flow rate [kg/h]',
    pollutantFlow: 'Pollutant flow rate [kg/h]',
    outletTemperature: 'Outlet temperature [°C]',
    temperatureDifference: 'Temperature difference outlet-air [°C]',
    distanceBetweenStacks: 'Distance between stacks [m]',
    secondaryStackHeight: 'Secondary stack height [m]',
    secondaryStackDiameter: 'Secondary stack diameter [m]',
    secondaryStackFlow: 'Secondary stack flue gas flow rate [Nm³/h]',
    secondaryStackTemperature: 'Secondary stack temperature [°C]',
    obstacleDistance: 'Distance from obstacle [m]',
    obstacleHeight: 'Obstacle height [m]',
    obstacleWidth: 'Obstacle width [m]',
    obstacleAngle: 'Obstacle angle [°]',

    stackConfiguration: 'STACK Configuration',
    backToFlow: 'Back to Flow',
    flueGases: 'Flue gases',
    pollutantEmissions: 'Pollutant Emissions',
    design: 'Design',
    opex: 'Opex',
  },
};