export const translations = {
  // ========== FRENCH TRANSLATIONS ==========
  fr: {
    'Calculation parameters': 'Paramètres de calcul',
    'Calculated parameters': 'Paramètres calculés',
    'Flue gas composition': 'Composition des gaz de combustion',
    'Input flue gas': 'Gaz de combustion d\'entrée',
    'Output flue gas': 'Gaz de combustion de sortie',
    'Residues calculated': 'Résidus calculés',
    'Clear memory': 'Effacer la mémoire',
    'Reset to Default Values': 'Réinitialiser aux valeurs par défaut',
    'Résultats': 'Résultats',
    'Back to Flow': 'Retour au flux',
    'None': 'Aucun',
    'Results': 'Résultats',
    'Flue gas temperature outlet [°C]': 'Température de sortie des gaz [°C]',
    'Ambient air temperature [°C]': 'Température de l\'air ambiant [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume d\'air entrant [Nm3/h]',
    'Thermal losses [%]': 'Pertes thermiques [%]',
    'Cooling water temperature [°C]': 'Température de l\'eau de refroidissement [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Température d\'entrée COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Eau pulvérisée/refroidissement [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume de gaz de sortie [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Gaz de combustion d\'entrée à la température d\'entrée',
    'Air ingress at ambient temperature': 'Apport d\'air à température ambiante',
    'Flue gas outlet at outlet temperature': 'Gaz de combustion de sortie à la température de sortie',
    'Fly ashes content outlet [g/Nm3]': 'Contenu des cendres volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Siccité des cendres de fond [%]',
    'O2 ref [%]': 'Référence O2 [%]',
    'Waste Flow [kg/h]': 'Flux de déchets [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flux de gaz humides [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flux de gaz secs [Nm3/h]',
    'O2 calculated [%]': 'O2 calculé [%]',
    'inert mass [kg/h]': 'Masse inerte [kg/h]',
    'Fly ash [kg/h]': 'Cendres volantes [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'Cendres COOLINGTOWER [kg/h]',
    'Pollutant': 'Polluant',
    'Reagent': 'Réactif',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Rendement (%)',
    'Stoich. Coeff.': 'Coeff. Stœchio.',
    'Output Mass': 'Masse de sortie',
    'Residue Mass': 'Masse résiduelle',
    'Reagent Mass': 'Masse du réactif',
    'Abated Mass': 'Masse éliminée',
    'Pollutant Treatment Table': 'Tableau de traitement des polluants',
    'Configuration du COOLINGTOWER': 'Configuration du COOLINGTOWER',
    'Sélection de la buse': 'Sélection de la buse',
    'Paramètres du spray': 'Paramètres du spray',
    'Paramètres du gaz': 'Paramètres du gaz',
    'Paramètres du liquide': 'Paramètres du liquide',
    'Réinitialiser les paramètres': 'Réinitialiser les paramètres',
    'Type de buse': 'Type de buse',
    'Cône creux': 'Cône creux',
    'Distribution étroite, bon pour l\'uniformité': 'Distribution étroite, bon pour l\'uniformité',
    'Cône plein': 'Cône plein',
    'Distribution plus large, meilleure couverture': 'Distribution plus large, meilleure couverture',
    'Jet plat': 'Jet plat',
    'Distribution large, bon pour les grandes surfaces': 'Distribution large, bon pour les grandes surfaces',
    'Spirale': 'Spirale',
    'Distribution très étroite, excellente atomisation': 'Distribution très étroite, excellente atomisation',
    'Pression (bar)': 'Pression (bar)',
    'Débit (L/min)': 'Débit (L/min)',
    'Diamètre moyen (m)': 'Diamètre moyen (m)',
    'Indice de distribution (n)': 'Indice de distribution (n)',
    'Température du gaz (K)': 'Température du gaz (K)',
    'Vitesse du gaz (m/s)': 'Vitesse du gaz (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Vitesse des gouttes initiale (m/s)',
    'Température du liquide (K)': 'Température du liquide (K)',
    'Caractéristiques calculées': 'Caractéristiques calculées',
    'Qualité du spray': 'Qualité du spray',
    'Hauteur minimale': 'Hauteur minimale',
    'Vitesse des gouttes': 'Vitesse des gouttes',
    'Angle de spray': 'Angle de spray',
    'Atomisation': 'Atomisation',
    'Uniformité': 'Uniformité',
    'Couverture': 'Couverture',
    'Excellente': 'Excellente',
    'Bonne': 'Bonne',
    'Moyenne': 'Moyenne',
    'Très uniforme': 'Très uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Moins uniforme',
    'Large couverture': 'Large couverture',
    'Couverture moyenne': 'Couverture moyenne',
    'Couverture concentrée': 'Couverture concentrée',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.',
    'COOLINGTOWER Image': 'Image COOLINGTOWER',
    'Flue gases': 'Gaz de combustion',
    'Pollutant Emissions': 'Émissions polluantes',
    'Design': 'Conception',
    'Opex': 'Opex',
    'pompe': 'pompe',
    'Réinitialiser': 'Réinitialiser',
    'Enregistrer': 'Enregistrer',
    'Annuler': 'Annuler',
    'Oui': 'Oui',
    'Non': 'Non',
    'Confirmer': 'Confirmer',
    'Supprime': 'Supprime',
  },

  // ========== ENGLISH TRANSLATIONS ==========
  en: {
    'Calculation parameters': 'Calculation parameters',
    'Calculated parameters': 'Calculated parameters',
    'Flue gas composition': 'Flue gas composition',
    'Input flue gas': 'Input flue gas',
    'Output flue gas': 'Output flue gas',
    'Residues calculated': 'Residues calculated',
    'Clear memory': 'Clear memory',
    'Reset to Default Values': 'Reset to Default Values',
    'Résultats': 'Results',
    'Back to Flow': 'Back to Flow',
    'None': 'None',
    'Results': 'Results',
    'Flue gas temperature outlet [°C]': 'Flue gas temperature outlet [°C]',
    'Ambient air temperature [°C]': 'Ambient air temperature [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume of air ingress [Nm3/h]',
    'Thermal losses [%]': 'Thermal losses [%]',
    'Cooling water temperature [°C]': 'Cooling water temperature [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Temperature inlet COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta enthalpies [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprayed/cooling water [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Outlet flue gas volume [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Flue gas inlet at inlet temperature',
    'Air ingress at ambient temperature': 'Air ingress at ambient temperature',
    'Flue gas outlet at outlet temperature': 'Flue gas outlet at outlet temperature',
    'Fly ashes content outlet [g/Nm3]': 'Fly ashes content outlet [g/Nm3]',
    'siccity bottom ash [%]': 'Siccity bottom ash [%]',
    'O2 ref [%]': 'O2 ref [%]',
    'Waste Flow [kg/h]': 'Waste Flow [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flue gas Flow Wet [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flue gas Flow Dry [Nm3/h]',
    'O2 calculated [%]': 'O2 calculated [%]',
    'inert mass [kg/h]': 'inert mass [kg/h]',
    'Fly ash [kg/h]': 'Fly ash [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'COOLINGTOWER ash [kg/h]',
    'Pollutant': 'Pollutant',
    'Reagent': 'Reagent',
    'Mass (kg/h)': 'Mass (kg/h)',
    'Efficiency (%)': 'Efficiency (%)',
    'Stoich. Coeff.': 'Stoich. Coeff.',
    'Output Mass': 'Output Mass',
    'Residue Mass': 'Residue Mass',
    'Reagent Mass': 'Reagent Mass',
    'Abated Mass': 'Abated Mass',
    'Pollutant Treatment Table': 'Pollutant Treatment Table',
    'Configuration du COOLINGTOWER': 'COOLINGTOWER Configuration',
    'Sélection de la buse': 'Nozzle Selection',
    'Paramètres du spray': 'Spray Parameters',
    'Paramètres du gaz': 'Gas Parameters',
    'Paramètres du liquide': 'Liquid Parameters',
    'Réinitialiser les paramètres': 'Reset Parameters',
    'Type de buse': 'Nozzle Type',
    'Cône creux': 'Hollow Cone',
    'Distribution étroite, bon pour l\'uniformité': 'Narrow distribution, good for uniformity',
    'Cône plein': 'Full Cone',
    'Distribution plus large, meilleure couverture': 'Wider distribution, better coverage',
    'Jet plat': 'Flat Jet',
    'Distribution large, bon pour les grandes surfaces': 'Wide distribution, good for large surfaces',
    'Spirale': 'Spiral',
    'Distribution très étroite, excellente atomisation': 'Very narrow distribution, excellent atomization',
    'Pression (bar)': 'Pressure (bar)',
    'Débit (L/min)': 'Flow Rate (L/min)',
    'Diamètre moyen (m)': 'Mean Diameter (m)',
    'Indice de distribution (n)': 'Distribution Index (n)',
    'Température du gaz (K)': 'Gas Temperature (K)',
    'Vitesse du gaz (m/s)': 'Gas Velocity (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Initial Droplet Velocity (m/s)',
    'Température du liquide (K)': 'Liquid Temperature (K)',
    'Caractéristiques calculées': 'Calculated Characteristics',
    'Qualité du spray': 'Spray Quality',
    'Hauteur minimale': 'Minimum Height',
    'Vitesse des gouttes': 'Droplet Velocity',
    'Angle de spray': 'Spray Angle',
    'Atomisation': 'Atomization',
    'Uniformité': 'Uniformity',
    'Couverture': 'Coverage',
    'Excellente': 'Excellent',
    'Bonne': 'Good',
    'Moyenne': 'Average',
    'Très uniforme': 'Very uniform',
    'Uniforme': 'Uniform',
    'Moins uniforme': 'Less uniform',
    'Large couverture': 'Wide coverage',
    'Couverture moyenne': 'Medium coverage',
    'Couverture concentrée': 'Concentrated coverage',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Error during calculation. Check input parameters.',
    'COOLINGTOWER Image': 'COOLINGTOWER Image',
    'Flue gases': 'Flue gases',
    'Pollutant Emissions': 'Pollutant Emissions',
    'Design': 'Design',
    'Opex': 'Opex',
    'pompe': 'pump',
    'Réinitialiser': 'Reset',
    'Enregistrer': 'Save',
    'Annuler': 'Cancel',
    'Oui': 'Yes',
    'Non': 'No',
    'Confirmer': 'Confirm',
    'Supprime': 'Delete',
  },

  // ========== GERMAN TRANSLATIONS ==========
  de: {
    'Calculation parameters': 'Berechnungsparameter',
    'Calculated parameters': 'Berechnete Parameter',
    'Flue gas composition': 'Rauchgaszusammensetzung',
    'Input flue gas': 'Rauchgas-Eingang',
    'Output flue gas': 'Rauchgas-Ausgang',
    'Residues calculated': 'Berechnete Rückstände',
    'Clear memory': 'Speicher löschen',
    'Reset to Default Values': 'Auf Standardwerte zurücksetzen',
    'Résultats': 'Ergebnisse',
    'Back to Flow': 'Zurück zum Fluss',
    'None': 'Keiner',
    'Results': 'Ergebnisse',
    'Flue gas temperature outlet [°C]': 'Rauchgastemperaturauslass [°C]',
    'Ambient air temperature [°C]': 'Umgebungslufttemperatur [°C]',
    'Volume of air ingress [Nm3/h]': 'Lufteintrittsvolumen [Nm3/h]',
    'Thermal losses [%]': 'Thermische Verluste [%]',
    'Cooling water temperature [°C]': 'Kühlwassertemperatur [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Temperatureeingang COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Delta-Enthalpien [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Sprühwasser/Kühlwasser [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Rauchgasausgangsvolumen [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Rauchgas-Eingang bei Eingangstemperatur',
    'Air ingress at ambient temperature': 'Lufteintritt bei Umgebungstemperatur',
    'Flue gas outlet at outlet temperature': 'Rauchgas-Ausgang bei Ausgangstemperatur',
    'Fly ashes content outlet [g/Nm3]': 'Flugaschegehalt Auslass [g/Nm3]',
    'siccity bottom ash [%]': 'Trockenheit der Bodenaschen [%]',
    'O2 ref [%]': 'O2 Referenz [%]',
    'Waste Flow [kg/h]': 'Abfallfluss [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Rauchgasfluss Nass [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Rauchgasfluss Trocken [Nm3/h]',
    'O2 calculated [%]': 'O2 berechnet [%]',
    'inert mass [kg/h]': 'inerte Masse [kg/h]',
    'Fly ash [kg/h]': 'Flugasche [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'COOLINGTOWER Asche [kg/h]',
    'Pollutant': 'Schadstoff',
    'Reagent': 'Reagenz',
    'Mass (kg/h)': 'Masse (kg/h)',
    'Efficiency (%)': 'Wirkungsgrad (%)',
    'Stoich. Coeff.': 'Stöch. Koeff.',
    'Output Mass': 'Ausgangsmasse',
    'Residue Mass': 'Restmasse',
    'Reagent Mass': 'Reagenzmasse',
    'Abated Mass': 'Reduzierte Masse',
    'Pollutant Treatment Table': 'Schadstoffbehandlungstabelle',
    'Configuration du COOLINGTOWER': 'COOLINGTOWER-Konfiguration',
    'Sélection de la buse': 'Düsenauswahl',
    'Paramètres du spray': 'Sprühparameter',
    'Paramètres du gaz': 'Gasparameter',
    'Paramètres du liquide': 'Flüssigkeitsparameter',
    'Réinitialiser les paramètres': 'Parameter zurücksetzen',
    'Type de buse': 'Düsentyp',
    'Cône creux': 'Hohlkegel',
    'Distribution étroite, bon pour l\'uniformité': 'Enge Verteilung, gut für Gleichmäßigkeit',
    'Cône plein': 'Vollkegel',
    'Distribution plus large, meilleure couverture': 'Breitere Verteilung, bessere Abdeckung',
    'Jet plat': 'Flacher Strahl',
    'Distribution large, bon pour les grandes surfaces': 'Breite Verteilung, gut für große Flächen',
    'Spirale': 'Spirale',
    'Distribution très étroite, excellente atomisation': 'Sehr enge Verteilung, ausgezeichnete Zerstäubung',
    'Pression (bar)': 'Druck (bar)',
    'Débit (L/min)': 'Durchfluss (L/min)',
    'Diamètre moyen (m)': 'Mittlerer Durchmesser (m)',
    'Indice de distribution (n)': 'Verteilungsindex (n)',
    'Température du gaz (K)': 'Gastemperatur (K)',
    'Vitesse du gaz (m/s)': 'Gasgeschwindigkeit (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Anfängliche Tropfengeschwindigkeit (m/s)',
    'Température du liquide (K)': 'Flüssigkeitstemperatur (K)',
    'Caractéristiques calculées': 'Berechnete Eigenschaften',
    'Qualité du spray': 'Sprühqualität',
    'Hauteur minimale': 'Mindesthöhe',
    'Vitesse des gouttes': 'Tropfengeschwindigkeit',
    'Angle de spray': 'Sprühwinkel',
    'Atomisation': 'Zerstäubung',
    'Uniformité': 'Gleichmäßigkeit',
    'Couverture': 'Abdeckung',
    'Excellente': 'Ausgezeichnet',
    'Bonne': 'Gut',
    'Moyenne': 'Durchschnitt',
    'Très uniforme': 'Sehr gleichmäßig',
    'Uniforme': 'Gleichmäßig',
    'Moins uniforme': 'Weniger gleichmäßig',
    'Large couverture': 'Breite Abdeckung',
    'Couverture moyenne': 'Mittlere Abdeckung',
    'Couverture concentrée': 'Konzentrierte Abdeckung',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Fehler bei der Berechnung. Überprüfen Sie die Eingabeparameter.',
    'COOLINGTOWER Image': 'COOLINGTOWER Bild',
    'Flue gases': 'Rauchgase',
    'Pollutant Emissions': 'Schadstoffemissionen',
    'Design': 'Auslegung',
    'Opex': 'Opex',
    'pompe': 'Pumpe',
    'Réinitialiser': 'Zurücksetzen',
    'Enregistrer': 'Speichern',
    'Annuler': 'Abbrechen',
    'Oui': 'Ja',
    'Non': 'Nein',
    'Confirmer': 'Bestätigen',
    'Supprime': 'Löschen',
  },

  // ========== SPANISH TRANSLATIONS ==========
  es: {
    'Calculation parameters': 'Parámetros de cálculo',
    'Calculated parameters': 'Parámetros calculados',
    'Flue gas composition': 'Composición del gas de escape',
    'Input flue gas': 'Gas de escape de entrada',
    'Output flue gas': 'Gas de escape de salida',
    'Residues calculated': 'Residuos calculados',
    'Clear memory': 'Borrar memoria',
    'Reset to Default Values': 'Restablecer valores predeterminados',
    'Résultats': 'Resultados',
    'Back to Flow': 'Volver al flujo',
    'None': 'Ninguno',
    'Results': 'Resultados',
    'Flue gas temperature outlet [°C]': 'Temperatura de salida del gas de escape [°C]',
    'Ambient air temperature [°C]': 'Temperatura del aire ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volumen de entrada de aire [Nm3/h]',
    'Thermal losses [%]': 'Pérdidas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura del agua de enfriamiento [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Temperatura de entrada COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Entalpías delta [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Agua pulverizada/enfriamiento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volumen de gas de salida [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Gas de escape de entrada a temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de aire a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Gas de escape de salida a temperatura de salida',
    'Fly ashes content outlet [g/Nm3]': 'Contenido de cenizas volantes [g/Nm3]',
    'siccity bottom ash [%]': 'Sequedad de cenizas de fondo [%]',
    'O2 ref [%]': 'Referencia O2 [%]',
    'Waste Flow [kg/h]': 'Flujo de residuos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flujo de gas húmedo [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flujo de gas seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Masa inerte [kg/h]',
    'Fly ash [kg/h]': 'Cenizas volantes [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'Cenizas COOLINGTOWER [kg/h]',
    'Pollutant': 'Contaminante',
    'Reagent': 'Reactivo',
    'Mass (kg/h)': 'Masa (kg/h)',
    'Efficiency (%)': 'Eficiencia (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Masa de salida',
    'Residue Mass': 'Masa residual',
    'Reagent Mass': 'Masa del reactivo',
    'Abated Mass': 'Masa reducida',
    'Pollutant Treatment Table': 'Tabla de tratamiento de contaminantes',
    'Configuration du COOLINGTOWER': 'Configuración del COOLINGTOWER',
    'Sélection de la buse': 'Selección de boquilla',
    'Paramètres du spray': 'Parámetros del pulverizador',
    'Paramètres du gaz': 'Parámetros del gas',
    'Paramètres du liquide': 'Parámetros del líquido',
    'Réinitialiser les paramètres': 'Restablecer parámetros',
    'Type de buse': 'Tipo de boquilla',
    'Cône creux': 'Cono hueco',
    'Distribution étroite, bon pour l\'uniformité': 'Distribución estrecha, buena para la uniformidad',
    'Cône plein': 'Cono lleno',
    'Distribution plus large, meilleure couverture': 'Distribución más amplia, mejor cobertura',
    'Jet plat': 'Chorro plano',
    'Distribution large, bon pour les grandes surfaces': 'Distribución amplia, buena para superficies grandes',
    'Spirale': 'Espiral',
    'Distribution très étroite, excellente atomisation': 'Distribución muy estrecha, excelente atomización',
    'Pression (bar)': 'Presión (bar)',
    'Débit (L/min)': 'Caudal (L/min)',
    'Diamètre moyen (m)': 'Diámetro medio (m)',
    'Indice de distribution (n)': 'Índice de distribución (n)',
    'Température du gaz (K)': 'Temperatura del gas (K)',
    'Vitesse du gaz (m/s)': 'Velocidad del gas (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Velocidad inicial de gotitas (m/s)',
    'Température du liquide (K)': 'Temperatura del líquido (K)',
    'Caractéristiques calculées': 'Características calculadas',
    'Qualité du spray': 'Calidad del pulverizador',
    'Hauteur minimale': 'Altura mínima',
    'Vitesse des gouttes': 'Velocidad de gotitas',
    'Angle de spray': 'Ángulo de pulverizador',
    'Atomisation': 'Atomización',
    'Uniformité': 'Uniformidad',
    'Couverture': 'Cobertura',
    'Excellente': 'Excelente',
    'Bonne': 'Bueno',
    'Moyenne': 'Promedio',
    'Très uniforme': 'Muy uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Menos uniforme',
    'Large couverture': 'Cobertura amplia',
    'Couverture moyenne': 'Cobertura media',
    'Couverture concentrée': 'Cobertura concentrada',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Error durante el cálculo. Verifique los parámetros de entrada.',
    'COOLINGTOWER Image': 'Imagen COOLINGTOWER',
    'Flue gases': 'Gases de escape',
    'Pollutant Emissions': 'Emisiones contaminantes',
    'Design': 'Diseño',
    'Opex': 'Opex',
    'pompe': 'Bomba',
    'Réinitialiser': 'Restablecer',
    'Enregistrer': 'Guardar',
    'Annuler': 'Cancelar',
    'Oui': 'Sí',
    'Non': 'No',
    'Confirmar': 'Confirmar',
    'Supprime': 'Eliminar',
  },

  // ========== ITALIAN TRANSLATIONS ==========
  it: {
    'Calculation parameters': 'Parametri di calcolo',
    'Calculated parameters': 'Parametri calcolati',
    'Flue gas composition': 'Composizione del gas di scarico',
    'Input flue gas': 'Gas di scarico in ingresso',
    'Output flue gas': 'Gas di scarico in uscita',
    'Residues calculated': 'Residui calcolati',
    'Clear memory': 'Cancella memoria',
    'Reset to Default Values': 'Ripristina valori predefiniti',
    'Résultats': 'Risultati',
    'Back to Flow': 'Torna al flusso',
    'None': 'Nessuno',
    'Results': 'Risultati',
    'Flue gas temperature outlet [°C]': 'Temperatura di uscita del gas [°C]',
    'Ambient air temperature [°C]': 'Temperatura dell\'aria ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume di ingresso aria [Nm3/h]',
    'Thermal losses [%]': 'Perdite termiche [%]',
    'Cooling water temperature [°C]': 'Temperatura dell\'acqua di raffreddamento [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Temperatura ingresso COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Entalpie delta [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Acqua spruzzata/raffreddamento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume gas di uscita [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Gas di scarico in ingresso a temperatura di ingresso',
    'Air ingress at ambient temperature': 'Ingresso aria a temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Gas di scarico in uscita a temperatura di uscita',
    'Fly ashes content outlet [g/Nm3]': 'Contenuto ceneri volanti in uscita [g/Nm3]',
    'siccity bottom ash [%]': 'Siccità delle ceneri di fondo [%]',
    'O2 ref [%]': 'Riferimento O2 [%]',
    'Waste Flow [kg/h]': 'Flusso di rifiuti [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Flusso gas umido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Flusso gas secco [Nm3/h]',
    'O2 calculated [%]': 'O2 calcolato [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Fly ash [kg/h]': 'Ceneri volanti [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'Ceneri COOLINGTOWER [kg/h]',
    'Pollutant': 'Inquinante',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Efficienza (%)',
    'Stoich. Coeff.': 'Coeff. Stechiom.',
    'Output Mass': 'Massa in uscita',
    'Residue Mass': 'Massa residua',
    'Reagent Mass': 'Massa reagente',
    'Abated Mass': 'Massa abbattuta',
    'Pollutant Treatment Table': 'Tabella di trattamento degli inquinanti',
    'Configuration du COOLINGTOWER': 'Configurazione COOLINGTOWER',
    'Sélection de la buse': 'Selezione ugello',
    'Paramètres du spray': 'Parametri spray',
    'Paramètres du gaz': 'Parametri gas',
    'Paramètres du liquide': 'Parametri liquido',
    'Réinitialiser les paramètres': 'Ripristina parametri',
    'Type de buse': 'Tipo di ugello',
    'Cône creux': 'Cono cavo',
    'Distribution étroite, bon pour l\'uniformité': 'Distribuzione stretta, buona per l\'uniformità',
    'Cône plein': 'Cono pieno',
    'Distribution plus large, meilleure couverture': 'Distribuzione più ampia, migliore copertura',
    'Jet plat': 'Getto piatto',
    'Distribution large, bon pour les grandes surfaces': 'Distribuzione ampia, buona per grandi superfici',
    'Spirale': 'Spirale',
    'Distribution très étroite, excellente atomisation': 'Distribuzione molto stretta, eccellente atomizzazione',
    'Pression (bar)': 'Pressione (bar)',
    'Débit (L/min)': 'Portata (L/min)',
    'Diamètre moyen (m)': 'Diametro medio (m)',
    'Indice de distribution (n)': 'Indice di distribuzione (n)',
    'Température du gaz (K)': 'Temperatura gas (K)',
    'Vitesse du gaz (m/s)': 'Velocità del gas (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Velocità iniziale delle gocce (m/s)',
    'Température du liquide (K)': 'Temperatura liquido (K)',
    'Caractéristiques calculées': 'Caratteristiche calcolate',
    'Qualité du spray': 'Qualità dello spray',
    'Hauteur minimale': 'Altezza minima',
    'Vitesse des gouttes': 'Velocità delle gocce',
    'Angle de spray': 'Angolo spray',
    'Atomisation': 'Atomizzazione',
    'Uniformité': 'Uniformità',
    'Couverture': 'Copertura',
    'Excellente': 'Eccellente',
    'Bonne': 'Buono',
    'Moyenne': 'Medio',
    'Très uniforme': 'Molto uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Meno uniforme',
    'Large couverture': 'Copertura ampia',
    'Couverture moyenne': 'Copertura media',
    'Couverture concentrée': 'Copertura concentrata',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Errore durante il calcolo. Controllare i parametri di ingresso.',
    'COOLINGTOWER Image': 'Immagine COOLINGTOWER',
    'Flue gases': 'Gas di scarico',
    'Pollutant Emissions': 'Emissioni di inquinanti',
    'Design': 'Progettazione',
    'Opex': 'Opex',
    'pompe': 'pompa',
    'Réinitialiser': 'Ripristina',
    'Enregistrer': 'Salva',
    'Annuler': 'Annulla',
    'Oui': 'Sì',
    'Non': 'No',
    'Confirmer': 'Conferma',
    'Supprime': 'Elimina',
  },

  // ========== PORTUGUESE TRANSLATIONS ==========
  pt: {
    'Calculation parameters': 'Parâmetros de cálculo',
    'Calculated parameters': 'Parâmetros calculados',
    'Flue gas composition': 'Composição do gás de escape',
    'Input flue gas': 'Gás de escape de entrada',
    'Output flue gas': 'Gás de escape de saída',
    'Residues calculated': 'Resíduos calculados',
    'Clear memory': 'Limpar memória',
    'Reset to Default Values': 'Redefinir para valores padrão',
    'Résultats': 'Resultados',
    'Back to Flow': 'Voltar ao fluxo',
    'None': 'Nenhum',
    'Results': 'Resultados',
    'Flue gas temperature outlet [°C]': 'Temperatura de saída do gás [°C]',
    'Ambient air temperature [°C]': 'Temperatura do ar ambiente [°C]',
    'Volume of air ingress [Nm3/h]': 'Volume de entrada de ar [Nm3/h]',
    'Thermal losses [%]': 'Perdas térmicas [%]',
    'Cooling water temperature [°C]': 'Temperatura da água de resfriamento [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Temperatura de entrada COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Entalpias delta [kJ/kg]',
    'Sprayed/cooling water [kg/h]': 'Água pulverizada/resfriamento [kg/h]',
    'Outlet flue gas volume [Nm3/h]': 'Volume do gás de saída [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'Gás de escape de entrada na temperatura de entrada',
    'Air ingress at ambient temperature': 'Entrada de ar na temperatura ambiente',
    'Flue gas outlet at outlet temperature': 'Gás de escape de saída na temperatura de saída',
    'Fly ashes content outlet [g/Nm3]': 'Conteúdo de cinzas volantes na saída [g/Nm3]',
    'siccity bottom ash [%]': 'Secura das cinzas de fundo [%]',
    'O2 ref [%]': 'Referência O2 [%]',
    'Waste Flow [kg/h]': 'Fluxo de resíduos [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': 'Fluxo de gás úmido [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'Fluxo de gás seco [Nm3/h]',
    'O2 calculated [%]': 'O2 calculado [%]',
    'inert mass [kg/h]': 'Massa inerte [kg/h]',
    'Fly ash [kg/h]': 'Cinzas volantes [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'Cinzas COOLINGTOWER [kg/h]',
    'Pollutant': 'Poluente',
    'Reagent': 'Reagente',
    'Mass (kg/h)': 'Massa (kg/h)',
    'Efficiency (%)': 'Eficiência (%)',
    'Stoich. Coeff.': 'Coef. Estequiom.',
    'Output Mass': 'Massa de saída',
    'Residue Mass': 'Massa residual',
    'Reagent Mass': 'Massa de reagente',
    'Abated Mass': 'Massa reduzida',
    'Pollutant Treatment Table': 'Tabela de tratamento de poluentes',
    'Configuration du COOLINGTOWER': 'Configuração do COOLINGTOWER',
    'Sélection de la buse': 'Seleção de bico',
    'Paramètres du spray': 'Parâmetros do spray',
    'Paramètres du gaz': 'Parâmetros do gás',
    'Paramètres du liquide': 'Parâmetros do líquido',
    'Réinitialiser les paramètres': 'Redefinir parâmetros',
    'Type de buse': 'Tipo de bico',
    'Cône creux': 'Cone oco',
    'Distribution étroite, bon pour l\'uniformité': 'Distribuição estreita, boa para uniformidade',
    'Cône plein': 'Cone cheio',
    'Distribution plus large, meilleure couverture': 'Distribuição mais ampla, melhor cobertura',
    'Jet plat': 'Jato plano',
    'Distribution large, bon pour les grandes surfaces': 'Distribuição ampla, boa para grandes superfícies',
    'Spirale': 'Espiral',
    'Distribution très étroite, excellente atomisation': 'Distribuição muito estreita, excelente atomização',
    'Pression (bar)': 'Pressão (bar)',
    'Débit (L/min)': 'Vazão (L/min)',
    'Diamètre moyen (m)': 'Diâmetro médio (m)',
    'Indice de distribution (n)': 'Índice de distribuição (n)',
    'Température du gaz (K)': 'Temperatura do gás (K)',
    'Vitesse du gaz (m/s)': 'Velocidade do gás (m/s)',
    'Vitesse des gouttes initiale (m/s)': 'Velocidade inicial das gotículas (m/s)',
    'Température du liquide (K)': 'Temperatura do líquido (K)',
    'Caractéristiques calculées': 'Características calculadas',
    'Qualité du spray': 'Qualidade do spray',
    'Hauteur minimale': 'Altura mínima',
    'Vitesse des gouttes': 'Velocidade das gotículas',
    'Angle de spray': 'Ângulo do spray',
    'Atomisation': 'Atomização',
    'Uniformité': 'Uniformidade',
    'Couverture': 'Cobertura',
    'Excellente': 'Excelente',
    'Bonne': 'Boa',
    'Moyenne': 'Médio',
    'Très uniforme': 'Muito uniforme',
    'Uniforme': 'Uniforme',
    'Moins uniforme': 'Menos uniforme',
    'Large couverture': 'Cobertura ampla',
    'Couverture moyenne': 'Cobertura média',
    'Couverture concentrée': 'Cobertura concentrada',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Erro durante o cálculo. Verifique os parâmetros de entrada.',
    'COOLINGTOWER Image': 'Imagem COOLINGTOWER',
    'Flue gases': 'Gases de escape',
    'Pollutant Emissions': 'Emissões de poluentes',
    'Design': 'Design',
    'Opex': 'Opex',
    'pompe': 'bomba',
    'Réinitialiser': 'Redefinir',
    'Enregistrer': 'Salvar',
    'Annuler': 'Cancelar',
    'Oui': 'Sim',
    'Non': 'Não',
    'Confirmar': 'Confirmar',
    'Supprime': 'Excluir',
  },

  // ========== CHINESE (Simplified) TRANSLATIONS ==========
  zh: {
    'Calculation parameters': '计算参数',
    'Calculated parameters': '计算的参数',
    'Flue gas composition': '烟气成分',
    'Input flue gas': '输入烟气',
    'Output flue gas': '输出烟气',
    'Residues calculated': '计算的残留物',
    'Clear memory': '清除内存',
    'Reset to Default Values': '重置为默认值',
    'Résultats': '结果',
    'Back to Flow': '返回流程',
    'None': '无',
    'Results': '结果',
    'Flue gas temperature outlet [°C]': '烟气出口温度 [°C]',
    'Ambient air temperature [°C]': '环境空气温度 [°C]',
    'Volume of air ingress [Nm3/h]': '进气体积 [Nm3/h]',
    'Thermal losses [%]': '热损失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Temperature inlet COOLINGTOWER [°C]': '冷却塔进口温度 [°C]',
    'Delta enthalpies [kJ/kg]': '焓差 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '喷洒/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '出口烟气体积 [Nm3/h]',
    'Flue gas inlet at inlet temperature': '进口温度处的烟气进口',
    'Air ingress at ambient temperature': '环境温度处的空气进入',
    'Flue gas outlet at outlet temperature': '出口温度处的烟气出口',
    'Fly ashes content outlet [g/Nm3]': '飞灰含量出口 [g/Nm3]',
    'siccity bottom ash [%]': '底灰干度 [%]',
    'O2 ref [%]': 'O2 参考 [%]',
    'Waste Flow [kg/h]': '废物流 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿烟气流 [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '干烟气流 [Nm3/h]',
    'O2 calculated [%]': '计算的 O2 [%]',
    'inert mass [kg/h]': '惰性质量 [kg/h]',
    'Fly ash [kg/h]': '飞灰 [kg/h]',
    'COOLINGTOWER ash [kg/h]': '冷却塔灰 [kg/h]',
    'Pollutant': '污染物',
    'Reagent': '试剂',
    'Mass (kg/h)': '质量 (kg/h)',
    'Efficiency (%)': '效率 (%)',
    'Stoich. Coeff.': '化学计量系数',
    'Output Mass': '输出质量',
    'Residue Mass': '残留质量',
    'Reagent Mass': '试剂质量',
    'Abated Mass': '减少质量',
    'Pollutant Treatment Table': '污染物处理表',
    'Configuration du COOLINGTOWER': '冷却塔配置',
    'Sélection de la buse': '喷嘴选择',
    'Paramètres du spray': '喷雾参数',
    'Paramètres du gaz': '气体参数',
    'Paramètres du liquide': '液体参数',
    'Réinitialiser les paramètres': '重置参数',
    'Type de buse': '喷嘴类型',
    'Cône creux': '空心锥',
    'Distribution étroite, bon pour l\'uniformité': '分布窄，有利于均匀性',
    'Cône plein': '实心锥',
    'Distribution plus large, meilleure couverture': '分布更宽，覆盖更好',
    'Jet plat': '平面喷射',
    'Distribution large, bon pour les grandes surfaces': '分布宽，适合大面积',
    'Spirale': '螺旋',
    'Distribution très étroite, excellente atomisation': '分布非常窄，优异的雾化',
    'Pression (bar)': '压力 (bar)',
    'Débit (L/min)': '流量 (L/min)',
    'Diamètre moyen (m)': '平均直径 (m)',
    'Indice de distribution (n)': '分布指数 (n)',
    'Température du gaz (K)': '气体温度 (K)',
    'Vitesse du gaz (m/s)': '气体速度 (m/s)',
    'Vitesse des gouttes initiale (m/s)': '初始液滴速度 (m/s)',
    'Température du liquide (K)': '液体温度 (K)',
    'Caractéristiques calculées': '计算的特性',
    'Qualité du spray': '喷雾质量',
    'Hauteur minimale': '最小高度',
    'Vitesse des gouttes': '液滴速度',
    'Angle de spray': '喷雾角',
    'Atomisation': '雾化',
    'Uniformité': '均匀性',
    'Couverture': '覆盖',
    'Excellente': '优秀',
    'Bonne': '良好',
    'Moyenne': '平均',
    'Très uniforme': '非常均匀',
    'Uniforme': '均匀',
    'Moins uniforme': '不均匀',
    'Large couverture': '广泛覆盖',
    'Couverture moyenne': '中等覆盖',
    'Couverture concentrée': '集中覆盖',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': '计算出错。请检查输入参数。',
    'COOLINGTOWER Image': '冷却塔图像',
    'Flue gases': '烟气',
    'Pollutant Emissions': '污染物排放',
    'Design': '设计',
    'Opex': '运营支出',
    'pompe': '泵',
    'Réinitialiser': '重置',
    'Enregistrer': '保存',
    'Annuler': '取消',
    'Oui': '是',
    'Non': '否',
    'Confirmer': '确认',
    'Supprime': '删除',
  },

  // ========== JAPANESE TRANSLATIONS ==========
  ja: {
    'Calculation parameters': '計算パラメータ',
    'Calculated parameters': '計算されたパラメータ',
    'Flue gas composition': '排ガス組成',
    'Input flue gas': '入口排ガス',
    'Output flue gas': '出口排ガス',
    'Residues calculated': '計算されたレジデュー',
    'Clear memory': 'メモリをクリア',
    'Reset to Default Values': 'デフォルト値にリセット',
    'Résultats': '結果',
    'Back to Flow': 'フローに戻る',
    'None': 'なし',
    'Results': '結果',
    'Flue gas temperature outlet [°C]': '排ガス温度出口 [°C]',
    'Ambient air temperature [°C]': '周囲空気温度 [°C]',
    'Volume of air ingress [Nm3/h]': '空気流入量 [Nm3/h]',
    'Thermal losses [%]': '熱損失 [%]',
    'Cooling water temperature [°C]': '冷却水温度 [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'クーリングタワー入口温度 [°C]',
    'Delta enthalpies [kJ/kg]': 'エンタルピー差 [kJ/kg]',
    'Sprayed/cooling water [kg/h]': '噴射/冷却水 [kg/h]',
    'Outlet flue gas volume [Nm3/h]': '出口排ガス体積 [Nm3/h]',
    'Flue gas inlet at inlet temperature': '入口温度での排ガス入口',
    'Air ingress at ambient temperature': '周囲温度での空気流入',
    'Flue gas outlet at outlet temperature': '出口温度での排ガス出口',
    'Fly ashes content outlet [g/Nm3]': 'フライアッシュ含有量出口 [g/Nm3]',
    'siccity bottom ash [%]': '底灰の乾燥度 [%]',
    'O2 ref [%]': 'O2 参照 [%]',
    'Waste Flow [kg/h]': '廃棄物流 [kg/h]',
    'Flue gas Flow Wet [Nm3/h]': '湿排ガスフロー [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': '乾燥排ガスフロー [Nm3/h]',
    'O2 calculated [%]': '計算された O2 [%]',
    'inert mass [kg/h]': '不活性質量 [kg/h]',
    'Fly ash [kg/h]': 'フライアッシュ [kg/h]',
    'COOLINGTOWER ash [kg/h]': 'クーリングタワー灰 [kg/h]',
    'Pollutant': '汚染物質',
    'Reagent': '試薬',
    'Mass (kg/h)': '質量 (kg/h)',
    'Efficiency (%)': '効率 (%)',
    'Stoich. Coeff.': '化学量論係数',
    'Output Mass': '出力質量',
    'Residue Mass': 'レジデュー質量',
    'Reagent Mass': '試薬質量',
    'Abated Mass': '低減質量',
    'Pollutant Treatment Table': '汚染物質処理表',
    'Configuration du COOLINGTOWER': 'クーリングタワー構成',
    'Sélection de la buse': 'ノズル選択',
    'Paramètres du spray': 'スプレーパラメータ',
    'Paramètres du gaz': 'ガスパラメータ',
    'Paramètres du liquide': '液体パラメータ',
    'Réinitialiser les paramètres': 'パラメータをリセット',
    'Type de buse': 'ノズルタイプ',
    'Cône creux': 'ホローコーン',
    'Distribution étroite, bon pour l\'uniformité': 'ナロー分布、均一性に良い',
    'Cône plein': 'フルコーン',
    'Distribution plus large, meilleure couverture': 'ワイド分布、より良いカバレッジ',
    'Jet plat': 'フラットジェット',
    'Distribution large, bon pour les grandes surfaces': 'ワイド分布、大面積に適している',
    'Spirale': 'スパイラル',
    'Distribution très étroite, excellente atomisation': 'ベリーナロー分布、優れた霧化',
    'Pression (bar)': '圧力 (bar)',
    'Débit (L/min)': '流量 (L/min)',
    'Diamètre moyen (m)': '平均直径 (m)',
    'Indice de distribution (n)': '分布指数 (n)',
    'Température du gaz (K)': 'ガス温度 (K)',
    'Vitesse du gaz (m/s)': 'ガス速度 (m/s)',
    'Vitesse des gouttes initiale (m/s)': '初期液滴速度 (m/s)',
    'Température du liquide (K)': '液体温度 (K)',
    'Caractéristiques calculées': '計算された特性',
    'Qualité du spray': 'スプレー品質',
    'Hauteur minimale': '最小高さ',
    'Vitesse des gouttes': '液滴速度',
    'Angle de spray': 'スプレー角度',
    'Atomisation': '霧化',
    'Uniformité': '均一性',
    'Couverture': 'カバレッジ',
    'Excellente': '優れた',
    'Bonne': '良好',
    'Moyenne': '平均',
    'Très uniforme': '非常に均一',
    'Uniforme': '均一',
    'Moins uniforme': 'やや不均一',
    'Large couverture': '広いカバレッジ',
    'Couverture moyenne': '中程度のカバレッジ',
    'Couverture concentrée': '集中カバレッジ',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': '計算中にエラーが発生しました。入力パラメータを確認してください。',
    'COOLINGTOWER Image': 'クーリングタワー画像',
    'Flue gases': '排ガス',
    'Pollutant Emissions': '汚染物質排出',
    'Design': '設計',
    'Opex': '運営経費',
    'pompe': 'ポンプ',
    'Réinitialiser': 'リセット',
    'Enregistrer': '保存',
    'Annuler': 'キャンセル',
    'Oui': 'はい',
    'Non': 'いいえ',
    'Confirmer': '確認',
    'Supprime': '削除',
  },

  // ========== RUSSIAN TRANSLATIONS ==========
  ru: {
    'Calculation parameters': 'Параметры расчета',
    'Calculated parameters': 'Расчетные параметры',
    'Flue gas composition': 'Состав дымовых газов',
    'Input flue gas': 'Входящие дымовые газы',
    'Output flue gas': 'Выходящие дымовые газы',
    'Residues calculated': 'Рассчитанные остатки',
    'Clear memory': 'Очистить память',
    'Reset to Default Values': 'Восстановить значения по умолчанию',
    'Résultats': 'Результаты',
    'Back to Flow': 'Вернуться к потоку',
    'None': 'Нет',
    'Results': 'Результаты',
    'Flue gas temperature outlet [°C]': 'Температура выходящих газов [°C]',
    'Ambient air temperature [°C]': 'Температура окружающего воздуха [°C]',
    'Volume of air ingress [Nm3/h]': 'Объем поступающего воздуха [Nm3/ч]',
    'Thermal losses [%]': 'Тепловые потери [%]',
    'Cooling water temperature [°C]': 'Температура охлаждающей воды [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'Температура входа COOLINGTOWER [°C]',
    'Delta enthalpies [kJ/kg]': 'Энтальпийные разности [кДж/кг]',
    'Sprayed/cooling water [kg/h]': 'Распыляемая/охлаждающая вода [кг/ч]',
    'Outlet flue gas volume [Nm3/h]': 'Объем выходящих газов [Nm3/ч]',
    'Flue gas inlet at inlet temperature': 'Входящие дымовые газы при температуре входа',
    'Air ingress at ambient temperature': 'Поступление воздуха при температуре окружающей среды',
    'Flue gas outlet at outlet temperature': 'Выходящие дымовые газы при температуре выхода',
    'Fly ashes content outlet [g/Nm3]': 'Содержание летучей золы на выходе [г/Nm3]',
    'siccity bottom ash [%]': 'Сухость золы шлака [%]',
    'O2 ref [%]': 'Справка O2 [%]',
    'Waste Flow [kg/h]': 'Поток отходов [кг/ч]',
    'Flue gas Flow Wet [Nm3/h]': 'Поток влажных газов [Nm3/ч]',
    'Flue gas Flow Dry [Nm3/h]': 'Поток сухих газов [Nm3/ч]',
    'O2 calculated [%]': 'Рассчитанный O2 [%]',
    'inert mass [kg/h]': 'Инертная масса [кг/ч]',
    'Fly ash [kg/h]': 'Летучая зола [кг/ч]',
    'COOLINGTOWER ash [kg/h]': 'Зола COOLINGTOWER [кг/ч]',
    'Pollutant': 'Загрязняющее вещество',
    'Reagent': 'Реагент',
    'Mass (kg/h)': 'Масса (кг/ч)',
    'Efficiency (%)': 'Эффективность (%)',
    'Stoich. Coeff.': 'Стехиометрический коэффициент',
    'Output Mass': 'Выходная масса',
    'Residue Mass': 'Остаточная масса',
    'Reagent Mass': 'Масса реагента',
    'Abated Mass': 'Сокращенная масса',
    'Pollutant Treatment Table': 'Таблица обработки загрязнителей',
    'Configuration du COOLINGTOWER': 'Конфигурация COOLINGTOWER',
    'Sélection de la buse': 'Выбор сопла',
    'Paramètres du spray': 'Параметры распыла',
    'Paramètres du gaz': 'Параметры газа',
    'Paramètres du liquide': 'Параметры жидкости',
    'Réinitialiser les paramètres': 'Переустановить параметры',
    'Type de buse': 'Тип сопла',
    'Cône creux': 'Полый конус',
    'Distribution étroite, bon pour l\'uniformité': 'Узкое распределение, хорошо для однородности',
    'Cône plein': 'Сплошной конус',
    'Distribution plus large, meilleure couverture': 'Более широкое распределение, лучшее покрытие',
    'Jet plat': 'Плоская струя',
    'Distribution large, bon pour les grandes surfaces': 'Широкое распределение, хорошо для больших поверхностей',
    'Spirale': 'Спираль',
    'Distribution très étroite, excellente atomisation': 'Очень узкое распределение, отличная атомизация',
    'Pression (bar)': 'Давление (бар)',
    'Débit (L/min)': 'Расход (л/мин)',
    'Diamètre moyen (m)': 'Средний диаметр (м)',
    'Indice de distribution (n)': 'Индекс распределения (n)',
    'Température du gaz (K)': 'Температура газа (K)',
    'Vitesse du gaz (m/s)': 'Скорость газа (м/с)',
    'Vitesse des gouttes initiale (m/s)': 'Начальная скорость капель (м/с)',
    'Température du liquide (K)': 'Температура жидкости (K)',
    'Caractéristiques calculées': 'Рассчитанные характеристики',
    'Qualité du spray': 'Качество распыла',
    'Hauteur minimale': 'Минимальная высота',
    'Vitesse des gouttes': 'Скорость капель',
    'Angle de spray': 'Угол распыла',
    'Atomisation': 'Атомизация',
    'Uniformité': 'Однородность',
    'Couverture': 'Покрытие',
    'Excellente': 'Отличная',
    'Bonne': 'Хорошая',
    'Moyenne': 'Средняя',
    'Très uniforme': 'Очень однородная',
    'Uniforme': 'Однородная',
    'Moins uniforme': 'Менее однородная',
    'Large couverture': 'Широкое покрытие',
    'Couverture moyenne': 'Среднее покрытие',
    'Couverture concentrée': 'Сосредоточенное покрытие',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'Ошибка при расчете. Проверьте входные параметры.',
    'COOLINGTOWER Image': 'Изображение COOLINGTOWER',
    'Flue gases': 'Дымовые газы',
    'Pollutant Emissions': 'Выбросы загрязнителей',
    'Design': 'Проектирование',
    'Opex': 'Opex',
    'pompe': 'насос',
    'Réinitialiser': 'Переустановить',
    'Enregistrer': 'Сохранить',
    'Annuler': 'Отмена',
    'Oui': 'Да',
    'Non': 'Нет',
    'Confirmer': 'Подтвердить',
    'Supprime': 'Удалить',
  },

  // ========== ARABIC TRANSLATIONS ==========
  ar: {
    'Calculation parameters': 'معاملات الحساب',
    'Calculated parameters': 'المعاملات المحسوبة',
    'Flue gas composition': 'تكوين غاز المداخن',
    'Input flue gas': 'غاز المداخن المدخل',
    'Output flue gas': 'غاز المداخن المخرج',
    'Residues calculated': 'البقايا المحسوبة',
    'Clear memory': 'مسح الذاكرة',
    'Reset to Default Values': 'إعادة تعيين إلى القيم الافتراضية',
    'Résultats': 'النتائج',
    'Back to Flow': 'العودة إلى التدفق',
    'None': 'لا شيء',
    'Results': 'النتائج',
    'Flue gas temperature outlet [°C]': 'درجة حرارة مخرج غاز المداخن [°C]',
    'Ambient air temperature [°C]': 'درجة حرارة الهواء المحيط [°C]',
    'Volume of air ingress [Nm3/h]': 'حجم دخول الهواء [Nm3/h]',
    'Thermal losses [%]': 'الخسائر الحرارية [%]',
    'Cooling water temperature [°C]': 'درجة حرارة ماء التبريد [°C]',
    'Temperature inlet COOLINGTOWER [°C]': 'درجة حرارة مدخل برج التبريد [°C]',
    'Delta enthalpies [kJ/kg]': 'فروقات الإنثالبيا [كيلو جول/كجم]',
    'Sprayed/cooling water [kg/h]': 'الماء المرشوش/ماء التبريد [كجم/ساعة]',
    'Outlet flue gas volume [Nm3/h]': 'حجم غاز المداخن المخرج [Nm3/h]',
    'Flue gas inlet at inlet temperature': 'مدخل غاز المداخن عند درجة حرارة الدخول',
    'Air ingress at ambient temperature': 'دخول الهواء عند درجة الحرارة المحيطة',
    'Flue gas outlet at outlet temperature': 'مخرج غاز المداخن عند درجة حرارة المخرج',
    'Fly ashes content outlet [g/Nm3]': 'محتوى الرماد المتطاير في المخرج [جم/Nm3]',
    'siccity bottom ash [%]': 'جفاف الرماد السفلي [%]',
    'O2 ref [%]': 'مرجع O2 [%]',
    'Waste Flow [kg/h]': 'تدفق النفايات [كجم/ساعة]',
    'Flue gas Flow Wet [Nm3/h]': 'تدفق الغاز الرطب [Nm3/h]',
    'Flue gas Flow Dry [Nm3/h]': 'تدفق الغاز الجاف [Nm3/h]',
    'O2 calculated [%]': 'O2 المحسوب [%]',
    'inert mass [kg/h]': 'الكتلة الخاملة [كجم/ساعة]',
    'Fly ash [kg/h]': 'الرماد المتطاير [كجم/ساعة]',
    'COOLINGTOWER ash [kg/h]': 'رماد برج التبريد [كجم/ساعة]',
    'Pollutant': 'ملوث',
    'Reagent': 'كاشف',
    'Mass (kg/h)': 'الكتلة (كجم/ساعة)',
    'Efficiency (%)': 'الكفاءة (%)',
    'Stoich. Coeff.': 'معامل المقياس المتكافئ',
    'Output Mass': 'كتلة المخرج',
    'Residue Mass': 'كتلة البقايا',
    'Reagent Mass': 'كتلة الكاشف',
    'Abated Mass': 'الكتلة المختزلة',
    'Pollutant Treatment Table': 'جدول معالجة الملوثات',
    'Configuration du COOLINGTOWER': 'تكوين برج التبريد',
    'Sélection de la buse': 'اختيار الفوهة',
    'Paramètres du spray': 'معاملات الرش',
    'Paramètres du gaz': 'معاملات الغاز',
    'Paramètres du liquide': 'معاملات السائل',
    'Réinitialiser les paramètres': 'إعادة تعيين المعاملات',
    'Type de buse': 'نوع الفوهة',
    'Cône creux': 'مخروط مجوف',
    'Distribution étroite, bon pour l\'uniformité': 'توزيع ضيق، جيد للتوحيد',
    'Cône plein': 'مخروط ممتلئ',
    'Distribution plus large, meilleure couverture': 'توزيع أوسع، تغطية أفضل',
    'Jet plat': 'نفاثة مسطحة',
    'Distribution large, bon pour les grandes surfaces': 'توزيع واسع، جيد للسطح الكبير',
    'Spirale': 'حلزون',
    'Distribution très étroite, excellente atomisation': 'توزيع ضيق جداً، تذرية ممتازة',
    'Pression (bar)': 'الضغط (بار)',
    'Débit (L/min)': 'معدل التدفق (لتر/دقيقة)',
    'Diamètre moyen (m)': 'القطر المتوسط (م)',
    'Indice de distribution (n)': 'مؤشر التوزيع (n)',
    'Température du gaz (K)': 'درجة حرارة الغاز (K)',
    'Vitesse du gaz (m/s)': 'سرعة الغاز (م/ث)',
    'Vitesse des gouttes initiale (m/s)': 'السرعة الأولية للقطرات (م/ث)',
    'Température du liquide (K)': 'درجة حرارة السائل (K)',
    'Caractéristiques calculées': 'الخصائص المحسوبة',
    'Qualité du spray': 'جودة الرش',
    'Hauteur minimale': 'الارتفاع الأدنى',
    'Vitesse des gouttes': 'سرعة القطرات',
    'Angle de spray': 'زاوية الرش',
    'Atomisation': 'التذرية',
    'Uniformité': 'التوحيد',
    'Couverture': 'التغطية',
    'Excellente': 'ممتاز',
    'Bonne': 'جيد',
    'Moyenne': 'متوسط',
    'Très uniforme': 'موحد جداً',
    'Uniforme': 'موحد',
    'Moins uniforme': 'أقل توحيداً',
    'Large couverture': 'تغطية واسعة',
    'Couverture moyenne': 'تغطية متوسطة',
    'Couverture concentrée': 'تغطية مركزة',
    'Erreur lors du calcul. Vérifiez les paramètres d\'entrée.': 'خطأ أثناء الحساب. تحقق من معاملات الإدخال.',
    'COOLINGTOWER Image': 'صورة برج التبريد',
    'Flue gases': 'غازات المداخن',
    'Pollutant Emissions': 'انبعاثات الملوثات',
    'Design': 'التصميم',
    'Opex': 'Opex',
    'pompe': 'مضخة',
    'Réinitialiser': 'إعادة تعيين',
    'Enregistrer': 'حفظ',
    'Annuler': 'إلغاء',
    'Oui': 'نعم',
    'Non': 'لا',
    'Confirmer': 'تأكيد',
    'Supprime': 'حذف',
  },
};