// RK_traduction.js
export const translations = {
  fr: {
    // Libellés des paramètres de l'onglet Design (Display_design)
    pressionAeraulique: 'Pression aéraulique',
    pdcMmCE: 'pdc mmCE',
    diametreInterne: 'Diamètre interne',
    diametreExterne: 'Diamètre externe',
    longueur: 'longueur',
    pente: 'Pente',
    nombreTours: 'Nombre de tours',
    hauteurDechets: 'Hauteur des déchets',
    masseVolumiqueDechets: 'Masse volumique des déchets',
    debitDechetsSolides: 'Débit des déchets solides',
    debitDechetsLiquides: 'Débit des déchets liquides',
    typeCombustible: 'Type de combustible',
    typeAtomisation: "Type d'atomisation",
    typeEau: "Type d'eau",
    debitEau: "Débit d'eau",
    temperatureEntree: "Température d'entrée",
    temperatureSortie: 'Température de sortie',
    epaisseurRefractaire: 'Épaisseur du réfractaire',
    temperaturePeau: 'Température de la peau',
    dtRefroidissement: 'DT refroidissement',
    // Dimensionnement SCC
    debitHumideFumees: 'Débit humide des fumées',
    temperatureSCC: 'Température SCC',
    diametreSCC: 'Diamètre SCC',
    tempsSejourDesire: 'Temps de séjour désiré',
    // Brûleurs SCC
    typeCombustibleSCC: 'Type de combustible',
    typeAtomisationSCC: "Type d'atomisation",
    // Conso extracteur
    nbTrappes: 'Nombre de trappes',
    puissanceUnite: 'Puissance par unité',
    masseImbrulees: 'Masse des imbrûlées',
    typeCamion: 'Type de camion',
    distance: 'Distance',
    // Conso ventilateur air combustion
    debitVentilateur: 'Débit ventilateur',
    rendementVentilateur: 'Rendement ventilateur',
    // Eau évaporée
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Température des fumées',
    emissiviteFume: 'Émissivité des fumées',
    teauExtracteur: "Température d'eau extracteur",
    // Design results (RK) — labels des tableaux de résultats
    dr_ratioLD: 'Rapport L/D',
    dr_puissanceFour: 'Puissance du four [MW]',
    dr_vitesseFumees: 'Vitesse des fumées [m/s]',
    dr_penteMmM: 'Pente [mm/m]',
    dr_rayonFour: 'Rayon du four [m]',
    dr_tempsSejourSullivan: 'Temps de séjour (Sullivan) [min]',
    dr_tauxRemplissage: 'Taux de remplissage du four [%]',
    dr_consoElecRotation: 'Conso élec mise en rotation [kW]',
    dr_debitDechetsLiquidesKgh: 'Débit déchets liquides [kg/h]',
    dr_puissanceBruleur: 'Puissance brûleur [MW]',
    dr_flammePilote: 'Flamme pilote [kW]',
    dr_nombreLances: 'Nombre de lances',
    dr_nombreLancesBackup: 'Nombre de lances backup',
    dr_volumeAir: "Volume d'air [Nm³/h]",
    dr_volumeVapeur: 'Volume de vapeur [t/h]',
    dr_consoElecAirCo: 'Conso élec air combustion [kW]',
    dr_perteEau: 'Perte en eau [m³/h]',
    dr_enthalpieRefroidissement: 'Enthalpie de refroidissement [MW]',
    dr_puissancePompe: 'Puissance pompe circulation eau [kW]',
    dr_surfaceExtFour: 'Surface extérieure du four [m²]',
    dr_pertesRad: 'Pertes thermiques radiatives [MW]',
    dr_pertesConv: 'Pertes thermiques convectives [MW]',
    dr_pertesTotales: 'Pertes thermiques totales [MW]',
    dr_partPertes: 'Part des pertes thermiques [%]',
    dr_pertesRadVirole: 'Pertes radiatives virole [MW]',
    dr_pertesConvVirole: 'Pertes convectives virole [MW]',
    dr_pertesConvViroleTot: 'Pertes convectives virole totales [MW]',
    dr_consoElecVirole: 'Conso élec refroidissement virole [kW]',
    dr_nombreVentilateurs: 'Nombre de ventilateurs',
    dr_debitFumeesM3h: 'Débit des fumées [m³/h]',
    dr_hauteurSCC: 'Hauteur de la SCC [m]',
    dr_puissanceBruleurSCC: 'Puissance du brûleur SCC [MW]',
    dr_puissanceFlammePilote: 'Puissance de la flamme pilote [kW]',
    dr_nombreLancesNb: 'Nombre de lances',
    dr_nombreLancesBackupNb: 'Nombre de lances back-up',
    dr_volumeAirAtomisation: 'Volume air atomisation [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Volume vapeur atomisation [t/h]',
    dr_tempParoiSCC: 'Température paroi SCC [°C]',
    dr_surfaceSCC: 'Surface SCC [m²]',
    dr_pthRadSCC: 'Pertes radiatives SCC [MW]',
    dr_pthConvSCC: 'Pertes convectives SCC [MW]',
    dr_pthTotSCC: 'Pertes totales SCC [MW]',
    dr_consoElecExtracteur: 'Consommation électrique extracteur [kW]',
    dr_masseImbruleesKgh: 'Masse des imbrûlées [kg/h]',
    dr_co2Transport: 'CO₂ transport [kg/km]',
    dr_coutTransport: 'Coût transport [€/km]',
    dr_co2TransportTotal: 'CO₂ transport total [kg]',
    dr_coutTransportTotal: 'Coût transport total [€]',
    dr_consoElecVentiloComb: 'Conso élec ventilateur combustion [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Température des fumées [°C]',
    dr_emissiviteFume: 'Émissivité des fumées',
    dr_teauExtracteur: "Température d'eau extracteur [°C]",
    dr_sEchange: "Surface d'échange [m²]",
    dr_coeffA: 'Coefficient a',
    dr_coeffB: 'Coefficient b',
    dr_coeffC: 'Coefficient c',
    dr_coeffBmaj: 'Coefficient B',
    dr_coeffCmaj: 'Coefficient C',
    dr_facteurF: 'Facteur de forme F',
    dr_fluxRadiatif: 'Flux radiatif [kW]',
    dr_eauEvapExtracteur: 'Eau évaporée extracteur [kg/h]',
    dr_pOutMmCE: 'Pression de sortie [mmCE]',

    // Main navigation
    title: 'Configuration du Four Rotatif et SCC',
    combustionParameters: 'Paramètres de combustion',
    flueGases: 'Gaz de combustion',
    pollutantEmissions: 'Émissions polluantes',
    design: 'Conception',
    opex: 'Opex',
    backToFlow: 'Retour au flux',
    sendData: 'Envoyer les données',
    rapport: 'Rapport',
    
    // Flue Gas Parameters (2_Flue_gas.jsx)
    calculationParameters: 'Paramètres de calcul',
    calculatedParameters: 'Paramètres calculés',
    combustionAirComposition: 'Composition de l\'air de combustion',
    atStoichiometry: 'À la stœchiométrie',
    atAdiabaticity: 'À l\'adiabaticité',
    combustionAirTotal: 'Air de combustion total',
    flueGasComposition: 'Composition des gaz de combustion',
    flueGasAtStoichiometry: 'Gaz de combustion à la stœchiométrie',
    outputFlueGasWithoutWater: 'Gaz de combustion en sortie sans eau de l\'extracteur',
    outputFlueGasWithWater: 'Gaz de combustion en sortie avec eau de l\'extracteur',
    resetValues: 'Remettre à zéro',
    export: 'Exporter',
    
    // Parameter labels
    flueGasTemperatureOutlet: 'Température de sortie des gaz de combustion [°C]',
    airFactor: 'Facteur d\'air',
    combustionAirTemperature: 'Température de l\'air de combustion [°C]',
    wasteTemperature: 'Température des déchets [°C]',
    steamWaterTemperature: 'Température de l\'eau vapeur',
    estimatedThermalLosses: 'Pertes thermiques estimées [%]',
    airPreheatingPart: 'Partie préchauffage d\'air [%]',
    airPreheatingTemperature: 'Température de préchauffage d\'air [°C]',
    airRelativeMoisture: 'Humidité relative de l\'air [%]',
    waterVaporizedFromExtractor: 'Eau vaporisée de l\'extracteur [kg/h]',
    
    // Calculated parameters
    airStoechio: 'Air stœchiométrique [Kmole]',
    calculatedTemperature: 'Température calculée [°C]',
    waterContent: 'Teneur en eau [kg/Nm3]',
    hSystem: 'H_système',
    airFactorCalculated: 'Facteur d\'air calculé',

    // Combustion Parameters (1_CombustionParameters.jsx)
    resetDefaultValues: 'Réinitialiser les valeurs par défaut',
    mass: 'Masse [kg/h]',
    wasteFlow: 'Débit de déchets [kg/h]',
    flueGasFlowWet: 'Débit de gaz humide [Nm3/h]',
    flueGasFlowDry: 'Débit de gaz sec [Nm3/h]',
    o2Calculated: 'O2 calculé [%]',
    inertMass: 'Masse inerte [kg/h]',

    // Pollutant Emissions (3_Pollutant_Emission.jsx)
    mercuryTreatmentThreshold: 'Seuil de traitement du mercure [micro g/Nm3]',
    noxIn: 'NOx EN [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Teneur en cendres volantes [g/Nm3]',
    siccityBottomAsh: 'Siccité des mâchefers [%]',
    o2Ref: 'O2 réf [%]',
    sncr: 'SNCR (Réduction catalytique sélective)',
    sncrtEnabled: 'SNCR activé',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Stœchiométrie',
    mercuryTreatment: 'Traitement du mercure',
    hgTreatmentEnabled: 'Traitement Hg activé',
    brHgRatio: 'Rapport Br/Hg',
    pollutantTreatmentTable: 'Tableau de traitement des polluants',
    pollutant: 'Polluant',
    reactif: 'Réactif',
    massInput: 'Masse entrée',
    efficiency: 'Efficacité (%)',
    stoechCoeff: 'Coeff. Stœch',
    massOutput: 'Masse sortie',
    massResidue: 'Masse résidu',
    massReactif: 'Masse réactif',
    massReduced: 'Masse abattue',
    inputFlueGas: 'Gaz de combustion en entrée',
    outputFlueGas: 'Gaz de combustion en sortie',
    bottomAshesCalculated: 'Mâchefers calculés',
    bottomAsh: 'Mâchefers [kg/h]',
    bottomAshWet: 'Mâchefers humides [kg/h]',
    flyAsh: 'Cendres volantes [kg/h]',
    nh3Consumption: 'Consommation NH3 [kg/h]',
    hgMass: 'Masse Hg [kg/h]',
    bromideConsumption: 'Consommation bromure [kg/h]',

    // Design (4_RK_Design.jsx)
    aeraulicPressureLoss: 'Perte de charge aéraulique',
    thermicalLossParameters: 'Paramètres pertes thermiques du four',
    rotaryKilnDesign: 'Conception du four rotatif',
    lanceEstimation: 'Estimation du nombre de lances sur la facade',
    facadeCooling: 'Paramètres du refroidissement de la facade',
    facadeThermicalLosses: 'Paramètres pertes thermiques du four',
    shellCooling: 'Refroidissement de la virole',
    sccDimensioning: 'Dimensionnement de la SCC',
    sccBurners: 'Brûleurs de la SCC',
    sccThermicalLosses: 'Estimation des pertes thermiques SCC',
    extractorConsumption: 'Estimation consommation extracteur',
    combustionAirFan: 'Estimation consommation ventilateur air combustion',
    extractorWaterEvaporation: 'Estimation eau évaporée extracteur',
    warningSlope: '⚠️ Attention : La pente du four dépasse la limite recommandée (2-5°)',
    warningFillRate: '⚠️ Attention : Le taux de remplissage dépasse la limite recommandée (max 5%)',
    warningVelocity: '⚠️ Attention : La vitesse des fumées dans la SCC dépasse la limite recommandée de 3 m/s',
  },
  
  en: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Aeraulic pressure',
    pdcMmCE: 'Pressure loss mmCE',
    diametreInterne: 'Inner diameter',
    diametreExterne: 'Outer diameter',
    longueur: 'Length',
    pente: 'Slope',
    nombreTours: 'Number of turns',
    hauteurDechets: 'Waste height',
    masseVolumiqueDechets: 'Waste density',
    debitDechetsSolides: 'Solid waste flow',
    debitDechetsLiquides: 'Liquid waste flow',
    typeCombustible: 'Fuel type',
    typeAtomisation: 'Atomization type',
    typeEau: 'Water type',
    debitEau: 'Water flow',
    temperatureEntree: 'Inlet temperature',
    temperatureSortie: 'Outlet temperature',
    epaisseurRefractaire: 'Refractory thickness',
    temperaturePeau: 'Skin temperature',
    dtRefroidissement: 'Cooling DT',
    debitHumideFumees: 'Wet flue gas flow',
    temperatureSCC: 'SCC temperature',
    diametreSCC: 'SCC diameter',
    tempsSejourDesire: 'Desired residence time',
    typeCombustibleSCC: 'Fuel type',
    typeAtomisationSCC: 'Atomization type',
    nbTrappes: 'Number of hatches',
    puissanceUnite: 'Power per unit',
    masseImbrulees: 'Unburnt mass',
    typeCamion: 'Truck type',
    distance: 'Distance',
    debitVentilateur: 'Fan flow',
    rendementVentilateur: 'Fan efficiency',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Flue gas temperature',
    emissiviteFume: 'Flue gas emissivity',
    teauExtracteur: 'Extractor water temperature',
    // Design results (RK)
    dr_ratioLD: 'L/D ratio',
    dr_puissanceFour: 'Kiln power [MW]',
    dr_vitesseFumees: 'Flue gas velocity [m/s]',
    dr_penteMmM: 'Slope [mm/m]',
    dr_rayonFour: 'Kiln radius [m]',
    dr_tempsSejourSullivan: 'Residence time (Sullivan) [min]',
    dr_tauxRemplissage: 'Kiln fill rate [%]',
    dr_consoElecRotation: 'Rotation power consumption [kW]',
    dr_debitDechetsLiquidesKgh: 'Liquid waste flow [kg/h]',
    dr_puissanceBruleur: 'Burner power [MW]',
    dr_flammePilote: 'Pilot flame [kW]',
    dr_nombreLances: 'Number of lances',
    dr_nombreLancesBackup: 'Number of backup lances',
    dr_volumeAir: 'Air volume [Nm³/h]',
    dr_volumeVapeur: 'Steam volume [t/h]',
    dr_consoElecAirCo: 'Combustion air power [kW]',
    dr_perteEau: 'Water loss [m³/h]',
    dr_enthalpieRefroidissement: 'Cooling enthalpy [MW]',
    dr_puissancePompe: 'Water circulation pump power [kW]',
    dr_surfaceExtFour: 'Kiln outer surface [m²]',
    dr_pertesRad: 'Radiative thermal losses [MW]',
    dr_pertesConv: 'Convective thermal losses [MW]',
    dr_pertesTotales: 'Total thermal losses [MW]',
    dr_partPertes: 'Thermal losses share [%]',
    dr_pertesRadVirole: 'Shell radiative losses [MW]',
    dr_pertesConvVirole: 'Shell convective losses [MW]',
    dr_pertesConvViroleTot: 'Total shell convective losses [MW]',
    dr_consoElecVirole: 'Shell cooling power [kW]',
    dr_nombreVentilateurs: 'Number of fans',
    dr_debitFumeesM3h: 'Flue gas flow [m³/h]',
    dr_hauteurSCC: 'SCC height [m]',
    dr_puissanceBruleurSCC: 'SCC burner power [MW]',
    dr_puissanceFlammePilote: 'Pilot flame power [kW]',
    dr_nombreLancesNb: 'Number of lances',
    dr_nombreLancesBackupNb: 'Number of backup lances',
    dr_volumeAirAtomisation: 'Atomization air volume [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Atomization steam volume [t/h]',
    dr_tempParoiSCC: 'SCC wall temperature [°C]',
    dr_surfaceSCC: 'SCC surface [m²]',
    dr_pthRadSCC: 'SCC radiative losses [MW]',
    dr_pthConvSCC: 'SCC convective losses [MW]',
    dr_pthTotSCC: 'SCC total losses [MW]',
    dr_consoElecExtracteur: 'Extractor power consumption [kW]',
    dr_masseImbruleesKgh: 'Unburnt mass [kg/h]',
    dr_co2Transport: 'CO₂ transport [kg/km]',
    dr_coutTransport: 'Transport cost [€/km]',
    dr_co2TransportTotal: 'Total CO₂ transport [kg]',
    dr_coutTransportTotal: 'Total transport cost [€]',
    dr_consoElecVentiloComb: 'Combustion fan power [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Flue gas temperature [°C]',
    dr_emissiviteFume: 'Flue gas emissivity',
    dr_teauExtracteur: 'Extractor water temperature [°C]',
    dr_sEchange: 'Heat exchange area [m²]',
    dr_coeffA: 'Coefficient a',
    dr_coeffB: 'Coefficient b',
    dr_coeffC: 'Coefficient c',
    dr_coeffBmaj: 'Coefficient B',
    dr_coeffCmaj: 'Coefficient C',
    dr_facteurF: 'View factor F',
    dr_fluxRadiatif: 'Radiative flux [kW]',
    dr_eauEvapExtracteur: 'Extractor evaporated water [kg/h]',
    dr_pOutMmCE: 'Outlet pressure [mmCE]',

    // Main navigation
    title: 'Rotary Kiln and SCC Configuration',
    combustionParameters: 'Combustion Parameters',
    flueGases: 'Flue gases',
    pollutantEmissions: 'Pollutant Emissions',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Back to Flow',
    sendData: 'Send Data',
    rapport: 'Report',
    
    // Flue Gas Parameters
    calculationParameters: 'Calculation parameters',
    calculatedParameters: 'Calculated parameters',
    combustionAirComposition: 'Combustion air composition',
    atStoichiometry: 'At the stoichiometry',
    atAdiabaticity: 'At the adiabaticity',
    combustionAirTotal: 'Combustion air total',
    flueGasComposition: 'Flue gas composition',
    flueGasAtStoichiometry: 'Flue gas at the stoichiometry',
    outputFlueGasWithoutWater: 'Output flue gas without water from extractor',
    outputFlueGasWithWater: 'Output flue gas with water from extractor',
    resetValues: 'Reset values',
    export: 'Export',
    
    // Parameter labels
    flueGasTemperatureOutlet: 'Flue gas temperature outlet [°C]',
    airFactor: 'Air factor',
    combustionAirTemperature: 'Combustion Air Temperature [°C]',
    wasteTemperature: 'Waste Temperature [°C]',
    steamWaterTemperature: 'Steam water temperature',
    estimatedThermalLosses: 'Estimated thermal Losses [%]',
    airPreheatingPart: 'Air preheating part [%]',
    airPreheatingTemperature: 'Air preheating temperature [°C]',
    airRelativeMoisture: 'Air Relative Moisture [%]',
    waterVaporizedFromExtractor: 'Water vaporized from extractor [kg/h]',
    
    // Calculated parameters
    airStoechio: 'Air Stoechio [Kmole]',
    calculatedTemperature: 'Calculated temperature [°C]',
    waterContent: 'Water Content [kg/Nm3]',
    hSystem: 'H_system',
    airFactorCalculated: 'Air factor calculated',

    // Combustion Parameters
    resetDefaultValues: 'Reset default values',
    mass: 'Mass [kg/h]',
    wasteFlow: 'Waste Flow [kg/h]',
    flueGasFlowWet: 'Flue gas Flow Wet [Nm3/h]',
    flueGasFlowDry: 'Flue gas Flow Dry [Nm3/h]',
    o2Calculated: 'O2 calculated [%]',
    inertMass: 'Inert mass [kg/h]',

    // Pollutant Emissions
    mercuryTreatmentThreshold: 'Mercury treatment threshold [micro g/Nm3]',
    noxIn: 'NOx IN [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Fly ashes content [g/Nm3]',
    siccityBottomAsh: 'Siccity bottom ash [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Selective Non-Catalytic Reduction)',
    sncrtEnabled: 'SNCR enabled',
    noxLimit: 'NOx limit [mg/Nm3]',
    stoichiometry: 'Stoichiometry',
    mercuryTreatment: 'Mercury Treatment',
    hgTreatmentEnabled: 'Hg treatment enabled',
    brHgRatio: 'Br/Hg ratio',
    pollutantTreatmentTable: 'Pollutant Treatment Table',
    pollutant: 'Pollutant',
    reactif: 'Reagent',
    massInput: 'Mass input',
    efficiency: 'Efficiency (%)',
    stoechCoeff: 'Stoech. Coeff',
    massOutput: 'Mass output',
    massResidue: 'Mass residue',
    massReactif: 'Reagent mass',
    massReduced: 'Mass reduced',
    inputFlueGas: 'Input flue gas',
    outputFlueGas: 'Output flue gas',
    bottomAshesCalculated: 'Bottom ashes calculated',
    bottomAsh: 'Bottom ash [kg/h]',
    bottomAshWet: 'Bottom ash wet [kg/h]',
    flyAsh: 'Fly ash [kg/h]',
    nh3Consumption: 'NH3 consumption [kg/h]',
    hgMass: 'Hg mass [kg/h]',
    bromideConsumption: 'Bromide consumption [kg/h]',

    // Design
    aeraulicPressureLoss: 'Aeraulic pressure loss',
    thermicalLossParameters: 'Thermal loss parameters',
    rotaryKilnDesign: 'Rotary Kiln Design',
    lanceEstimation: 'Lance estimation on facade',
    facadeCooling: 'Facade cooling parameters',
    facadeThermicalLosses: 'Facade thermal losses parameters',
    shellCooling: 'Shell cooling',
    sccDimensioning: 'SCC dimensioning',
    sccBurners: 'SCC burners',
    sccThermicalLosses: 'SCC thermal losses estimation',
    extractorConsumption: 'Extractor consumption estimation',
    combustionAirFan: 'Combustion air fan consumption estimation',
    extractorWaterEvaporation: 'Extractor water evaporation estimation',
    warningSlope: '⚠️ Warning: Kiln slope exceeds recommended limit (2-5°)',
    warningFillRate: '⚠️ Warning: Fill rate exceeds recommended limit (max 5%)',
    warningVelocity: '⚠️ Warning: Flue gas velocity in SCC exceeds recommended limit of 3 m/s',
  },

  es: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Presión aeráulica',
    pdcMmCE: 'Pérdida de carga mmCE',
    diametreInterne: 'Diámetro interno',
    diametreExterne: 'Diámetro externo',
    longueur: 'Longitud',
    pente: 'Pendiente',
    nombreTours: 'Número de vueltas',
    hauteurDechets: 'Altura de residuos',
    masseVolumiqueDechets: 'Densidad de residuos',
    debitDechetsSolides: 'Caudal de residuos sólidos',
    debitDechetsLiquides: 'Caudal de residuos líquidos',
    typeCombustible: 'Tipo de combustible',
    typeAtomisation: 'Tipo de atomización',
    typeEau: 'Tipo de agua',
    debitEau: 'Caudal de agua',
    temperatureEntree: 'Temperatura de entrada',
    temperatureSortie: 'Temperatura de salida',
    epaisseurRefractaire: 'Espesor del refractario',
    temperaturePeau: 'Temperatura de la piel',
    dtRefroidissement: 'DT enfriamiento',
    debitHumideFumees: 'Caudal húmedo de gases',
    temperatureSCC: 'Temperatura SCC',
    diametreSCC: 'Diámetro SCC',
    tempsSejourDesire: 'Tiempo de residencia deseado',
    typeCombustibleSCC: 'Tipo de combustible',
    typeAtomisationSCC: 'Tipo de atomización',
    nbTrappes: 'Número de trampas',
    puissanceUnite: 'Potencia por unidad',
    masseImbrulees: 'Masa de inquemados',
    typeCamion: 'Tipo de camión',
    distance: 'Distancia',
    debitVentilateur: 'Caudal del ventilador',
    rendementVentilateur: 'Rendimiento del ventilador',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Temperatura de gases',
    emissiviteFume: 'Emisividad de los gases',
    teauExtracteur: 'Temperatura del agua extractor',
    // Design results (RK)
    dr_ratioLD: 'Relación L/D',
    dr_puissanceFour: 'Potencia del horno [MW]',
    dr_vitesseFumees: 'Velocidad de gases [m/s]',
    dr_penteMmM: 'Pendiente [mm/m]',
    dr_rayonFour: 'Radio del horno [m]',
    dr_tempsSejourSullivan: 'Tiempo de residencia (Sullivan) [min]',
    dr_tauxRemplissage: 'Tasa de llenado del horno [%]',
    dr_consoElecRotation: 'Consumo eléctrico de rotación [kW]',
    dr_debitDechetsLiquidesKgh: 'Caudal de residuos líquidos [kg/h]',
    dr_puissanceBruleur: 'Potencia del quemador [MW]',
    dr_flammePilote: 'Llama piloto [kW]',
    dr_nombreLances: 'Número de lanzas',
    dr_nombreLancesBackup: 'Número de lanzas de reserva',
    dr_volumeAir: 'Volumen de aire [Nm³/h]',
    dr_volumeVapeur: 'Volumen de vapor [t/h]',
    dr_consoElecAirCo: 'Potencia aire de combustión [kW]',
    dr_perteEau: 'Pérdida de agua [m³/h]',
    dr_enthalpieRefroidissement: 'Entalpía de enfriamiento [MW]',
    dr_puissancePompe: 'Potencia bomba circulación agua [kW]',
    dr_surfaceExtFour: 'Superficie exterior del horno [m²]',
    dr_pertesRad: 'Pérdidas térmicas radiativas [MW]',
    dr_pertesConv: 'Pérdidas térmicas convectivas [MW]',
    dr_pertesTotales: 'Pérdidas térmicas totales [MW]',
    dr_partPertes: 'Proporción de pérdidas térmicas [%]',
    dr_pertesRadVirole: 'Pérdidas radiativas envolvente [MW]',
    dr_pertesConvVirole: 'Pérdidas convectivas envolvente [MW]',
    dr_pertesConvViroleTot: 'Pérdidas convectivas envolvente totales [MW]',
    dr_consoElecVirole: 'Consumo enfriamiento envolvente [kW]',
    dr_nombreVentilateurs: 'Número de ventiladores',
    dr_debitFumeesM3h: 'Caudal de gases [m³/h]',
    dr_hauteurSCC: 'Altura de la SCC [m]',
    dr_puissanceBruleurSCC: 'Potencia del quemador SCC [MW]',
    dr_puissanceFlammePilote: 'Potencia de la llama piloto [kW]',
    dr_nombreLancesNb: 'Número de lanzas',
    dr_nombreLancesBackupNb: 'Número de lanzas de reserva',
    dr_volumeAirAtomisation: 'Volumen aire atomización [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Volumen vapor atomización [t/h]',
    dr_tempParoiSCC: 'Temperatura pared SCC [°C]',
    dr_surfaceSCC: 'Superficie SCC [m²]',
    dr_pthRadSCC: 'Pérdidas radiativas SCC [MW]',
    dr_pthConvSCC: 'Pérdidas convectivas SCC [MW]',
    dr_pthTotSCC: 'Pérdidas totales SCC [MW]',
    dr_consoElecExtracteur: 'Consumo eléctrico extractor [kW]',
    dr_masseImbruleesKgh: 'Masa de inquemados [kg/h]',
    dr_co2Transport: 'CO₂ transporte [kg/km]',
    dr_coutTransport: 'Coste transporte [€/km]',
    dr_co2TransportTotal: 'CO₂ transporte total [kg]',
    dr_coutTransportTotal: 'Coste transporte total [€]',
    dr_consoElecVentiloComb: 'Consumo ventilador combustión [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Temperatura de gases [°C]',
    dr_emissiviteFume: 'Emisividad de los gases',
    dr_teauExtracteur: 'Temperatura del agua extractor [°C]',
    dr_sEchange: 'Superficie de intercambio [m²]',
    dr_coeffA: 'Coeficiente a',
    dr_coeffB: 'Coeficiente b',
    dr_coeffC: 'Coeficiente c',
    dr_coeffBmaj: 'Coeficiente B',
    dr_coeffCmaj: 'Coeficiente C',
    dr_facteurF: 'Factor de forma F',
    dr_fluxRadiatif: 'Flujo radiativo [kW]',
    dr_eauEvapExtracteur: 'Agua evaporada extractor [kg/h]',
    dr_pOutMmCE: 'Presión de salida [mmCE]',

    // Main navigation
    title: 'Configuración de Horno Rotativo y SCC',
    combustionParameters: 'Parámetros de combustión',
    flueGases: 'Gases de combustión',
    pollutantEmissions: 'Emisiones contaminantes',
    design: 'Diseño',
    opex: 'Opex',
    backToFlow: 'Volver al flujo',
    sendData: 'Enviar datos',
    rapport: 'Informe',
    
    calculationParameters: 'Parámetros de cálculo',
    calculatedParameters: 'Parámetros calculados',
    combustionAirComposition: 'Composición del aire de combustión',
    atStoichiometry: 'En la estequiometría',
    atAdiabaticity: 'En la adiabaticidad',
    combustionAirTotal: 'Aire de combustión total',
    flueGasComposition: 'Composición de gases de combustión',
    flueGasAtStoichiometry: 'Gases de combustión en la estequiometría',
    outputFlueGasWithoutWater: 'Gases de combustión de salida sin agua del extractor',
    outputFlueGasWithWater: 'Gases de combustión de salida con agua del extractor',
    resetValues: 'Restablecer valores',
    export: 'Exportar',
    
    flueGasTemperatureOutlet: 'Temperatura de salida de gases de combustión [°C]',
    airFactor: 'Factor de aire',
    combustionAirTemperature: 'Temperatura del aire de combustión [°C]',
    wasteTemperature: 'Temperatura de residuos [°C]',
    steamWaterTemperature: 'Temperatura del agua vapor',
    estimatedThermalLosses: 'Pérdidas térmicas estimadas [%]',
    airPreheatingPart: 'Parte de precalentamiento de aire [%]',
    airPreheatingTemperature: 'Temperatura de precalentamiento de aire [°C]',
    airRelativeMoisture: 'Humedad relativa del aire [%]',
    waterVaporizedFromExtractor: 'Agua vaporizada del extractor [kg/h]',
    
    airStoechio: 'Aire estequiométrico [Kmole]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Contenido de agua [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Factor de aire calculado',

    resetDefaultValues: 'Restablecer valores predeterminados',
    mass: 'Masa [kg/h]',
    wasteFlow: 'Flujo de residuos [kg/h]',
    flueGasFlowWet: 'Flujo de gas húmedo [Nm3/h]',
    flueGasFlowDry: 'Flujo de gas seco [Nm3/h]',
    o2Calculated: 'O2 calculado [%]',
    inertMass: 'Masa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Umbral de tratamiento de mercurio [micro g/Nm3]',
    noxIn: 'NOx ENTRADA [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Contenido de cenizas volantes [g/Nm3]',
    siccityBottomAsh: 'Sequedad de escorias [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Reducción Catalítica Selectiva)',
    sncrtEnabled: 'SNCR activado',
    noxLimit: 'Límite NOx [mg/Nm3]',
    stoichiometry: 'Estequiometría',
    mercuryTreatment: 'Tratamiento de mercurio',
    hgTreatmentEnabled: 'Tratamiento Hg activado',
    brHgRatio: 'Relación Br/Hg',
    pollutantTreatmentTable: 'Tabla de tratamiento de contaminantes',
    pollutant: 'Contaminante',
    reactif: 'Reactivo',
    massInput: 'Masa entrada',
    efficiency: 'Eficiencia (%)',
    stoechCoeff: 'Coef. Estequiom.',
    massOutput: 'Masa salida',
    massResidue: 'Masa residuo',
    massReactif: 'Masa reactivo',
    massReduced: 'Masa reducida',
    inputFlueGas: 'Gas de combustión de entrada',
    outputFlueGas: 'Gas de combustión de salida',
    bottomAshesCalculated: 'Escorias calculadas',
    bottomAsh: 'Escorias [kg/h]',
    bottomAshWet: 'Escorias húmedas [kg/h]',
    flyAsh: 'Cenizas volantes [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Masa Hg [kg/h]',
    bromideConsumption: 'Consumo de bromuro [kg/h]',

    aeraulicPressureLoss: 'Pérdida de carga aeráulica',
    thermicalLossParameters: 'Parámetros de pérdidas térmicas',
    rotaryKilnDesign: 'Diseño de horno rotativo',
    lanceEstimation: 'Estimación de lanzas en fachada',
    facadeCooling: 'Parámetros de refrigeración de fachada',
    facadeThermicalLosses: 'Parámetros de pérdidas térmicas de fachada',
    shellCooling: 'Refrigeración de carcasa',
    sccDimensioning: 'Dimensionamiento SCC',
    sccBurners: 'Quemadores SCC',
    sccThermicalLosses: 'Estimación de pérdidas térmicas SCC',
    extractorConsumption: 'Estimación consumo extractor',
    combustionAirFan: 'Estimación consumo ventilador aire combustión',
    extractorWaterEvaporation: 'Estimación evaporación agua extractor',
    warningSlope: '⚠️ Advertencia: La pendiente del horno supera el límite recomendado (2-5°)',
    warningFillRate: '⚠️ Advertencia: La tasa de llenado supera el límite recomendado (máx 5%)',
    warningVelocity: '⚠️ Advertencia: La velocidad del gas en SCC supera el límite recomendado de 3 m/s',
  },

  de: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Aeraulischer Druck',
    pdcMmCE: 'Druckverlust mmCE',
    diametreInterne: 'Innendurchmesser',
    diametreExterne: 'Außendurchmesser',
    longueur: 'Länge',
    pente: 'Neigung',
    nombreTours: 'Anzahl Umdrehungen',
    hauteurDechets: 'Abfallhöhe',
    masseVolumiqueDechets: 'Abfalldichte',
    debitDechetsSolides: 'Feststoffabfall-Durchsatz',
    debitDechetsLiquides: 'Flüssigabfall-Durchsatz',
    typeCombustible: 'Brennstofftyp',
    typeAtomisation: 'Zerstäubungstyp',
    typeEau: 'Wassertyp',
    debitEau: 'Wasserdurchsatz',
    temperatureEntree: 'Eintrittstemperatur',
    temperatureSortie: 'Austrittstemperatur',
    epaisseurRefractaire: 'Feuerfest-Dicke',
    temperaturePeau: 'Oberflächentemperatur',
    dtRefroidissement: 'Kühl-DT',
    debitHumideFumees: 'Feuchter Rauchgasstrom',
    temperatureSCC: 'SCC-Temperatur',
    diametreSCC: 'SCC-Durchmesser',
    tempsSejourDesire: 'Gewünschte Verweilzeit',
    typeCombustibleSCC: 'Brennstofftyp',
    typeAtomisationSCC: 'Zerstäubungstyp',
    nbTrappes: 'Anzahl Klappen',
    puissanceUnite: 'Leistung pro Einheit',
    masseImbrulees: 'Unverbrannte Masse',
    typeCamion: 'LKW-Typ',
    distance: 'Entfernung',
    debitVentilateur: 'Ventilatordurchsatz',
    rendementVentilateur: 'Ventilatorwirkungsgrad',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Rauchgastemperatur',
    emissiviteFume: 'Rauchgas-Emissionsgrad',
    teauExtracteur: 'Extraktor-Wassertemperatur',
    // Design results (RK)
    dr_ratioLD: 'L/D-Verhältnis',
    dr_puissanceFour: 'Ofenleistung [MW]',
    dr_vitesseFumees: 'Rauchgasgeschwindigkeit [m/s]',
    dr_penteMmM: 'Neigung [mm/m]',
    dr_rayonFour: 'Ofenradius [m]',
    dr_tempsSejourSullivan: 'Verweilzeit (Sullivan) [min]',
    dr_tauxRemplissage: 'Ofenfüllgrad [%]',
    dr_consoElecRotation: 'Stromverbrauch Drehung [kW]',
    dr_debitDechetsLiquidesKgh: 'Flüssigabfall-Durchsatz [kg/h]',
    dr_puissanceBruleur: 'Brennerleistung [MW]',
    dr_flammePilote: 'Pilotflamme [kW]',
    dr_nombreLances: 'Anzahl Lanzen',
    dr_nombreLancesBackup: 'Anzahl Reservelanzen',
    dr_volumeAir: 'Luftvolumen [Nm³/h]',
    dr_volumeVapeur: 'Dampfvolumen [t/h]',
    dr_consoElecAirCo: 'Leistung Verbrennungsluft [kW]',
    dr_perteEau: 'Wasserverlust [m³/h]',
    dr_enthalpieRefroidissement: 'Kühlenthalpie [MW]',
    dr_puissancePompe: 'Leistung Umwälzpumpe [kW]',
    dr_surfaceExtFour: 'Ofenaußenfläche [m²]',
    dr_pertesRad: 'Strahlungswärmeverluste [MW]',
    dr_pertesConv: 'Konvektive Wärmeverluste [MW]',
    dr_pertesTotales: 'Gesamte Wärmeverluste [MW]',
    dr_partPertes: 'Anteil Wärmeverluste [%]',
    dr_pertesRadVirole: 'Mantel-Strahlungsverluste [MW]',
    dr_pertesConvVirole: 'Mantel-Konvektionsverluste [MW]',
    dr_pertesConvViroleTot: 'Gesamte Mantel-Konvektionsverluste [MW]',
    dr_consoElecVirole: 'Leistung Mantelkühlung [kW]',
    dr_nombreVentilateurs: 'Anzahl Ventilatoren',
    dr_debitFumeesM3h: 'Rauchgasstrom [m³/h]',
    dr_hauteurSCC: 'SCC-Höhe [m]',
    dr_puissanceBruleurSCC: 'SCC-Brennerleistung [MW]',
    dr_puissanceFlammePilote: 'Leistung Pilotflamme [kW]',
    dr_nombreLancesNb: 'Anzahl Lanzen',
    dr_nombreLancesBackupNb: 'Anzahl Reservelanzen',
    dr_volumeAirAtomisation: 'Zerstäubungsluft-Volumen [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Zerstäubungsdampf-Volumen [t/h]',
    dr_tempParoiSCC: 'SCC-Wandtemperatur [°C]',
    dr_surfaceSCC: 'SCC-Fläche [m²]',
    dr_pthRadSCC: 'SCC-Strahlungsverluste [MW]',
    dr_pthConvSCC: 'SCC-Konvektionsverluste [MW]',
    dr_pthTotSCC: 'SCC-Gesamtverluste [MW]',
    dr_consoElecExtracteur: 'Stromverbrauch Austrag [kW]',
    dr_masseImbruleesKgh: 'Unverbrannte Masse [kg/h]',
    dr_co2Transport: 'CO₂ Transport [kg/km]',
    dr_coutTransport: 'Transportkosten [€/km]',
    dr_co2TransportTotal: 'CO₂ Transport gesamt [kg]',
    dr_coutTransportTotal: 'Transportkosten gesamt [€]',
    dr_consoElecVentiloComb: 'Leistung Verbrennungsventilator [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Rauchgastemperatur [°C]',
    dr_emissiviteFume: 'Rauchgas-Emissionsgrad',
    dr_teauExtracteur: 'Austrag-Wassertemperatur [°C]',
    dr_sEchange: 'Wärmeaustauschfläche [m²]',
    dr_coeffA: 'Koeffizient a',
    dr_coeffB: 'Koeffizient b',
    dr_coeffC: 'Koeffizient c',
    dr_coeffBmaj: 'Koeffizient B',
    dr_coeffCmaj: 'Koeffizient C',
    dr_facteurF: 'Sichtfaktor F',
    dr_fluxRadiatif: 'Strahlungsfluss [kW]',
    dr_eauEvapExtracteur: 'Verdampftes Wasser Austrag [kg/h]',
    dr_pOutMmCE: 'Austrittsdruck [mmCE]',

    // Main navigation
    title: 'Drehrohrofen und SCC Konfiguration',
    combustionParameters: 'Verbrennungsparameter',
    flueGases: 'Rauchgase',
    pollutantEmissions: 'Schadstoffemissionen',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Zurück zum Fluss',
    sendData: 'Daten senden',
    rapport: 'Bericht',
    
    calculationParameters: 'Berechnungsparameter',
    calculatedParameters: 'Berechnete Parameter',
    combustionAirComposition: 'Verbrennungsluftzusammensetzung',
    atStoichiometry: 'Bei der Stöchiometrie',
    atAdiabaticity: 'Bei der Adiabatik',
    combustionAirTotal: 'Verbrennungsluft gesamt',
    flueGasComposition: 'Rauchgaszusammensetzung',
    flueGasAtStoichiometry: 'Rauchgas bei der Stöchiometrie',
    outputFlueGasWithoutWater: 'Ausgangsrauchgas ohne Wasser aus Extraktor',
    outputFlueGasWithWater: 'Ausgangsrauchgas mit Wasser aus Extraktor',
    resetValues: 'Werte zurücksetzen',
    export: 'Exportieren',
    
    flueGasTemperatureOutlet: 'Rauchgas-Austrittstemperatur [°C]',
    airFactor: 'Luftfaktor',
    combustionAirTemperature: 'Verbrennungslufttemperatur [°C]',
    wasteTemperature: 'Abfalltemperatur [°C]',
    steamWaterTemperature: 'Dampfwassertemperatur',
    estimatedThermalLosses: 'Geschätzte Wärmeverluste [%]',
    airPreheatingPart: 'Luftvorwärmungsanteil [%]',
    airPreheatingTemperature: 'Luftvorwärmungstemperatur [°C]',
    airRelativeMoisture: 'Relative Luftfeuchtigkeit [%]',
    waterVaporizedFromExtractor: 'Verdampftes Wasser aus Extraktor [kg/h]',
    
    airStoechio: 'Stöchiometrische Luft [Kmole]',
    calculatedTemperature: 'Berechnete Temperatur [°C]',
    waterContent: 'Wassergehalt [kg/Nm3]',
    hSystem: 'H_System',
    airFactorCalculated: 'Berechneter Luftfaktor',

    resetDefaultValues: 'Standardwerte zurücksetzen',
    mass: 'Masse [kg/h]',
    wasteFlow: 'Abfallstrom [kg/h]',
    flueGasFlowWet: 'Feuchter Rauchgasstrom [Nm3/h]',
    flueGasFlowDry: 'Trockener Rauchgasstrom [Nm3/h]',
    o2Calculated: 'O2 berechnet [%]',
    inertMass: 'Inerte Masse [kg/h]',

    mercuryTreatmentThreshold: 'Quecksilberbehandlungsschwelle [micro g/Nm3]',
    noxIn: 'NOx EINGANG [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Flugaschegehalt [g/Nm3]',
    siccityBottomAsh: 'Trockenheit der Schlacke [%]',
    o2Ref: 'O2 Ref [%]',
    sncr: 'SNCR (Selektive Nicht-Katalytische Reduktion)',
    sncrtEnabled: 'SNCR aktiviert',
    noxLimit: 'NOx-Grenze [mg/Nm3]',
    stoichiometry: 'Stöchiometrie',
    mercuryTreatment: 'Quecksilberbehandlung',
    hgTreatmentEnabled: 'Hg-Behandlung aktiviert',
    brHgRatio: 'Br/Hg-Verhältnis',
    pollutantTreatmentTable: 'Schadstoffbehandlungstabelle',
    pollutant: 'Schadstoff',
    reactif: 'Reagenz',
    massInput: 'Eingangsmasse',
    efficiency: 'Wirkungsgrad (%)',
    stoechCoeff: 'Stöch. Koeff',
    massOutput: 'Ausgangsmasse',
    massResidue: 'Rückstandsmasse',
    massReactif: 'Reagenzmasse',
    massReduced: 'Reduzierte Masse',
    inputFlueGas: 'Eingangsrauchgas',
    outputFlueGas: 'Ausgangsrauchgas',
    bottomAshesCalculated: 'Berechnete Schlacke',
    bottomAsh: 'Schlacke [kg/h]',
    bottomAshWet: 'Feuchte Schlacke [kg/h]',
    flyAsh: 'Flugasche [kg/h]',
    nh3Consumption: 'NH3-Verbrauch [kg/h]',
    hgMass: 'Hg-Masse [kg/h]',
    bromideConsumption: 'Bromidverbrauch [kg/h]',

    aeraulicPressureLoss: 'Aeraulischer Druckverlust',
    thermicalLossParameters: 'Wärmeverlustparameter',
    rotaryKilnDesign: 'Drehrohrofen-Design',
    lanceEstimation: 'Lanzenschätzung an Fassade',
    facadeCooling: 'Fassadenkühlungsparameter',
    facadeThermicalLosses: 'Fassadenwärmeverlustparameter',
    shellCooling: 'Mantelkühlung',
    sccDimensioning: 'SCC-Dimensionierung',
    sccBurners: 'SCC-Brenner',
    sccThermicalLosses: 'SCC-Wärmeverlustschätzung',
    extractorConsumption: 'Extraktorverbrauchsschätzung',
    combustionAirFan: 'Verbrennungsluftgebläseverbrauchsschätzung',
    extractorWaterEvaporation: 'Extraktor-Wasserverdampfungsschätzung',
    warningSlope: '⚠️ Warnung: Ofenneigung überschreitet empfohlene Grenze (2-5°)',
    warningFillRate: '⚠️ Warnung: Füllrate überschreitet empfohlene Grenze (max 5%)',
    warningVelocity: '⚠️ Warnung: Rauchgasgeschwindigkeit in SCC überschreitet empfohlene Grenze von 3 m/s',
  },

  it: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Pressione aeraulica',
    pdcMmCE: 'Perdita di carico mmCE',
    diametreInterne: 'Diametro interno',
    diametreExterne: 'Diametro esterno',
    longueur: 'Lunghezza',
    pente: 'Pendenza',
    nombreTours: 'Numero di giri',
    hauteurDechets: 'Altezza rifiuti',
    masseVolumiqueDechets: 'Densità rifiuti',
    debitDechetsSolides: 'Portata rifiuti solidi',
    debitDechetsLiquides: 'Portata rifiuti liquidi',
    typeCombustible: 'Tipo di combustibile',
    typeAtomisation: 'Tipo di atomizzazione',
    typeEau: 'Tipo di acqua',
    debitEau: 'Portata acqua',
    temperatureEntree: 'Temperatura di ingresso',
    temperatureSortie: 'Temperatura di uscita',
    epaisseurRefractaire: 'Spessore del refrattario',
    temperaturePeau: 'Temperatura della pelle',
    dtRefroidissement: 'DT raffreddamento',
    debitHumideFumees: 'Portata umida fumi',
    temperatureSCC: 'Temperatura SCC',
    diametreSCC: 'Diametro SCC',
    tempsSejourDesire: 'Tempo di residenza desiderato',
    typeCombustibleSCC: 'Tipo di combustibile',
    typeAtomisationSCC: 'Tipo di atomizzazione',
    nbTrappes: 'Numero di portelli',
    puissanceUnite: 'Potenza per unità',
    masseImbrulees: 'Massa di incombusti',
    typeCamion: 'Tipo di camion',
    distance: 'Distanza',
    debitVentilateur: 'Portata ventilatore',
    rendementVentilateur: 'Rendimento ventilatore',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Temperatura fumi',
    emissiviteFume: 'Emissività fumi',
    teauExtracteur: 'Temperatura acqua estrattore',
    // Design results (RK)
    dr_ratioLD: 'Rapporto L/D',
    dr_puissanceFour: 'Potenza del forno [MW]',
    dr_vitesseFumees: 'Velocità dei fumi [m/s]',
    dr_penteMmM: 'Pendenza [mm/m]',
    dr_rayonFour: 'Raggio del forno [m]',
    dr_tempsSejourSullivan: 'Tempo di residenza (Sullivan) [min]',
    dr_tauxRemplissage: 'Grado di riempimento del forno [%]',
    dr_consoElecRotation: 'Consumo elettrico rotazione [kW]',
    dr_debitDechetsLiquidesKgh: 'Portata rifiuti liquidi [kg/h]',
    dr_puissanceBruleur: 'Potenza bruciatore [MW]',
    dr_flammePilote: 'Fiamma pilota [kW]',
    dr_nombreLances: 'Numero di lance',
    dr_nombreLancesBackup: 'Numero di lance di riserva',
    dr_volumeAir: "Volume d'aria [Nm³/h]",
    dr_volumeVapeur: 'Volume di vapore [t/h]',
    dr_consoElecAirCo: 'Potenza aria di combustione [kW]',
    dr_perteEau: "Perdita d'acqua [m³/h]",
    dr_enthalpieRefroidissement: 'Entalpia di raffreddamento [MW]',
    dr_puissancePompe: 'Potenza pompa circolazione acqua [kW]',
    dr_surfaceExtFour: 'Superficie esterna del forno [m²]',
    dr_pertesRad: 'Perdite termiche radiative [MW]',
    dr_pertesConv: 'Perdite termiche convettive [MW]',
    dr_pertesTotales: 'Perdite termiche totali [MW]',
    dr_partPertes: 'Quota perdite termiche [%]',
    dr_pertesRadVirole: 'Perdite radiative mantello [MW]',
    dr_pertesConvVirole: 'Perdite convettive mantello [MW]',
    dr_pertesConvViroleTot: 'Perdite convettive mantello totali [MW]',
    dr_consoElecVirole: 'Consumo raffreddamento mantello [kW]',
    dr_nombreVentilateurs: 'Numero di ventilatori',
    dr_debitFumeesM3h: 'Portata dei fumi [m³/h]',
    dr_hauteurSCC: 'Altezza della SCC [m]',
    dr_puissanceBruleurSCC: 'Potenza del bruciatore SCC [MW]',
    dr_puissanceFlammePilote: 'Potenza della fiamma pilota [kW]',
    dr_nombreLancesNb: 'Numero di lance',
    dr_nombreLancesBackupNb: 'Numero di lance di riserva',
    dr_volumeAirAtomisation: 'Volume aria atomizzazione [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Volume vapore atomizzazione [t/h]',
    dr_tempParoiSCC: 'Temperatura parete SCC [°C]',
    dr_surfaceSCC: 'Superficie SCC [m²]',
    dr_pthRadSCC: 'Perdite radiative SCC [MW]',
    dr_pthConvSCC: 'Perdite convettive SCC [MW]',
    dr_pthTotSCC: 'Perdite totali SCC [MW]',
    dr_consoElecExtracteur: 'Consumo elettrico estrattore [kW]',
    dr_masseImbruleesKgh: 'Massa di incombusti [kg/h]',
    dr_co2Transport: 'CO₂ trasporto [kg/km]',
    dr_coutTransport: 'Costo trasporto [€/km]',
    dr_co2TransportTotal: 'CO₂ trasporto totale [kg]',
    dr_coutTransportTotal: 'Costo trasporto totale [€]',
    dr_consoElecVentiloComb: 'Consumo ventilatore combustione [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Temperatura dei fumi [°C]',
    dr_emissiviteFume: 'Emissività dei fumi',
    dr_teauExtracteur: 'Temperatura acqua estrattore [°C]',
    dr_sEchange: 'Superficie di scambio [m²]',
    dr_coeffA: 'Coefficiente a',
    dr_coeffB: 'Coefficiente b',
    dr_coeffC: 'Coefficiente c',
    dr_coeffBmaj: 'Coefficiente B',
    dr_coeffCmaj: 'Coefficiente C',
    dr_facteurF: 'Fattore di forma F',
    dr_fluxRadiatif: 'Flusso radiativo [kW]',
    dr_eauEvapExtracteur: 'Acqua evaporata estrattore [kg/h]',
    dr_pOutMmCE: 'Pressione di uscita [mmCE]',

    // Main navigation
    title: 'Configurazione Forno Rotativo e SCC',
    combustionParameters: 'Parametri di combustione',
    flueGases: 'Gas di combustione',
    pollutantEmissions: 'Emissioni inquinanti',
    design: 'Progettazione',
    opex: 'Opex',
    backToFlow: 'Torna al flusso',
    sendData: 'Invia dati',
    rapport: 'Rapporto',
    
    calculationParameters: 'Parametri di calcolo',
    calculatedParameters: 'Parametri calcolati',
    combustionAirComposition: 'Composizione aria di combustione',
    atStoichiometry: 'Alla stechiometria',
    atAdiabaticity: 'All\'adiabaticità',
    combustionAirTotal: 'Aria di combustione totale',
    flueGasComposition: 'Composizione gas di combustione',
    flueGasAtStoichiometry: 'Gas di combustione alla stechiometria',
    outputFlueGasWithoutWater: 'Gas di combustione in uscita senza acqua dall\'estrattore',
    outputFlueGasWithWater: 'Gas di combustione in uscita con acqua dall\'estrattore',
    resetValues: 'Ripristina valori',
    export: 'Esporta',
    
    flueGasTemperatureOutlet: 'Temperatura di uscita gas di combustione [°C]',
    airFactor: 'Fattore aria',
    combustionAirTemperature: 'Temperatura aria di combustione [°C]',
    wasteTemperature: 'Temperatura rifiuti [°C]',
    steamWaterTemperature: 'Temperatura acqua vapore',
    estimatedThermalLosses: 'Perdite termiche stimate [%]',
    airPreheatingPart: 'Parte preriscaldamento aria [%]',
    airPreheatingTemperature: 'Temperatura preriscaldamento aria [°C]',
    airRelativeMoisture: 'Umidità relativa aria [%]',
    waterVaporizedFromExtractor: 'Acqua vaporizzata dall\'estrattore [kg/h]',
    
    airStoechio: 'Aria stechiometrica [Kmole]',
    calculatedTemperature: 'Temperatura calcolata [°C]',
    waterContent: 'Contenuto acqua [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Fattore aria calcolato',

    resetDefaultValues: 'Ripristina valori predefiniti',
    mass: 'Massa [kg/h]',
    wasteFlow: 'Flusso rifiuti [kg/h]',
    flueGasFlowWet: 'Flusso gas umido [Nm3/h]',
    flueGasFlowDry: 'Flusso gas secco [Nm3/h]',
    o2Calculated: 'O2 calcolato [%]',
    inertMass: 'Massa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Soglia trattamento mercurio [micro g/Nm3]',
    noxIn: 'NOx INGRESSO [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Contenuto ceneri volanti [g/Nm3]',
    siccityBottomAsh: 'Siccità scorie [%]',
    o2Ref: 'O2 rif [%]',
    sncr: 'SNCR (Riduzione Catalitica Selettiva)',
    sncrtEnabled: 'SNCR attivato',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Stechiometria',
    mercuryTreatment: 'Trattamento mercurio',
    hgTreatmentEnabled: 'Trattamento Hg attivato',
    brHgRatio: 'Rapporto Br/Hg',
    pollutantTreatmentTable: 'Tabella trattamento inquinanti',
    pollutant: 'Inquinante',
    reactif: 'Reagente',
    massInput: 'Massa ingresso',
    efficiency: 'Efficienza (%)',
    stoechCoeff: 'Coeff. Stechiom.',
    massOutput: 'Massa uscita',
    massResidue: 'Massa residuo',
    massReactif: 'Massa reagente',
    massReduced: 'Massa ridotta',
    inputFlueGas: 'Gas di combustione ingresso',
    outputFlueGas: 'Gas di combustione uscita',
    bottomAshesCalculated: 'Scorie calcolate',
    bottomAsh: 'Scorie [kg/h]',
    bottomAshWet: 'Scorie umide [kg/h]',
    flyAsh: 'Ceneri volanti [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Massa Hg [kg/h]',
    bromideConsumption: 'Consumo bromuro [kg/h]',

    aeraulicPressureLoss: 'Perdita di carico aeraulica',
    thermicalLossParameters: 'Parametri perdite termiche',
    rotaryKilnDesign: 'Progettazione forno rotativo',
    lanceEstimation: 'Stima lance su facciata',
    facadeCooling: 'Parametri raffreddamento facciata',
    facadeThermicalLosses: 'Parametri perdite termiche facciata',
    shellCooling: 'Raffreddamento involucro',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Bruciatori SCC',
    sccThermicalLosses: 'Stima perdite termiche SCC',
    extractorConsumption: 'Stima consumo estrattore',
    combustionAirFan: 'Stima consumo ventilatore aria combustione',
    extractorWaterEvaporation: 'Stima evaporazione acqua estrattore',
    warningSlope: '⚠️ Attenzione: Pendenza forno supera limite raccomandato (2-5°)',
    warningFillRate: '⚠️ Attenzione: Tasso riempimento supera limite raccomandato (max 5%)',
    warningVelocity: '⚠️ Attenzione: Velocità gas in SCC supera limite raccomandato di 3 m/s',
  },

  pt: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Pressão aeráulica',
    pdcMmCE: 'Perda de carga mmCE',
    diametreInterne: 'Diâmetro interno',
    diametreExterne: 'Diâmetro externo',
    longueur: 'Comprimento',
    pente: 'Inclinação',
    nombreTours: 'Número de voltas',
    hauteurDechets: 'Altura dos resíduos',
    masseVolumiqueDechets: 'Densidade dos resíduos',
    debitDechetsSolides: 'Vazão de resíduos sólidos',
    debitDechetsLiquides: 'Vazão de resíduos líquidos',
    typeCombustible: 'Tipo de combustível',
    typeAtomisation: 'Tipo de atomização',
    typeEau: 'Tipo de água',
    debitEau: 'Vazão de água',
    temperatureEntree: 'Temperatura de entrada',
    temperatureSortie: 'Temperatura de saída',
    epaisseurRefractaire: 'Espessura do refratário',
    temperaturePeau: 'Temperatura da pele',
    dtRefroidissement: 'DT resfriamento',
    debitHumideFumees: 'Vazão úmida dos gases',
    temperatureSCC: 'Temperatura SCC',
    diametreSCC: 'Diâmetro SCC',
    tempsSejourDesire: 'Tempo de residência desejado',
    typeCombustibleSCC: 'Tipo de combustível',
    typeAtomisationSCC: 'Tipo de atomização',
    nbTrappes: 'Número de comportas',
    puissanceUnite: 'Potência por unidade',
    masseImbrulees: 'Massa de inqueimados',
    typeCamion: 'Tipo de caminhão',
    distance: 'Distância',
    debitVentilateur: 'Vazão do ventilador',
    rendementVentilateur: 'Rendimento do ventilador',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Temperatura dos gases',
    emissiviteFume: 'Emissividade dos gases',
    teauExtracteur: 'Temperatura da água extrator',
    // Design results (RK)
    dr_ratioLD: 'Relação L/D',
    dr_puissanceFour: 'Potência do forno [MW]',
    dr_vitesseFumees: 'Velocidade dos gases [m/s]',
    dr_penteMmM: 'Inclinação [mm/m]',
    dr_rayonFour: 'Raio do forno [m]',
    dr_tempsSejourSullivan: 'Tempo de residência (Sullivan) [min]',
    dr_tauxRemplissage: 'Taxa de enchimento do forno [%]',
    dr_consoElecRotation: 'Consumo elétrico de rotação [kW]',
    dr_debitDechetsLiquidesKgh: 'Vazão de resíduos líquidos [kg/h]',
    dr_puissanceBruleur: 'Potência do queimador [MW]',
    dr_flammePilote: 'Chama piloto [kW]',
    dr_nombreLances: 'Número de lanças',
    dr_nombreLancesBackup: 'Número de lanças reserva',
    dr_volumeAir: 'Volume de ar [Nm³/h]',
    dr_volumeVapeur: 'Volume de vapor [t/h]',
    dr_consoElecAirCo: 'Potência ar de combustão [kW]',
    dr_perteEau: 'Perda de água [m³/h]',
    dr_enthalpieRefroidissement: 'Entalpia de resfriamento [MW]',
    dr_puissancePompe: 'Potência bomba circulação água [kW]',
    dr_surfaceExtFour: 'Superfície externa do forno [m²]',
    dr_pertesRad: 'Perdas térmicas radiativas [MW]',
    dr_pertesConv: 'Perdas térmicas convectivas [MW]',
    dr_pertesTotales: 'Perdas térmicas totais [MW]',
    dr_partPertes: 'Parcela de perdas térmicas [%]',
    dr_pertesRadVirole: 'Perdas radiativas casco [MW]',
    dr_pertesConvVirole: 'Perdas convectivas casco [MW]',
    dr_pertesConvViroleTot: 'Perdas convectivas casco totais [MW]',
    dr_consoElecVirole: 'Consumo resfriamento casco [kW]',
    dr_nombreVentilateurs: 'Número de ventiladores',
    dr_debitFumeesM3h: 'Vazão dos gases [m³/h]',
    dr_hauteurSCC: 'Altura da SCC [m]',
    dr_puissanceBruleurSCC: 'Potência do queimador SCC [MW]',
    dr_puissanceFlammePilote: 'Potência da chama piloto [kW]',
    dr_nombreLancesNb: 'Número de lanças',
    dr_nombreLancesBackupNb: 'Número de lanças reserva',
    dr_volumeAirAtomisation: 'Volume ar atomização [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Volume vapor atomização [t/h]',
    dr_tempParoiSCC: 'Temperatura parede SCC [°C]',
    dr_surfaceSCC: 'Superfície SCC [m²]',
    dr_pthRadSCC: 'Perdas radiativas SCC [MW]',
    dr_pthConvSCC: 'Perdas convectivas SCC [MW]',
    dr_pthTotSCC: 'Perdas totais SCC [MW]',
    dr_consoElecExtracteur: 'Consumo elétrico extrator [kW]',
    dr_masseImbruleesKgh: 'Massa de inqueimados [kg/h]',
    dr_co2Transport: 'CO₂ transporte [kg/km]',
    dr_coutTransport: 'Custo transporte [€/km]',
    dr_co2TransportTotal: 'CO₂ transporte total [kg]',
    dr_coutTransportTotal: 'Custo transporte total [€]',
    dr_consoElecVentiloComb: 'Consumo ventilador combustão [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Temperatura dos gases [°C]',
    dr_emissiviteFume: 'Emissividade dos gases',
    dr_teauExtracteur: 'Temperatura da água extrator [°C]',
    dr_sEchange: 'Superfície de troca [m²]',
    dr_coeffA: 'Coeficiente a',
    dr_coeffB: 'Coeficiente b',
    dr_coeffC: 'Coeficiente c',
    dr_coeffBmaj: 'Coeficiente B',
    dr_coeffCmaj: 'Coeficiente C',
    dr_facteurF: 'Fator de forma F',
    dr_fluxRadiatif: 'Fluxo radiativo [kW]',
    dr_eauEvapExtracteur: 'Água evaporada extrator [kg/h]',
    dr_pOutMmCE: 'Pressão de saída [mmCE]',

    // Main navigation
    title: 'Configuração de Forno Rotativo e SCC',
    combustionParameters: 'Parâmetros de combustão',
    flueGases: 'Gases de combustão',
    pollutantEmissions: 'Emissões poluentes',
    design: 'Design',
    opex: 'Opex',
    backToFlow: 'Voltar ao fluxo',
    sendData: 'Enviar dados',
    rapport: 'Relatório',
    
    calculationParameters: 'Parâmetros de cálculo',
    calculatedParameters: 'Parâmetros calculados',
    combustionAirComposition: 'Composição do ar de combustão',
    atStoichiometry: 'Na estequiometria',
    atAdiabaticity: 'Na adiabacidade',
    combustionAirTotal: 'Ar de combustão total',
    flueGasComposition: 'Composição dos gases de combustão',
    flueGasAtStoichiometry: 'Gases de combustão na estequiometria',
    outputFlueGasWithoutWater: 'Gases de combustão de saída sem água do extrator',
    outputFlueGasWithWater: 'Gases de combustão de saída com água do extrator',
    resetValues: 'Redefinir valores',
    export: 'Exportar',
    
    flueGasTemperatureOutlet: 'Temperatura de saída dos gases de combustão [°C]',
    airFactor: 'Fator de ar',
    combustionAirTemperature: 'Temperatura do ar de combustão [°C]',
    wasteTemperature: 'Temperatura dos resíduos [°C]',
    steamWaterTemperature: 'Temperatura da água vapor',
    estimatedThermalLosses: 'Perdas térmicas estimadas [%]',
    airPreheatingPart: 'Parte de pré-aquecimento do ar [%]',
    airPreheatingTemperature: 'Temperatura de pré-aquecimento do ar [°C]',
    airRelativeMoisture: 'Umidade relativa do ar [%]',
    waterVaporizedFromExtractor: 'Água vaporizada do extrator [kg/h]',
    
    airStoechio: 'Ar estequiométrico [Kmole]',
    calculatedTemperature: 'Temperatura calculada [°C]',
    waterContent: 'Conteúdo de água [kg/Nm3]',
    hSystem: 'H_sistema',
    airFactorCalculated: 'Fator de ar calculado',

    resetDefaultValues: 'Redefinir valores padrão',
    mass: 'Massa [kg/h]',
    wasteFlow: 'Fluxo de resíduos [kg/h]',
    flueGasFlowWet: 'Fluxo de gás úmido [Nm3/h]',
    flueGasFlowDry: 'Fluxo de gás seco [Nm3/h]',
    o2Calculated: 'O2 calculado [%]',
    inertMass: 'Massa inerte [kg/h]',

    mercuryTreatmentThreshold: 'Limiar de tratamento de mercúrio [micro g/Nm3]',
    noxIn: 'NOx ENTRADA [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Conteúdo de cinzas volantes [g/Nm3]',
    siccityBottomAsh: 'Secura das escórias [%]',
    o2Ref: 'O2 ref [%]',
    sncr: 'SNCR (Redução Catalítica Seletiva)',
    sncrtEnabled: 'SNCR ativado',
    noxLimit: 'Limite NOx [mg/Nm3]',
    stoichiometry: 'Estequiometria',
    mercuryTreatment: 'Tratamento de mercúrio',
    hgTreatmentEnabled: 'Tratamento Hg ativado',
    brHgRatio: 'Relação Br/Hg',
    pollutantTreatmentTable: 'Tabela de tratamento de poluentes',
    pollutant: 'Poluente',
    reactif: 'Reagente',
    massInput: 'Massa entrada',
    efficiency: 'Eficiência (%)',
    stoechCoeff: 'Coef. Estequiom.',
    massOutput: 'Massa saída',
    massResidue: 'Massa resíduo',
    massReactif: 'Massa reagente',
    massReduced: 'Massa reduzida',
    inputFlueGas: 'Gás de combustão entrada',
    outputFlueGas: 'Gás de combustão saída',
    bottomAshesCalculated: 'Escórias calculadas',
    bottomAsh: 'Escórias [kg/h]',
    bottomAshWet: 'Escórias úmidas [kg/h]',
    flyAsh: 'Cinzas volantes [kg/h]',
    nh3Consumption: 'Consumo NH3 [kg/h]',
    hgMass: 'Massa Hg [kg/h]',
    bromideConsumption: 'Consumo de brometo [kg/h]',

    aeraulicPressureLoss: 'Perda de carga aeráulica',
    thermicalLossParameters: 'Parâmetros de perdas térmicas',
    rotaryKilnDesign: 'Projeto de forno rotativo',
    lanceEstimation: 'Estimativa de lanças na fachada',
    facadeCooling: 'Parâmetros de refrigeração da fachada',
    facadeThermicalLosses: 'Parâmetros de perdas térmicas da fachada',
    shellCooling: 'Refrigeração da carcaça',
    sccDimensioning: 'Dimensionamento SCC',
    sccBurners: 'Queimadores SCC',
    sccThermicalLosses: 'Estimativa de perdas térmicas SCC',
    extractorConsumption: 'Estimativa de consumo do extrator',
    combustionAirFan: 'Estimativa de consumo do ventilador de ar de combustão',
    extractorWaterEvaporation: 'Estimativa de evaporação de água do extrator',
    warningSlope: '⚠️ Aviso: Inclinação do forno excede limite recomendado (2-5°)',
    warningFillRate: '⚠️ Aviso: Taxa de enchimento excede limite recomendado (máx 5%)',
    warningVelocity: '⚠️ Aviso: Velocidade do gás em SCC excede limite recomendado de 3 m/s',
  },

  ru: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'Аэравлическое давление',
    pdcMmCE: 'Потеря давления mmCE',
    diametreInterne: 'Внутренний диаметр',
    diametreExterne: 'Наружный диаметр',
    longueur: 'Длина',
    pente: 'Уклон',
    nombreTours: 'Число оборотов',
    hauteurDechets: 'Высота отходов',
    masseVolumiqueDechets: 'Плотность отходов',
    debitDechetsSolides: 'Расход твёрдых отходов',
    debitDechetsLiquides: 'Расход жидких отходов',
    typeCombustible: 'Тип топлива',
    typeAtomisation: 'Тип распыления',
    typeEau: 'Тип воды',
    debitEau: 'Расход воды',
    temperatureEntree: 'Температура на входе',
    temperatureSortie: 'Температура на выходе',
    epaisseurRefractaire: 'Толщина футеровки',
    temperaturePeau: 'Температура поверхности',
    dtRefroidissement: 'DT охлаждения',
    debitHumideFumees: 'Расход влажных дымовых газов',
    temperatureSCC: 'Температура SCC',
    diametreSCC: 'Диаметр SCC',
    tempsSejourDesire: 'Желаемое время пребывания',
    typeCombustibleSCC: 'Тип топлива',
    typeAtomisationSCC: 'Тип распыления',
    nbTrappes: 'Количество люков',
    puissanceUnite: 'Мощность на единицу',
    masseImbrulees: 'Масса недожога',
    typeCamion: 'Тип грузовика',
    distance: 'Расстояние',
    debitVentilateur: 'Расход вентилятора',
    rendementVentilateur: 'КПД вентилятора',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'Температура дымовых газов',
    emissiviteFume: 'Излучательная способность газов',
    teauExtracteur: 'Температура воды экстрактора',
    // Design results (RK)
    dr_ratioLD: 'Отношение L/D',
    dr_puissanceFour: 'Мощность печи [MW]',
    dr_vitesseFumees: 'Скорость дымовых газов [m/s]',
    dr_penteMmM: 'Уклон [mm/m]',
    dr_rayonFour: 'Радиус печи [m]',
    dr_tempsSejourSullivan: 'Время пребывания (Sullivan) [min]',
    dr_tauxRemplissage: 'Степень заполнения печи [%]',
    dr_consoElecRotation: 'Потребление на вращение [kW]',
    dr_debitDechetsLiquidesKgh: 'Расход жидких отходов [kg/h]',
    dr_puissanceBruleur: 'Мощность горелки [MW]',
    dr_flammePilote: 'Запальное пламя [kW]',
    dr_nombreLances: 'Число фурм',
    dr_nombreLancesBackup: 'Число резервных фурм',
    dr_volumeAir: 'Объём воздуха [Nm³/h]',
    dr_volumeVapeur: 'Объём пара [t/h]',
    dr_consoElecAirCo: 'Мощность воздуха горения [kW]',
    dr_perteEau: 'Потери воды [m³/h]',
    dr_enthalpieRefroidissement: 'Энтальпия охлаждения [MW]',
    dr_puissancePompe: 'Мощность насоса циркуляции воды [kW]',
    dr_surfaceExtFour: 'Наружная поверхность печи [m²]',
    dr_pertesRad: 'Радиационные тепловые потери [MW]',
    dr_pertesConv: 'Конвективные тепловые потери [MW]',
    dr_pertesTotales: 'Суммарные тепловые потери [MW]',
    dr_partPertes: 'Доля тепловых потерь [%]',
    dr_pertesRadVirole: 'Радиационные потери обечайки [MW]',
    dr_pertesConvVirole: 'Конвективные потери обечайки [MW]',
    dr_pertesConvViroleTot: 'Суммарные конвективные потери обечайки [MW]',
    dr_consoElecVirole: 'Мощность охлаждения обечайки [kW]',
    dr_nombreVentilateurs: 'Число вентиляторов',
    dr_debitFumeesM3h: 'Расход дымовых газов [m³/h]',
    dr_hauteurSCC: 'Высота SCC [m]',
    dr_puissanceBruleurSCC: 'Мощность горелки SCC [MW]',
    dr_puissanceFlammePilote: 'Мощность запального пламени [kW]',
    dr_nombreLancesNb: 'Число фурм',
    dr_nombreLancesBackupNb: 'Число резервных фурм',
    dr_volumeAirAtomisation: 'Объём воздуха распыления [Nm³/h]',
    dr_volumeVapeurAtomisation: 'Объём пара распыления [t/h]',
    dr_tempParoiSCC: 'Температура стенки SCC [°C]',
    dr_surfaceSCC: 'Поверхность SCC [m²]',
    dr_pthRadSCC: 'Радиационные потери SCC [MW]',
    dr_pthConvSCC: 'Конвективные потери SCC [MW]',
    dr_pthTotSCC: 'Суммарные потери SCC [MW]',
    dr_consoElecExtracteur: 'Потребление экстрактора [kW]',
    dr_masseImbruleesKgh: 'Масса недожога [kg/h]',
    dr_co2Transport: 'CO₂ транспорт [kg/km]',
    dr_coutTransport: 'Стоимость транспорта [€/km]',
    dr_co2TransportTotal: 'CO₂ транспорт всего [kg]',
    dr_coutTransportTotal: 'Стоимость транспорта всего [€]',
    dr_consoElecVentiloComb: 'Мощность вентилятора горения [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'Температура дымовых газов [°C]',
    dr_emissiviteFume: 'Излучательная способность газов',
    dr_teauExtracteur: 'Температура воды экстрактора [°C]',
    dr_sEchange: 'Площадь теплообмена [m²]',
    dr_coeffA: 'Коэффициент a',
    dr_coeffB: 'Коэффициент b',
    dr_coeffC: 'Коэффициент c',
    dr_coeffBmaj: 'Коэффициент B',
    dr_coeffCmaj: 'Коэффициент C',
    dr_facteurF: 'Угловой коэффициент F',
    dr_fluxRadiatif: 'Радиационный поток [kW]',
    dr_eauEvapExtracteur: 'Испарённая вода экстрактора [kg/h]',
    dr_pOutMmCE: 'Давление на выходе [mmCE]',

    // Main navigation
    title: 'Конфигурация вращающейся печи и SCC',
    combustionParameters: 'Параметры сгорания',
    flueGases: 'Дымовые газы',
    pollutantEmissions: 'Выбросы загрязняющих веществ',
    design: 'Проектирование',
    opex: 'Эксплуатационные расходы',
    backToFlow: 'Вернуться к потоку',
    sendData: 'Отправить данные',
    rapport: 'Отчёт',
    
    calculationParameters: 'Параметры расчета',
    calculatedParameters: 'Расчетные параметры',
    combustionAirComposition: 'Состав воздуха для сгорания',
    atStoichiometry: 'При стехиометрии',
    atAdiabaticity: 'При адиабатности',
    combustionAirTotal: 'Общий воздух для сгорания',
    flueGasComposition: 'Состав дымовых газов',
    flueGasAtStoichiometry: 'Дымовые газы при стехиометрии',
    outputFlueGasWithoutWater: 'Выходящие дымовые газы без воды из экстрактора',
    outputFlueGasWithWater: 'Выходящие дымовые газы с водой из экстрактора',
    resetValues: 'Сбросить значения',
    export: 'Экспорт',
    
    flueGasTemperatureOutlet: 'Температура выхода дымовых газов [°C]',
    airFactor: 'Коэффициент воздуха',
    combustionAirTemperature: 'Температура воздуха для сгорания [°C]',
    wasteTemperature: 'Температура отходов [°C]',
    steamWaterTemperature: 'Температура водяного пара',
    estimatedThermalLosses: 'Предполагаемые тепловые потери [%]',
    airPreheatingPart: 'Часть подогрева воздуха [%]',
    airPreheatingTemperature: 'Температура подогрева воздуха [°C]',
    airRelativeMoisture: 'Относительная влажность воздуха [%]',
    waterVaporizedFromExtractor: 'Испаренная вода из экстрактора [kg/h]',
    
    airStoechio: 'Стехиометрический воздух [Kmole]',
    calculatedTemperature: 'Расчетная температура [°C]',
    waterContent: 'Содержание воды [kg/Nm3]',
    hSystem: 'H_система',
    airFactorCalculated: 'Расчетный коэффициент воздуха',

    resetDefaultValues: 'Сбросить значения по умолчанию',
    mass: 'Масса [kg/h]',
    wasteFlow: 'Поток отходов [kg/h]',
    flueGasFlowWet: 'Поток влажного газа [Nm3/h]',
    flueGasFlowDry: 'Поток сухого газа [Nm3/h]',
    o2Calculated: 'O2 рассчитано [%]',
    inertMass: 'Инертная масса [kg/h]',

    mercuryTreatmentThreshold: 'Порог обработки ртути [micro g/Nm3]',
    noxIn: 'NOx ВХОД [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'Содержание летучей золы [g/Nm3]',
    siccityBottomAsh: 'Сухость шлака [%]',
    o2Ref: 'O2 эталон [%]',
    sncr: 'SNCR (Селективное некаталитическое восстановление)',
    sncrtEnabled: 'SNCR активирован',
    noxLimit: 'Предел NOx [mg/Nm3]',
    stoichiometry: 'Стехиометрия',
    mercuryTreatment: 'Обработка ртути',
    hgTreatmentEnabled: 'Обработка Hg активирована',
    brHgRatio: 'Соотношение Br/Hg',
    pollutantTreatmentTable: 'Таблица обработки загрязняющих веществ',
    pollutant: 'Загрязняющее вещество',
    reactif: 'Реагент',
    massInput: 'Входная масса',
    efficiency: 'Эффективность (%)',
    stoechCoeff: 'Стехиом. коэфф.',
    massOutput: 'Выходная масса',
    massResidue: 'Масса остатка',
    massReactif: 'Масса реагента',
    massReduced: 'Уменьшенная масса',
    inputFlueGas: 'Входящий дымовой газ',
    outputFlueGas: 'Выходящий дымовой газ',
    bottomAshesCalculated: 'Рассчитанный шлак',
    bottomAsh: 'Шлак [kg/h]',
    bottomAshWet: 'Влажный шлак [kg/h]',
    flyAsh: 'Летучая зола [kg/h]',
    nh3Consumption: 'Потребление NH3 [kg/h]',
    hgMass: 'Масса Hg [kg/h]',
    bromideConsumption: 'Потребление бромида [kg/h]',

    aeraulicPressureLoss: 'Аэродинамическая потеря давления',
    thermicalLossParameters: 'Параметры тепловых потерь',
    rotaryKilnDesign: 'Проектирование вращающейся печи',
    lanceEstimation: 'Оценка форсунок на фасаде',
    facadeCooling: 'Параметры охлаждения фасада',
    facadeThermicalLosses: 'Параметры тепловых потерь фасада',
    shellCooling: 'Охлаждение корпуса',
    sccDimensioning: 'Размеры SCC',
    sccBurners: 'Горелки SCC',
    sccThermicalLosses: 'Оценка тепловых потерь SCC',
    extractorConsumption: 'Оценка потребления экстрактора',
    combustionAirFan: 'Оценка потребления вентилятора воздуха для горения',
    extractorWaterEvaporation: 'Оценка испарения воды экстрактора',
    warningSlope: '⚠️ Предупреждение: Наклон печи превышает рекомендуемый предел (2-5°)',
    warningFillRate: '⚠️ Предупреждение: Коэффициент заполнения превышает рекомендуемый предел (макс 5%)',
    warningVelocity: '⚠️ Предупреждение: Скорость газа в SCC превышает рекомендуемый предел 3 м/с',
  },

  ja: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: '通風圧力',
    pdcMmCE: '圧力損失 mmCE',
    diametreInterne: '内径',
    diametreExterne: '外径',
    longueur: '長さ',
    pente: '傾斜',
    nombreTours: '回転数',
    hauteurDechets: '廃棄物の高さ',
    masseVolumiqueDechets: '廃棄物の密度',
    debitDechetsSolides: '固形廃棄物流量',
    debitDechetsLiquides: '液体廃棄物流量',
    typeCombustible: '燃料の種類',
    typeAtomisation: '噴霧の種類',
    typeEau: '水の種類',
    debitEau: '水流量',
    temperatureEntree: '入口温度',
    temperatureSortie: '出口温度',
    epaisseurRefractaire: '耐火材の厚さ',
    temperaturePeau: '表面温度',
    dtRefroidissement: '冷却DT',
    debitHumideFumees: '湿り排ガス流量',
    temperatureSCC: 'SCC温度',
    diametreSCC: 'SCC直径',
    tempsSejourDesire: '所望滞留時間',
    typeCombustibleSCC: '燃料の種類',
    typeAtomisationSCC: '噴霧の種類',
    nbTrappes: 'ハッチ数',
    puissanceUnite: '単位あたり出力',
    masseImbrulees: '未燃分質量',
    typeCamion: 'トラックの種類',
    distance: '距離',
    debitVentilateur: 'ファン流量',
    rendementVentilateur: 'ファン効率',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: '排ガス温度',
    emissiviteFume: '排ガス放射率',
    teauExtracteur: '抽出器水温',
    // Design results (RK)
    dr_ratioLD: 'L/D比',
    dr_puissanceFour: 'キルン出力 [MW]',
    dr_vitesseFumees: '排ガス速度 [m/s]',
    dr_penteMmM: '傾斜 [mm/m]',
    dr_rayonFour: 'キルン半径 [m]',
    dr_tempsSejourSullivan: '滞留時間 (Sullivan) [min]',
    dr_tauxRemplissage: 'キルン充填率 [%]',
    dr_consoElecRotation: '回転電力消費 [kW]',
    dr_debitDechetsLiquidesKgh: '液体廃棄物流量 [kg/h]',
    dr_puissanceBruleur: 'バーナー出力 [MW]',
    dr_flammePilote: 'パイロット炎 [kW]',
    dr_nombreLances: 'ランス数',
    dr_nombreLancesBackup: '予備ランス数',
    dr_volumeAir: '空気量 [Nm³/h]',
    dr_volumeVapeur: '蒸気量 [t/h]',
    dr_consoElecAirCo: '燃焼空気電力 [kW]',
    dr_perteEau: '水損失 [m³/h]',
    dr_enthalpieRefroidissement: '冷却エンタルピー [MW]',
    dr_puissancePompe: '水循環ポンプ出力 [kW]',
    dr_surfaceExtFour: 'キルン外表面 [m²]',
    dr_pertesRad: '放射熱損失 [MW]',
    dr_pertesConv: '対流熱損失 [MW]',
    dr_pertesTotales: '総熱損失 [MW]',
    dr_partPertes: '熱損失割合 [%]',
    dr_pertesRadVirole: 'シェル放射損失 [MW]',
    dr_pertesConvVirole: 'シェル対流損失 [MW]',
    dr_pertesConvViroleTot: 'シェル対流損失合計 [MW]',
    dr_consoElecVirole: 'シェル冷却電力 [kW]',
    dr_nombreVentilateurs: 'ファン数',
    dr_debitFumeesM3h: '排ガス流量 [m³/h]',
    dr_hauteurSCC: 'SCC高さ [m]',
    dr_puissanceBruleurSCC: 'SCCバーナー出力 [MW]',
    dr_puissanceFlammePilote: 'パイロット炎出力 [kW]',
    dr_nombreLancesNb: 'ランス数',
    dr_nombreLancesBackupNb: '予備ランス数',
    dr_volumeAirAtomisation: '噴霧空気量 [Nm³/h]',
    dr_volumeVapeurAtomisation: '噴霧蒸気量 [t/h]',
    dr_tempParoiSCC: 'SCC壁温度 [°C]',
    dr_surfaceSCC: 'SCC表面積 [m²]',
    dr_pthRadSCC: 'SCC放射損失 [MW]',
    dr_pthConvSCC: 'SCC対流損失 [MW]',
    dr_pthTotSCC: 'SCC総損失 [MW]',
    dr_consoElecExtracteur: '抽出機電力消費 [kW]',
    dr_masseImbruleesKgh: '未燃分質量 [kg/h]',
    dr_co2Transport: 'CO₂輸送 [kg/km]',
    dr_coutTransport: '輸送コスト [€/km]',
    dr_co2TransportTotal: 'CO₂輸送合計 [kg]',
    dr_coutTransportTotal: '輸送コスト合計 [€]',
    dr_consoElecVentiloComb: '燃焼ファン電力 [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: '排ガス温度 [°C]',
    dr_emissiviteFume: '排ガス放射率',
    dr_teauExtracteur: '抽出器水温 [°C]',
    dr_sEchange: '熱交換面積 [m²]',
    dr_coeffA: '係数 a',
    dr_coeffB: '係数 b',
    dr_coeffC: '係数 c',
    dr_coeffBmaj: '係数 B',
    dr_coeffCmaj: '係数 C',
    dr_facteurF: '形態係数 F',
    dr_fluxRadiatif: '放射熱流束 [kW]',
    dr_eauEvapExtracteur: '抽出器蒸発水 [kg/h]',
    dr_pOutMmCE: '出口圧力 [mmCE]',

    // Main navigation
    title: 'ロータリーキルンとSCC設定',
    combustionParameters: '燃焼パラメータ',
    flueGases: '燃焼ガス',
    pollutantEmissions: '汚染物質排出',
    design: '設計',
    opex: '運営費',
    backToFlow: 'フローに戻る',
    sendData: 'データ送信',
    rapport: 'レポート',
    
    calculationParameters: '計算パラメータ',
    calculatedParameters: '計算されたパラメータ',
    combustionAirComposition: '燃焼空気組成',
    atStoichiometry: '化学量論で',
    atAdiabaticity: '断熱で',
    combustionAirTotal: '燃焼空気合計',
    flueGasComposition: '燃焼ガス組成',
    flueGasAtStoichiometry: '化学量論での燃焼ガス',
    outputFlueGasWithoutWater: '抽出器からの水なしの出力燃焼ガス',
    outputFlueGasWithWater: '抽出器からの水ありの出力燃焼ガス',
    resetValues: '値をリセット',
    export: 'エクスポート',
    
    flueGasTemperatureOutlet: '燃焼ガス出口温度 [°C]',
    airFactor: '空気率',
    combustionAirTemperature: '燃焼空気温度 [°C]',
    wasteTemperature: '廃棄物温度 [°C]',
    steamWaterTemperature: '蒸気水温度',
    estimatedThermalLosses: '推定熱損失 [%]',
    airPreheatingPart: '空気予熱部分 [%]',
    airPreheatingTemperature: '空気予熱温度 [°C]',
    airRelativeMoisture: '空気相対湿度 [%]',
    waterVaporizedFromExtractor: '抽出器からの蒸発水 [kg/h]',
    
    airStoechio: '化学量論空気 [Kmole]',
    calculatedTemperature: '計算温度 [°C]',
    waterContent: '水分含有量 [kg/Nm3]',
    hSystem: 'H_システム',
    airFactorCalculated: '計算された空気率',

    resetDefaultValues: 'デフォルト値にリセット',
    mass: '質量 [kg/h]',
    wasteFlow: '廃棄物流量 [kg/h]',
    flueGasFlowWet: '湿潤ガス流量 [Nm3/h]',
    flueGasFlowDry: '乾燥ガス流量 [Nm3/h]',
    o2Calculated: 'O2計算値 [%]',
    inertMass: '不活性質量 [kg/h]',

    mercuryTreatmentThreshold: '水銀処理閾値 [micro g/Nm3]',
    noxIn: 'NOx入力 [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: '飛灰含有量 [g/Nm3]',
    siccityBottomAsh: '底灰乾燥度 [%]',
    o2Ref: 'O2基準 [%]',
    sncr: 'SNCR（選択的非触媒還元）',
    sncrtEnabled: 'SNCR有効',
    noxLimit: 'NOx制限 [mg/Nm3]',
    stoichiometry: '化学量論',
    mercuryTreatment: '水銀処理',
    hgTreatmentEnabled: 'Hg処理有効',
    brHgRatio: 'Br/Hg比',
    pollutantTreatmentTable: '汚染物質処理表',
    pollutant: '汚染物質',
    reactif: '試薬',
    massInput: '入力質量',
    efficiency: '効率 (%)',
    stoechCoeff: '化学量論係数',
    massOutput: '出力質量',
    massResidue: '残留質量',
    massReactif: '試薬質量',
    massReduced: '削減質量',
    inputFlueGas: '入力燃焼ガス',
    outputFlueGas: '出力燃焼ガス',
    bottomAshesCalculated: '計算された底灰',
    bottomAsh: '底灰 [kg/h]',
    bottomAshWet: '湿潤底灰 [kg/h]',
    flyAsh: '飛灰 [kg/h]',
    nh3Consumption: 'NH3消費 [kg/h]',
    hgMass: 'Hg質量 [kg/h]',
    bromideConsumption: '臭化物消費 [kg/h]',

    aeraulicPressureLoss: '空気圧力損失',
    thermicalLossParameters: '熱損失パラメータ',
    rotaryKilnDesign: 'ロータリーキルン設計',
    lanceEstimation: 'ファサードランス推定',
    facadeCooling: 'ファサード冷却パラメータ',
    facadeThermicalLosses: 'ファサード熱損失パラメータ',
    shellCooling: 'シェル冷却',
    sccDimensioning: 'SCCサイジング',
    sccBurners: 'SCCバーナー',
    sccThermicalLosses: 'SCC熱損失推定',
    extractorConsumption: '抽出器消費推定',
    combustionAirFan: '燃焼空気ファン消費推定',
    extractorWaterEvaporation: '抽出器水蒸発推定',
    warningSlope: '⚠️ 警告：キルン傾斜が推奨制限（2-5°）を超えています',
    warningFillRate: '⚠️ 警告：充填率が推奨制限（最大5%）を超えています',
    warningVelocity: '⚠️ 警告：SCCのガス速度が推奨制限3 m/sを超えています',
  },

  zh: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: '风压',
    pdcMmCE: '压力损失 mmCE',
    diametreInterne: '内径',
    diametreExterne: '外径',
    longueur: '长度',
    pente: '坡度',
    nombreTours: '转数',
    hauteurDechets: '废物高度',
    masseVolumiqueDechets: '废物密度',
    debitDechetsSolides: '固体废物流量',
    debitDechetsLiquides: '液体废物流量',
    typeCombustible: '燃料类型',
    typeAtomisation: '雾化类型',
    typeEau: '水类型',
    debitEau: '水流量',
    temperatureEntree: '进口温度',
    temperatureSortie: '出口温度',
    epaisseurRefractaire: '耐火材料厚度',
    temperaturePeau: '表面温度',
    dtRefroidissement: '冷却DT',
    debitHumideFumees: '湿烟气流量',
    temperatureSCC: 'SCC温度',
    diametreSCC: 'SCC直径',
    tempsSejourDesire: '期望停留时间',
    typeCombustibleSCC: '燃料类型',
    typeAtomisationSCC: '雾化类型',
    nbTrappes: '闸门数量',
    puissanceUnite: '每单位功率',
    masseImbrulees: '未燃烧质量',
    typeCamion: '卡车类型',
    distance: '距离',
    debitVentilateur: '风机流量',
    rendementVentilateur: '风机效率',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: '烟气温度',
    emissiviteFume: '烟气发射率',
    teauExtracteur: '抽取器水温',
    // Design results (RK)
    dr_ratioLD: 'L/D比',
    dr_puissanceFour: '窑功率 [MW]',
    dr_vitesseFumees: '烟气速度 [m/s]',
    dr_penteMmM: '坡度 [mm/m]',
    dr_rayonFour: '窑半径 [m]',
    dr_tempsSejourSullivan: '停留时间 (Sullivan) [min]',
    dr_tauxRemplissage: '窑充填率 [%]',
    dr_consoElecRotation: '旋转电耗 [kW]',
    dr_debitDechetsLiquidesKgh: '液体废物流量 [kg/h]',
    dr_puissanceBruleur: '燃烧器功率 [MW]',
    dr_flammePilote: '引燃火焰 [kW]',
    dr_nombreLances: '喷枪数量',
    dr_nombreLancesBackup: '备用喷枪数量',
    dr_volumeAir: '空气量 [Nm³/h]',
    dr_volumeVapeur: '蒸汽量 [t/h]',
    dr_consoElecAirCo: '燃烧空气功率 [kW]',
    dr_perteEau: '水损失 [m³/h]',
    dr_enthalpieRefroidissement: '冷却焓 [MW]',
    dr_puissancePompe: '水循环泵功率 [kW]',
    dr_surfaceExtFour: '窑外表面 [m²]',
    dr_pertesRad: '辐射热损失 [MW]',
    dr_pertesConv: '对流热损失 [MW]',
    dr_pertesTotales: '总热损失 [MW]',
    dr_partPertes: '热损失占比 [%]',
    dr_pertesRadVirole: '筒体辐射损失 [MW]',
    dr_pertesConvVirole: '筒体对流损失 [MW]',
    dr_pertesConvViroleTot: '筒体对流损失合计 [MW]',
    dr_consoElecVirole: '筒体冷却电耗 [kW]',
    dr_nombreVentilateurs: '风机数量',
    dr_debitFumeesM3h: '烟气流量 [m³/h]',
    dr_hauteurSCC: 'SCC高度 [m]',
    dr_puissanceBruleurSCC: 'SCC燃烧器功率 [MW]',
    dr_puissanceFlammePilote: '引燃火焰功率 [kW]',
    dr_nombreLancesNb: '喷枪数量',
    dr_nombreLancesBackupNb: '备用喷枪数量',
    dr_volumeAirAtomisation: '雾化空气量 [Nm³/h]',
    dr_volumeVapeurAtomisation: '雾化蒸汽量 [t/h]',
    dr_tempParoiSCC: 'SCC壁温 [°C]',
    dr_surfaceSCC: 'SCC表面积 [m²]',
    dr_pthRadSCC: 'SCC辐射损失 [MW]',
    dr_pthConvSCC: 'SCC对流损失 [MW]',
    dr_pthTotSCC: 'SCC总损失 [MW]',
    dr_consoElecExtracteur: '抽取机电耗 [kW]',
    dr_masseImbruleesKgh: '未燃烧质量 [kg/h]',
    dr_co2Transport: 'CO₂运输 [kg/km]',
    dr_coutTransport: '运输成本 [€/km]',
    dr_co2TransportTotal: 'CO₂运输总量 [kg]',
    dr_coutTransportTotal: '运输总成本 [€]',
    dr_consoElecVentiloComb: '燃烧风机电耗 [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: '烟气温度 [°C]',
    dr_emissiviteFume: '烟气发射率',
    dr_teauExtracteur: '抽取器水温 [°C]',
    dr_sEchange: '换热面积 [m²]',
    dr_coeffA: '系数 a',
    dr_coeffB: '系数 b',
    dr_coeffC: '系数 c',
    dr_coeffBmaj: '系数 B',
    dr_coeffCmaj: '系数 C',
    dr_facteurF: '角系数 F',
    dr_fluxRadiatif: '辐射热流 [kW]',
    dr_eauEvapExtracteur: '抽取器蒸发水 [kg/h]',
    dr_pOutMmCE: '出口压力 [mmCE]',

    // Main navigation
    title: '回转窑和SCC配置',
    combustionParameters: '燃烧参数',
    flueGases: '烟气',
    pollutantEmissions: '污染物排放',
    design: '设计',
    opex: '运营费用',
    backToFlow: '返回流程',
    sendData: '发送数据',
    rapport: '报告',
    
    calculationParameters: '计算参数',
    calculatedParameters: '计算得出的参数',
    combustionAirComposition: '燃烧空气组成',
    atStoichiometry: '在化学计量比',
    atAdiabaticity: '在绝热性',
    combustionAirTotal: '燃烧空气总量',
    flueGasComposition: '烟气组成',
    flueGasAtStoichiometry: '化学计量比下的烟气',
    outputFlueGasWithoutWater: '不含提取器水的输出烟气',
    outputFlueGasWithWater: '含提取器水的输出烟气',
    resetValues: '重置数值',
    export: '导出',
    
    flueGasTemperatureOutlet: '烟气出口温度 [°C]',
    airFactor: '空气系数',
    combustionAirTemperature: '燃烧空气温度 [°C]',
    wasteTemperature: '废料温度 [°C]',
    steamWaterTemperature: '蒸汽水温度',
    estimatedThermalLosses: '估计热损失 [%]',
    airPreheatingPart: '空气预热部分 [%]',
    airPreheatingTemperature: '空气预热温度 [°C]',
    airRelativeMoisture: '空气相对湿度 [%]',
    waterVaporizedFromExtractor: '提取器蒸发水 [kg/h]',
    
    airStoechio: '化学计量空气 [Kmole]',
    calculatedTemperature: '计算温度 [°C]',
    waterContent: '含水量 [kg/Nm3]',
    hSystem: 'H_系统',
    airFactorCalculated: '计算的空气系数',

    resetDefaultValues: '重置默认值',
    mass: '质量 [kg/h]',
    wasteFlow: '废物流量 [kg/h]',
    flueGasFlowWet: '湿气流量 [Nm3/h]',
    flueGasFlowDry: '干气流量 [Nm3/h]',
    o2Calculated: 'O2计算值 [%]',
    inertMass: '惰性质量 [kg/h]',

    mercuryTreatmentThreshold: '汞处理阈值 [micro g/Nm3]',
    noxIn: 'NOx输入 [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: '飞灰含量 [g/Nm3]',
    siccityBottomAsh: '底灰干燥度 [%]',
    o2Ref: 'O2参考 [%]',
    sncr: 'SNCR（选择性非催化还原）',
    sncrtEnabled: 'SNCR启用',
    noxLimit: 'NOx限制 [mg/Nm3]',
    stoichiometry: '化学计量',
    mercuryTreatment: '汞处理',
    hgTreatmentEnabled: 'Hg处理启用',
    brHgRatio: 'Br/Hg比',
    pollutantTreatmentTable: '污染物处理表',
    pollutant: '污染物',
    reactif: '试剂',
    massInput: '输入质量',
    efficiency: '效率 (%)',
    stoechCoeff: '化学计量系数',
    massOutput: '输出质量',
    massResidue: '残留质量',
    massReactif: '试剂质量',
    massReduced: '减少质量',
    inputFlueGas: '输入烟气',
    outputFlueGas: '输出烟气',
    bottomAshesCalculated: '计算的底灰',
    bottomAsh: '底灰 [kg/h]',
    bottomAshWet: '湿底灰 [kg/h]',
    flyAsh: '飞灰 [kg/h]',
    nh3Consumption: 'NH3消耗 [kg/h]',
    hgMass: 'Hg质量 [kg/h]',
    bromideConsumption: '溴化物消耗 [kg/h]',

    aeraulicPressureLoss: '气动压力损失',
    thermicalLossParameters: '热损失参数',
    rotaryKilnDesign: '回转窑设计',
    lanceEstimation: '正面喷枪估算',
    facadeCooling: '正面冷却参数',
    facadeThermicalLosses: '正面热损失参数',
    shellCooling: '外壳冷却',
    sccDimensioning: 'SCC尺寸设计',
    sccBurners: 'SCC燃烧器',
    sccThermicalLosses: 'SCC热损失估算',
    extractorConsumption: '提取器消耗估算',
    combustionAirFan: '燃烧空气风扇消耗估算',
    extractorWaterEvaporation: '提取器水蒸发估算',
    warningSlope: '⚠️ 警告：窑倾斜超过推荐限制（2-5°）',
    warningFillRate: '⚠️ 警告：填充率超过推荐限制（最大5%）',
    warningVelocity: '⚠️ 警告：SCC中的气体速度超过推荐限制3 m/s',
  },

  ar: {
    // Design parameters (RK) — Display_design labels
    pressionAeraulique: 'الضغط الهوائي',
    pdcMmCE: 'فقد الضغط mmCE',
    diametreInterne: 'القطر الداخلي',
    diametreExterne: 'القطر الخارجي',
    longueur: 'الطول',
    pente: 'الميل',
    nombreTours: 'عدد الدورات',
    hauteurDechets: 'ارتفاع النفايات',
    masseVolumiqueDechets: 'كثافة النفايات',
    debitDechetsSolides: 'تدفق النفايات الصلبة',
    debitDechetsLiquides: 'تدفق النفايات السائلة',
    typeCombustible: 'نوع الوقود',
    typeAtomisation: 'نوع الرش',
    typeEau: 'نوع الماء',
    debitEau: 'تدفق الماء',
    temperatureEntree: 'درجة حرارة المدخل',
    temperatureSortie: 'درجة حرارة المخرج',
    epaisseurRefractaire: 'سماكة الحراري',
    temperaturePeau: 'درجة حرارة السطح',
    dtRefroidissement: 'DT التبريد',
    debitHumideFumees: 'تدفق الغازات الرطبة',
    temperatureSCC: 'درجة حرارة SCC',
    diametreSCC: 'قطر SCC',
    tempsSejourDesire: 'زمن المكوث المطلوب',
    typeCombustibleSCC: 'نوع الوقود',
    typeAtomisationSCC: 'نوع الرش',
    nbTrappes: 'عدد الفتحات',
    puissanceUnite: 'القدرة لكل وحدة',
    masseImbrulees: 'كتلة غير المحترق',
    typeCamion: 'نوع الشاحنة',
    distance: 'المسافة',
    debitVentilateur: 'تدفق المروحة',
    rendementVentilateur: 'كفاءة المروحة',
    h2oPourcent: 'H₂O [%]',
    co2Pourcent: 'CO₂ [%]',
    tfumProvisoire: 'درجة حرارة الغازات',
    emissiviteFume: 'انبعاثية الغازات',
    teauExtracteur: 'درجة حرارة ماء المستخرج',
    // Design results (RK)
    dr_ratioLD: 'نسبة L/D',
    dr_puissanceFour: 'قدرة الفرن [MW]',
    dr_vitesseFumees: 'سرعة الغازات [m/s]',
    dr_penteMmM: 'الميل [mm/m]',
    dr_rayonFour: 'نصف قطر الفرن [m]',
    dr_tempsSejourSullivan: 'زمن المكوث (Sullivan) [min]',
    dr_tauxRemplissage: 'نسبة امتلاء الفرن [%]',
    dr_consoElecRotation: 'استهلاك كهربائي للدوران [kW]',
    dr_debitDechetsLiquidesKgh: 'تدفق النفايات السائلة [kg/h]',
    dr_puissanceBruleur: 'قدرة الموقد [MW]',
    dr_flammePilote: 'اللهب التجريبي [kW]',
    dr_nombreLances: 'عدد الرماح',
    dr_nombreLancesBackup: 'عدد الرماح الاحتياطية',
    dr_volumeAir: 'حجم الهواء [Nm³/h]',
    dr_volumeVapeur: 'حجم البخار [t/h]',
    dr_consoElecAirCo: 'قدرة هواء الاحتراق [kW]',
    dr_perteEau: 'فقد الماء [m³/h]',
    dr_enthalpieRefroidissement: 'إنثالبي التبريد [MW]',
    dr_puissancePompe: 'قدرة مضخة دوران الماء [kW]',
    dr_surfaceExtFour: 'السطح الخارجي للفرن [m²]',
    dr_pertesRad: 'الفقد الحراري الإشعاعي [MW]',
    dr_pertesConv: 'الفقد الحراري الحملي [MW]',
    dr_pertesTotales: 'الفقد الحراري الكلي [MW]',
    dr_partPertes: 'نسبة الفقد الحراري [%]',
    dr_pertesRadVirole: 'فقد إشعاعي للغلاف [MW]',
    dr_pertesConvVirole: 'فقد حملي للغلاف [MW]',
    dr_pertesConvViroleTot: 'الفقد الحملي الكلي للغلاف [MW]',
    dr_consoElecVirole: 'استهلاك تبريد الغلاف [kW]',
    dr_nombreVentilateurs: 'عدد المراوح',
    dr_debitFumeesM3h: 'تدفق الغازات [m³/h]',
    dr_hauteurSCC: 'ارتفاع SCC [m]',
    dr_puissanceBruleurSCC: 'قدرة موقد SCC [MW]',
    dr_puissanceFlammePilote: 'قدرة اللهب التجريبي [kW]',
    dr_nombreLancesNb: 'عدد الرماح',
    dr_nombreLancesBackupNb: 'عدد الرماح الاحتياطية',
    dr_volumeAirAtomisation: 'حجم هواء الرش [Nm³/h]',
    dr_volumeVapeurAtomisation: 'حجم بخار الرش [t/h]',
    dr_tempParoiSCC: 'درجة حرارة جدار SCC [°C]',
    dr_surfaceSCC: 'مساحة SCC [m²]',
    dr_pthRadSCC: 'الفقد الإشعاعي SCC [MW]',
    dr_pthConvSCC: 'الفقد الحملي SCC [MW]',
    dr_pthTotSCC: 'الفقد الكلي SCC [MW]',
    dr_consoElecExtracteur: 'استهلاك كهربائي للمستخرج [kW]',
    dr_masseImbruleesKgh: 'كتلة غير المحترق [kg/h]',
    dr_co2Transport: 'CO₂ النقل [kg/km]',
    dr_coutTransport: 'تكلفة النقل [€/km]',
    dr_co2TransportTotal: 'إجمالي CO₂ النقل [kg]',
    dr_coutTransportTotal: 'إجمالي تكلفة النقل [€]',
    dr_consoElecVentiloComb: 'قدرة مروحة الاحتراق [kW]',
    dr_h2oPourcent: 'H₂O [%]',
    dr_co2Pourcent: 'CO₂ [%]',
    dr_tfumProvisoire: 'درجة حرارة الغازات [°C]',
    dr_emissiviteFume: 'انبعاثية الغازات',
    dr_teauExtracteur: 'درجة حرارة ماء المستخرج [°C]',
    dr_sEchange: 'مساحة التبادل الحراري [m²]',
    dr_coeffA: 'المعامل a',
    dr_coeffB: 'المعامل b',
    dr_coeffC: 'المعامل c',
    dr_coeffBmaj: 'المعامل B',
    dr_coeffCmaj: 'المعامل C',
    dr_facteurF: 'معامل الشكل F',
    dr_fluxRadiatif: 'التدفق الإشعاعي [kW]',
    dr_eauEvapExtracteur: 'ماء متبخر المستخرج [kg/h]',
    dr_pOutMmCE: 'ضغط الخروج [mmCE]',

    // Main navigation
    title: 'تكوين الفرن الدوار و SCC',
    combustionParameters: 'معاملات الاحتراق',
    flueGases: 'غازات المداخن',
    pollutantEmissions: 'انبعاثات الملوثات',
    design: 'التصميم',
    opex: 'نفقات التشغيل',
    backToFlow: 'العودة إلى التدفق',
    sendData: 'إرسال البيانات',
    rapport: 'تقرير',
    
    calculationParameters: 'معاملات الحساب',
    calculatedParameters: 'المعاملات المحسوبة',
    combustionAirComposition: 'تركيب هواء الاحتراق',
    atStoichiometry: 'عند التكافؤ الكيميائي',
    atAdiabaticity: 'عند الحالة الأديباتية',
    combustionAirTotal: 'إجمالي هواء الاحتراق',
    flueGasComposition: 'تركيب غازات المداخن',
    flueGasAtStoichiometry: 'غازات المداخن عند التكافؤ الكيميائي',
    outputFlueGasWithoutWater: 'غازات المداخن الخارجة بدون ماء من المستخرج',
    outputFlueGasWithWater: 'غازات المداخن الخارجة مع ماء من المستخرج',
    resetValues: 'إعادة تعيين القيم',
    export: 'تصدير',
    
    flueGasTemperatureOutlet: 'درجة حرارة مخرج غازات المداخن [°C]',
    airFactor: 'معامل الهواء',
    combustionAirTemperature: 'درجة حرارة هواء الاحتراق [°C]',
    wasteTemperature: 'درجة حرارة النفايات [°C]',
    steamWaterTemperature: 'درجة حرارة الماء البخاري',
    estimatedThermalLosses: 'الخسائر الحرارية المقدرة [%]',
    airPreheatingPart: 'جزء تسخين الهواء المسبق [%]',
    airPreheatingTemperature: 'درجة حرارة تسخين الهواء المسبق [°C]',
    airRelativeMoisture: 'الرطوبة النسبية للهواء [%]',
    waterVaporizedFromExtractor: 'الماء المتبخر من المستخرج [kg/h]',
    
    airStoechio: 'الهواء التكافئي [Kmole]',
    calculatedTemperature: 'درجة الحرارة المحسوبة [°C]',
    waterContent: 'محتوى الماء [kg/Nm3]',
    hSystem: 'H_النظام',
    airFactorCalculated: 'معامل الهواء المحسوب',

    resetDefaultValues: 'إعادة تعيين القيم الافتراضية',
    mass: 'الكتلة [kg/h]',
    wasteFlow: 'تدفق النفايات [kg/h]',
    flueGasFlowWet: 'تدفق الغاز الرطب [Nm3/h]',
    flueGasFlowDry: 'تدفق الغاز الجاف [Nm3/h]',
    o2Calculated: 'O2 محسوب [%]',
    inertMass: 'الكتلة الخاملة [kg/h]',

    mercuryTreatmentThreshold: 'عتبة معالجة الزئبق [micro g/Nm3]',
    noxIn: 'NOx دخول [mg/Nm3]',
    pcddf: 'PCDDF [micro g/Nm3]',
    hfPercent: 'HF [%]',
    cdTi: 'Cd + TI [mg/Nm3]',
    heavyMetals: 'Sb +As + Pb +Cr +Co +Cu +Mn + Ni +V [mg/Nm3]',
    flyAshesContent: 'محتوى الرماد المتطاير [g/Nm3]',
    siccityBottomAsh: 'جفاف الخبث [%]',
    o2Ref: 'O2 مرجع [%]',
    sncr: 'SNCR (الاختزال غير التحفيزي الانتقائي)',
    sncrtEnabled: 'SNCR مفعل',
    noxLimit: 'حد NOx [mg/Nm3]',
    stoichiometry: 'التكافؤ الكيميائي',
    mercuryTreatment: 'معالجة الزئبق',
    hgTreatmentEnabled: 'معالجة Hg مفعلة',
    brHgRatio: 'نسبة Br/Hg',
    pollutantTreatmentTable: 'جدول معالجة الملوثات',
    pollutant: 'ملوث',
    reactif: 'كاشف',
    massInput: 'كتلة الدخول',
    efficiency: 'الكفاءة (%)',
    stoechCoeff: 'معامل التكافؤ',
    massOutput: 'كتلة الخروج',
    massResidue: 'كتلة المخلفات',
    massReactif: 'كتلة الكاشف',
    massReduced: 'الكتلة المخفضة',
    inputFlueGas: 'غاز مداخن الدخول',
    outputFlueGas: 'غاز مداخن الخروج',
    bottomAshesCalculated: 'الخبث المحسوب',
    bottomAsh: 'خبث [kg/h]',
    bottomAshWet: 'خبث رطب [kg/h]',
    flyAsh: 'رماد متطاير [kg/h]',
    nh3Consumption: 'استهلاك NH3 [kg/h]',
    hgMass: 'كتلة Hg [kg/h]',
    bromideConsumption: 'استهلاك البروميد [kg/h]',

    aeraulicPressureLoss: 'فقدان الضغط الهوائي',
    thermicalLossParameters: 'معاملات الفقد الحراري',
    rotaryKilnDesign: 'تصميم الفرن الدوار',
    lanceEstimation: 'تقدير الرماح على الواجهة',
    facadeCooling: 'معاملات تبريد الواجهة',
    facadeThermicalLosses: 'معاملات الفقد الحراري للواجهة',
    shellCooling: 'تبريد الغلاف',
    sccDimensioning: 'تحديد أبعاد SCC',
    sccBurners: 'موقد SCC',
    sccThermicalLosses: 'تقدير الفقد الحراري لـ SCC',
    extractorConsumption: 'تقدير استهلاك المستخرج',
    combustionAirFan: 'تقدير استهلاك مروحة هواء الاحتراق',
    extractorWaterEvaporation: 'تقدير تبخر ماء المستخرج',
    warningSlope: '⚠️ تحذير: ميل الفرن يتجاوز الحد الموصى به (2-5°)',
    warningFillRate: '⚠️ تحذير: معدل الملء يتجاوز الحد الموصى به (الحد الأقصى 5%)',
    warningVelocity: '⚠️ تحذير: سرعة الغاز في SCC تتجاوز الحد الموصى به 3 م/ث',
  },
};